//! LLVM New-PM pass plugin: for every function named by an `__volar_entry`
//! marker (see `volar-llvm-plugin-api`), runs it through the full
//! LLVM-import round trip —
//!
//! 1. **DFA jump threading** (`volar-llvm-jumpthread`), in place, on the
//!    original function, before import.
//! 2. **Structural, call-preserving import into VAFFLE**
//!    (`volar-llvm-vaffle-import`) — no argument-binding descriptor is
//!    needed, unlike `cirrus-llvm-pass`'s execution-mode importer, since
//!    this walker is purely structural.
//! 3. **Replay back out to LLVM IR** (`volar-ssa-lir-replay` into
//!    `volar-llvm-backend`), into a temporary module in the same
//!    `LLVMContext`.
//!
//! ...then links the temporary module in and swaps names so every existing
//! reference to the original function (in this module, and via its link
//! symbol from any other translation unit) transparently resolves to the
//! reimported implementation. The original function is left in the module,
//! renamed out of the way — never deleted, since this pass cannot prove no
//! other not-yet-linked translation unit still references it by symbol
//! name.
//!
//! # Scope: only `i1`-shaped signatures round-trip today
//!
//! `volar-llvm-vaffle-import`'s structural importer bit-decomposes every
//! multi-bit scalar into that many individual `Bit`-typed VAFFLE values
//! (e.g. an `i32` parameter becomes 32 separate 1-bit VAFFLE params) — this
//! is VAFFLE's own data model, not something this plugin controls. Replayed
//! back out, that produces a function whose LLVM signature is 32 `i1`
//! parameters, not one `i32` parameter. This plugin never *silently*
//! narrows or repacks that mismatch into a trampoline — see the signature
//! check in [`reimport_function`] — so only functions whose original LLVM
//! signature is *already* `i1`-shaped (every parameter and the return type,
//! if any, is `i1`) round-trip successfully today. Anything else fails
//! loudly with a clear diagnostic naming both signatures, never a silent
//! miscompile. A bit-packing trampoline generator (mechanical, and
//! independent of VAFFLE semantics — see `volar-lir::circuits::pack_bits`/
//! `unpack_words` for the existing building blocks) would lift this, but is
//! its own follow-on, not attempted here.
//!
//! The C++ shim (generated by `volar-llvm-pass-build`, see `build.rs`) owns
//! LLVM's New-PM registration; this crate owns all policy.

use std::collections::BTreeMap;
use std::ffi::c_char;
use std::mem::ManuallyDrop;

use inkwell::context::Context;
use inkwell::llvm_sys::core::{
    LLVMGetArgOperand, LLVMGetInitializer, LLVMGetNumOperands, LLVMGetOperand,
};
use inkwell::llvm_sys::linker::LLVMLinkModules2;
use inkwell::llvm_sys::prelude::LLVMModuleRef;
use inkwell::module::Module;
use inkwell::values::{AsValueRef, FunctionValue, PointerValue};
use volar_llvm_constchain::{ConstChainError, function_from_pointer, strip_pointer};

const MARKER: &str = "__volar_entry";
const REIMPORT_PREFIX: &str = "__volar_reimport_";
const RENAMED_SUFFIX: &str = ".volar_orig";

#[derive(Debug)]
struct PassError(String);

impl PassError {
    fn new(message: impl Into<String>) -> Self {
        Self(message.into())
    }
}

impl core::fmt::Display for PassError {
    fn fmt(&self, formatter: &mut core::fmt::Formatter<'_>) -> core::fmt::Result {
        self.0.fmt(formatter)
    }
}

impl From<ConstChainError> for PassError {
    fn from(error: ConstChainError) -> Self {
        PassError::new(error.to_string())
    }
}

unsafe extern "C" {
    fn volar_llvm_plugin_link_anchor();
}

/// C++ calls this with an LLVM-owned module. `0` means no `__volar_entry`
/// markers were found, `1` means at least one function was reimported, and
/// `-1` returns an allocated diagnostic.
#[unsafe(no_mangle)]
pub unsafe extern "C" fn volar_llvm_plugin_run(
    raw_module: LLVMModuleRef,
    error: *mut *mut c_char,
) -> i32 {
    // SAFETY: this empty C++ function deliberately anchors the pass-plugin
    // archive member containing llvmGetPassPluginInfo in the final cdylib.
    unsafe { volar_llvm_plugin_link_anchor() };
    // SAFETY: the C++ pass manager owns raw_module for the duration of this
    // call; `run_pass_body` borrows it without disposing it, and catches
    // any panic before it can unwind across this `extern "C"` boundary.
    unsafe { volar_llvm_pass_support::run_pass_body(raw_module, error, run_on_module) }
}

/// Release a diagnostic allocated by [`volar_llvm_plugin_run`].
#[unsafe(no_mangle)]
pub unsafe extern "C" fn volar_llvm_plugin_free_error(error: *mut c_char) {
    // SAFETY: forwarded to `volar_llvm_pass_support::free_error`'s own
    // requirement -- `error` is null, or a pointer `run_pass_body`
    // previously allocated.
    unsafe { volar_llvm_pass_support::free_error(error) }
}

fn run_on_module<'ctx>(context: &'ctx Context, module: &Module<'ctx>) -> Result<bool, PassError> {
    let marker_calls = volar_llvm_pass_support::find_calls_to(module, MARKER);
    if marker_calls.is_empty() {
        return Ok(false);
    }

    let mut targets = Vec::with_capacity(marker_calls.len());
    for found in &marker_calls {
        let callee = found
            .call
            .get_called_fn_value()
            .expect("find_calls_to only returns calls with a resolved callee");
        volar_llvm_pass_support::validate_marker_declaration(callee, MARKER, 1)
            .map_err(PassError::new)?;
        if found.call.count_arguments() != 1 {
            return Err(PassError::new(
                "__volar_entry must take exactly (ptr target)",
            ));
        }
        // SAFETY: count_arguments above proves this argument slot exists.
        let raw_target = unsafe { LLVMGetArgOperand(found.call.as_value_ref(), 0) };
        targets.push(function_from_pointer(raw_target, "__volar_entry target")?);
    }

    for &target in &targets {
        reimport_function(context, module, target)?;
    }

    // Mirror cirrus-llvm-pass's marker-cleanup sequence: erase the calls,
    // then any single-block "call the marker, then return" wrapper
    // functions (and the `llvm.used` entries retaining them) that only
    // existed to keep those calls alive through optimization, then the
    // marker declaration itself.
    let wrapper_owners: BTreeMap<usize, FunctionValue<'ctx>> = marker_calls
        .iter()
        .filter(|found| volar_llvm_pass_support::is_marker_wrapper(found.caller, MARKER))
        .map(|found| (found.caller.as_value_ref() as usize, found.caller))
        .collect();
    let retention_globals =
        volar_llvm_pass_support::retained_wrapper_globals(module, &wrapper_owners);

    let mut discarded: std::collections::BTreeSet<usize> = wrapper_owners.keys().copied().collect();
    discarded.extend(retention_globals.keys().copied());
    discard_llvm_used_entries(context, module, &discarded)?;

    for found in &marker_calls {
        // SAFETY: calls were discovered before the module was mutated
        // beyond `reimport_function`'s own additions, which never
        // reference these instructions.
        found.instruction.erase_from_basic_block();
    }
    for retention in retention_globals.into_values() {
        // SAFETY: it was an `llvm.used`-only marker holder, removed from
        // that list above, and the wrapper it referenced has no runtime role.
        unsafe { retention.delete() };
    }
    for wrapper in wrapper_owners.into_values() {
        // SAFETY: discarded `llvm.used` entries were removed above, and the
        // wrapper consists exclusively of pseudo-intrinsic marker calls
        // (that's the definition `is_marker_wrapper` checked).
        unsafe { wrapper.delete() };
    }
    if let Some(marker) = module.get_function(MARKER) {
        // SAFETY: every direct use was erased above, and a valid marker is
        // a declaration only (validated while scanning it).
        unsafe { marker.delete() };
    }

    Ok(true)
}

/// Rewrite `llvm.used`, dropping any entry whose (possibly bitcast-wrapped)
/// pointee is in `discarded`. Extracted verbatim (down to the "delete and
/// recreate the global" approach -- `llvm.used`'s array length is baked
/// into its own declared type, not just its initializer, so shrinking it
/// requires a fresh global, not an in-place `set_initializer`) from
/// `cirrus-llvm-pass`'s own helper of the same purpose. Not yet promoted to
/// `volar-llvm-pass-support` since this is still this crate's only caller.
fn discard_llvm_used_entries<'ctx>(
    context: &'ctx Context,
    module: &Module<'ctx>,
    discarded: &std::collections::BTreeSet<usize>,
) -> Result<(), PassError> {
    let Some(used) = module.get_global("llvm.used") else {
        return Ok(());
    };
    let initializer = unsafe { LLVMGetInitializer(used.as_value_ref()) };
    if initializer.is_null() {
        return Err(PassError::new("llvm.used must have a constant initializer"));
    }
    let mut retained = Vec::<PointerValue<'_>>::new();
    for index in 0..unsafe { LLVMGetNumOperands(initializer) } as u32 {
        let entry = unsafe { LLVMGetOperand(initializer, index) };
        let is_discarded = strip_pointer(entry, "llvm.used entry")
            .ok()
            .is_some_and(|value| discarded.contains(&(value as usize)));
        if !is_discarded {
            // SAFETY: llvm.used is an array of pointer constants by LLVM's
            // special-global contract.
            retained.push(unsafe { PointerValue::new(entry) });
        }
    }
    // SAFETY: replacing this special global is valid after retaining all
    // unrelated entries, and no generated operation refers to it.
    unsafe { used.delete() };
    if retained.is_empty() {
        return Ok(());
    }
    let pointer = context.ptr_type(inkwell::AddressSpace::default());
    let replacement =
        module.add_global(pointer.array_type(retained.len() as u32), None, "llvm.used");
    replacement.set_linkage(inkwell::module::Linkage::Appending);
    replacement.set_section(Some("llvm.metadata"));
    replacement.set_initializer(&pointer.const_array(&retained));
    Ok(())
}

/// DFA-jump-thread, structurally import, and replay `target` back out to
/// LLVM IR in place, splicing the reimplementation in under `target`'s
/// original name.
fn reimport_function<'ctx>(
    context: &'ctx Context,
    module: &Module<'ctx>,
    target: FunctionValue<'ctx>,
) -> Result<(), PassError> {
    if target.count_basic_blocks() == 0 {
        return Err(PassError::new(format!(
            "__volar_entry target `{}` is a declaration, not a definition",
            target.get_name().to_string_lossy()
        )));
    }
    let target_name = target
        .get_name()
        .to_str()
        .map_err(|_| PassError::new("__volar_entry target name is not valid UTF-8"))?
        .to_string();

    // Phase 5: DFA jump threading, in place, before import -- unfolds any
    // statically-enumerable dispatch loop into concrete control flow so the
    // structural importer sees plainer control flow (jump threading itself
    // never requires this; it's simply always safe to run first).
    volar_llvm_jumpthread::thread_jumps(target, volar_llvm_jumpthread::JumpThreadLimits::default());

    // Phase 2: structural, call-preserving import into VAFFLE. Everything
    // `target` transitively calls (in this module) comes along as its own
    // `vaffle::Func`, never inlined.
    let vaffle_module = volar_llvm_vaffle_import::import_module(module, &[&target_name])
        .map_err(|error| PassError::new(format!("importing `{target_name}`: {error}")))?;

    // Replay back out to a temporary module in the *same* LLVMContext (so
    // it can be linked into the original), with every emitted function
    // prefixed to avoid name collisions with `module` while both
    // temporarily coexist.
    let mut backend = volar_llvm_backend::LlvmBackend::new(context, "volar_reimport_tmp")
        .with_prefix(REIMPORT_PREFIX);
    volar_ssa_lir_replay::lower_vaffle_module(&vaffle_module, &mut backend);
    let temp_module = backend.finish();

    // `LLVMLinkModules2` destroys its source module on success; wrap it so
    // this crate's own `Module::drop` doesn't also try to dispose an
    // already-freed module.
    let temp_module = ManuallyDrop::new(temp_module);
    // SAFETY: both modules share `context`; `module` outlives this call
    // (borrowed from the pass manager), and `temp_module` was just built
    // fresh above and is never touched again after this call succeeds.
    let failed = unsafe { LLVMLinkModules2(module.as_mut_ptr(), temp_module.as_mut_ptr()) };
    if failed != 0 {
        return Err(PassError::new(format!(
            "linking the reimported `{target_name}` into the module failed"
        )));
    }

    let reimported_name = format!("{REIMPORT_PREFIX}{target_name}");
    let reimported = module.get_function(&reimported_name).ok_or_else(|| {
        PassError::new(format!(
            "reimported function `{reimported_name}` missing after link"
        ))
    })?;

    if target.get_type() != reimported.get_type() {
        return Err(PassError::new(format!(
            "reimported `{target_name}` has a different LLVM signature ({:?}) than the original ({:?}) -- \
             only i1-shaped signatures round-trip today (see this crate's top-level docs): a wider scalar \
             parameter/return (e.g. i32) gets bit-decomposed into that many individual i1 VAFFLE values by \
             the structural importer, which is a mismatch this plugin refuses to paper over with an implicit \
             bit-packing trampoline",
            reimported.get_type(),
            target.get_type(),
        )));
    }

    // Redirect every existing in-module use to the reimplementation, then
    // free the original symbol name for it -- any not-yet-linked
    // translation unit that later resolves `target_name` by symbol will
    // transparently get the reimplementation too. `target` itself is left
    // in the module (renamed, unreferenced by anything generated here) --
    // never deleted, since this pass cannot prove no other translation unit
    // still references its symbol before final link.
    target.replace_all_uses_with(reimported);
    target
        .as_global_value()
        .set_name(&format!("{target_name}{RENAMED_SUFFIX}"));
    reimported.as_global_value().set_name(&target_name);

    Ok(())
}
