[package]
name = "volar-ir-virt"
version = "0.1.0"
edition = "2024"
license.workspace = true
description.workspace = true
repository.workspace = true

[dependencies]
volar-ir = { workspace = true, features = ["rkyv"] }
volar-ir-common.workspace = true
volar-ir-passes.workspace = true
volar-provenance.workspace = true
volar-lir.workspace = true

[dev-dependencies]
volar-fuzz.workspace = true
volar-ir-opt.workspace = true
rkyv.workspace = true
