// Generated by volar-ir-schema-gen; do not edit.
//
// This code deliberately implements rkyv's three traits directly and
// generates byte validation for archived values. The archived layout matches
// rkyv_derive's `#[repr(C)]` scalar-newtype layout, so pinned-rkyv binary
// artifacts remain byte-compatible.

/// Opaque identifier of a bit-granular storage lane.
#[derive(Clone, Copy, PartialEq, Eq, PartialOrd, Ord, Hash, Debug)]
pub struct LaneId(pub u32);

#[cfg(feature = "rkyv")]
#[derive(Clone, Copy, PartialEq, Eq, PartialOrd, Ord, Debug, rkyv::bytecheck::CheckBytes)]
#[bytecheck(crate = rkyv::bytecheck)]
#[repr(C)]
pub struct ArchivedLaneId(pub rkyv::primitive::ArchivedU32);

#[cfg(feature = "rkyv")]
unsafe impl rkyv::Portable for ArchivedLaneId {}

#[cfg(feature = "rkyv")]
impl rkyv::Archive for LaneId {
    type Archived = ArchivedLaneId;
    type Resolver = ();

    fn resolve(&self, (): Self::Resolver, out: rkyv::Place<Self::Archived>) {
        // SAFETY: the generated archived newtype is repr(C), contains exactly
        // one initialized portable scalar, and has no padding.
        unsafe {
            out.write_unchecked(ArchivedLaneId(rkyv::primitive::ArchivedU32::from_native(self.0)))
        }
    }
}

#[cfg(feature = "rkyv")]
impl<S: rkyv::rancor::Fallible + ?Sized> rkyv::Serialize<S> for LaneId {
    fn serialize(&self, _: &mut S) -> Result<Self::Resolver, S::Error> {
        Ok(())
    }
}

#[cfg(feature = "rkyv")]
impl<D: rkyv::rancor::Fallible + ?Sized> rkyv::Deserialize<LaneId, D>
    for ArchivedLaneId
{
    fn deserialize(&self, _: &mut D) -> Result<LaneId, D::Error> {
        Ok(LaneId(self.0.to_native()))
    }
}

/// A bit-granular pre-initialised storage segment.
#[derive(Clone, PartialEq, Eq, PartialOrd, Ord, Hash, Debug)]
pub struct BIrPreInitSegment {
    pub storage: volar_ir_common::StorageId,
    pub lane: LaneId,
    pub addr: alloc::vec::Vec<bool>,
    pub data: alloc::vec::Vec<bool>,
}

#[cfg(feature = "rkyv")]
#[derive(rkyv::bytecheck::CheckBytes)]
#[bytecheck(crate = rkyv::bytecheck)]
#[repr(C)]
pub struct ArchivedBIrPreInitSegment {
    pub storage: <volar_ir_common::StorageId as rkyv::Archive>::Archived,
    pub lane: <LaneId as rkyv::Archive>::Archived,
    pub addr: <alloc::vec::Vec<bool> as rkyv::Archive>::Archived,
    pub data: <alloc::vec::Vec<bool> as rkyv::Archive>::Archived,
}

#[cfg(feature = "rkyv")]
#[allow(dead_code)]
pub struct BIrPreInitSegmentResolver {
    storage: <volar_ir_common::StorageId as rkyv::Archive>::Resolver,
    lane: <LaneId as rkyv::Archive>::Resolver,
    addr: <alloc::vec::Vec<bool> as rkyv::Archive>::Resolver,
    data: <alloc::vec::Vec<bool> as rkyv::Archive>::Resolver,
}

#[cfg(feature = "rkyv")]
unsafe impl rkyv::Portable for ArchivedBIrPreInitSegment
where
    <volar_ir_common::StorageId as rkyv::Archive>::Archived: rkyv::Portable,
    <LaneId as rkyv::Archive>::Archived: rkyv::Portable,
    <alloc::vec::Vec<bool> as rkyv::Archive>::Archived: rkyv::Portable,
    <alloc::vec::Vec<bool> as rkyv::Archive>::Archived: rkyv::Portable,
{}

#[cfg(feature = "rkyv")]
impl rkyv::Archive for BIrPreInitSegment {
    type Archived = ArchivedBIrPreInitSegment;
    type Resolver = BIrPreInitSegmentResolver;

    fn resolve(&self, resolver: Self::Resolver, out: rkyv::Place<Self::Archived>) {
        let field_ptr = unsafe { ::core::ptr::addr_of_mut!((*out.ptr()).storage) };
        let field_out = unsafe { rkyv::Place::from_field_unchecked(out, field_ptr) };
        rkyv::Archive::resolve(&self.storage, resolver.storage, field_out);
        let field_ptr = unsafe { ::core::ptr::addr_of_mut!((*out.ptr()).lane) };
        let field_out = unsafe { rkyv::Place::from_field_unchecked(out, field_ptr) };
        rkyv::Archive::resolve(&self.lane, resolver.lane, field_out);
        let field_ptr = unsafe { ::core::ptr::addr_of_mut!((*out.ptr()).addr) };
        let field_out = unsafe { rkyv::Place::from_field_unchecked(out, field_ptr) };
        rkyv::Archive::resolve(&self.addr, resolver.addr, field_out);
        let field_ptr = unsafe { ::core::ptr::addr_of_mut!((*out.ptr()).data) };
        let field_out = unsafe { rkyv::Place::from_field_unchecked(out, field_ptr) };
        rkyv::Archive::resolve(&self.data, resolver.data, field_out);
    }
}

#[cfg(feature = "rkyv")]
impl<S: rkyv::rancor::Fallible + ?Sized> rkyv::Serialize<S> for BIrPreInitSegment
where
    volar_ir_common::StorageId: rkyv::Serialize<S>,
    LaneId: rkyv::Serialize<S>,
    alloc::vec::Vec<bool>: rkyv::Serialize<S>,
    alloc::vec::Vec<bool>: rkyv::Serialize<S>,
{
    fn serialize(&self, serializer: &mut S) -> Result<Self::Resolver, S::Error> {
        Ok(BIrPreInitSegmentResolver {
            storage: rkyv::Serialize::serialize(&self.storage, serializer)?,
            lane: rkyv::Serialize::serialize(&self.lane, serializer)?,
            addr: rkyv::Serialize::serialize(&self.addr, serializer)?,
            data: rkyv::Serialize::serialize(&self.data, serializer)?,
        })
    }
}

#[cfg(feature = "rkyv")]
impl<D: rkyv::rancor::Fallible + ?Sized> rkyv::Deserialize<BIrPreInitSegment, D>
    for ArchivedBIrPreInitSegment
where
    <volar_ir_common::StorageId as rkyv::Archive>::Archived: rkyv::Deserialize<volar_ir_common::StorageId, D>,
    <LaneId as rkyv::Archive>::Archived: rkyv::Deserialize<LaneId, D>,
    <alloc::vec::Vec<bool> as rkyv::Archive>::Archived: rkyv::Deserialize<alloc::vec::Vec<bool>, D>,
    <alloc::vec::Vec<bool> as rkyv::Archive>::Archived: rkyv::Deserialize<alloc::vec::Vec<bool>, D>,
{
    fn deserialize(&self, deserializer: &mut D) -> Result<BIrPreInitSegment, D::Error> {
        Ok(BIrPreInitSegment {
            storage: rkyv::Deserialize::deserialize(&self.storage, deserializer)?,
            lane: rkyv::Deserialize::deserialize(&self.lane, deserializer)?,
            addr: rkyv::Deserialize::deserialize(&self.addr, deserializer)?,
            data: rkyv::Deserialize::deserialize(&self.data, deserializer)?,
        })
    }
}

/// A complete Boolar circuit module with bit blocks and pre-initialized storage.
#[derive(Clone, PartialEq, Eq, PartialOrd, Ord, Hash, Debug)]
pub struct BIrBlocks<P: Clone = ()> {
    pub blocks: alloc::vec::Vec<crate::boolar::BIrBlock<P>>,
    pub pre_init: alloc::vec::Vec<crate::boolar::BIrPreInitSegment>,
}

#[cfg(feature = "rkyv")]
#[derive(rkyv::bytecheck::CheckBytes)]
#[bytecheck(crate = rkyv::bytecheck)]
#[repr(C)]
pub struct ArchivedBIrBlocks<P: Clone + rkyv::Archive = ()> {
    pub blocks: <alloc::vec::Vec<crate::boolar::BIrBlock<P>> as rkyv::Archive>::Archived,
    pub pre_init: <alloc::vec::Vec<crate::boolar::BIrPreInitSegment> as rkyv::Archive>::Archived,
}

#[cfg(feature = "rkyv")]
#[allow(dead_code)]
pub struct BIrBlocksResolver<P: Clone + rkyv::Archive = ()> {
    blocks: <alloc::vec::Vec<crate::boolar::BIrBlock<P>> as rkyv::Archive>::Resolver,
    pre_init: <alloc::vec::Vec<crate::boolar::BIrPreInitSegment> as rkyv::Archive>::Resolver,
}

#[cfg(feature = "rkyv")]
unsafe impl<P: Clone + rkyv::Archive> rkyv::Portable for ArchivedBIrBlocks<P>
where
    <alloc::vec::Vec<crate::boolar::BIrBlock<P>> as rkyv::Archive>::Archived: rkyv::Portable,
    <alloc::vec::Vec<crate::boolar::BIrPreInitSegment> as rkyv::Archive>::Archived: rkyv::Portable,
{}

#[cfg(feature = "rkyv")]
impl<P: Clone + rkyv::Archive> rkyv::Archive for BIrBlocks<P> {
    type Archived = ArchivedBIrBlocks<P>;
    type Resolver = BIrBlocksResolver<P>;

    fn resolve(&self, resolver: Self::Resolver, out: rkyv::Place<Self::Archived>) {
        let field_ptr = unsafe { ::core::ptr::addr_of_mut!((*out.ptr()).blocks) };
        let field_out = unsafe { rkyv::Place::from_field_unchecked(out, field_ptr) };
        rkyv::Archive::resolve(&self.blocks, resolver.blocks, field_out);
        let field_ptr = unsafe { ::core::ptr::addr_of_mut!((*out.ptr()).pre_init) };
        let field_out = unsafe { rkyv::Place::from_field_unchecked(out, field_ptr) };
        rkyv::Archive::resolve(&self.pre_init, resolver.pre_init, field_out);
    }
}

#[cfg(feature = "rkyv")]
impl<P: Clone + rkyv::Archive, S: rkyv::rancor::Fallible + ?Sized> rkyv::Serialize<S> for BIrBlocks<P>
where
    alloc::vec::Vec<crate::boolar::BIrBlock<P>>: rkyv::Serialize<S>,
    alloc::vec::Vec<crate::boolar::BIrPreInitSegment>: rkyv::Serialize<S>,
{
    fn serialize(&self, serializer: &mut S) -> Result<Self::Resolver, S::Error> {
        Ok(BIrBlocksResolver {
            blocks: rkyv::Serialize::serialize(&self.blocks, serializer)?,
            pre_init: rkyv::Serialize::serialize(&self.pre_init, serializer)?,
        })
    }
}

#[cfg(feature = "rkyv")]
impl<P: Clone + rkyv::Archive, D: rkyv::rancor::Fallible + ?Sized> rkyv::Deserialize<BIrBlocks<P>, D>
    for ArchivedBIrBlocks<P>
where
    <alloc::vec::Vec<crate::boolar::BIrBlock<P>> as rkyv::Archive>::Archived: rkyv::Deserialize<alloc::vec::Vec<crate::boolar::BIrBlock<P>>, D>,
    <alloc::vec::Vec<crate::boolar::BIrPreInitSegment> as rkyv::Archive>::Archived: rkyv::Deserialize<alloc::vec::Vec<crate::boolar::BIrPreInitSegment>, D>,
{
    fn deserialize(&self, deserializer: &mut D) -> Result<BIrBlocks<P>, D::Error> {
        Ok(BIrBlocks {
            blocks: rkyv::Deserialize::deserialize(&self.blocks, deserializer)?,
            pre_init: rkyv::Deserialize::deserialize(&self.pre_init, deserializer)?,
        })
    }
}

/// One Boolar block with bit statements and a terminator.
#[derive(Clone, PartialEq, Eq, PartialOrd, Ord, Hash, Debug)]
pub struct BIrBlock<P: Clone = ()> {
    pub params: u32,
    pub stmts: alloc::vec::Vec<volar_ir_common::Node<crate::boolar::BIrStmt, P>>,
    pub terminator: crate::boolar::BIrTerminator,
}

#[cfg(feature = "rkyv")]
#[derive(rkyv::bytecheck::CheckBytes)]
#[bytecheck(crate = rkyv::bytecheck)]
#[repr(C)]
pub struct ArchivedBIrBlock<P: Clone + rkyv::Archive = ()> {
    pub params: <u32 as rkyv::Archive>::Archived,
    pub stmts: <alloc::vec::Vec<volar_ir_common::Node<crate::boolar::BIrStmt, P>> as rkyv::Archive>::Archived,
    pub terminator: <crate::boolar::BIrTerminator as rkyv::Archive>::Archived,
}

#[cfg(feature = "rkyv")]
#[allow(dead_code)]
pub struct BIrBlockResolver<P: Clone + rkyv::Archive = ()> {
    params: <u32 as rkyv::Archive>::Resolver,
    stmts: <alloc::vec::Vec<volar_ir_common::Node<crate::boolar::BIrStmt, P>> as rkyv::Archive>::Resolver,
    terminator: <crate::boolar::BIrTerminator as rkyv::Archive>::Resolver,
}

#[cfg(feature = "rkyv")]
unsafe impl<P: Clone + rkyv::Archive> rkyv::Portable for ArchivedBIrBlock<P>
where
    <u32 as rkyv::Archive>::Archived: rkyv::Portable,
    <alloc::vec::Vec<volar_ir_common::Node<crate::boolar::BIrStmt, P>> as rkyv::Archive>::Archived: rkyv::Portable,
    <crate::boolar::BIrTerminator as rkyv::Archive>::Archived: rkyv::Portable,
{}

#[cfg(feature = "rkyv")]
impl<P: Clone + rkyv::Archive> rkyv::Archive for BIrBlock<P> {
    type Archived = ArchivedBIrBlock<P>;
    type Resolver = BIrBlockResolver<P>;

    fn resolve(&self, resolver: Self::Resolver, out: rkyv::Place<Self::Archived>) {
        let field_ptr = unsafe { ::core::ptr::addr_of_mut!((*out.ptr()).params) };
        let field_out = unsafe { rkyv::Place::from_field_unchecked(out, field_ptr) };
        rkyv::Archive::resolve(&self.params, resolver.params, field_out);
        let field_ptr = unsafe { ::core::ptr::addr_of_mut!((*out.ptr()).stmts) };
        let field_out = unsafe { rkyv::Place::from_field_unchecked(out, field_ptr) };
        rkyv::Archive::resolve(&self.stmts, resolver.stmts, field_out);
        let field_ptr = unsafe { ::core::ptr::addr_of_mut!((*out.ptr()).terminator) };
        let field_out = unsafe { rkyv::Place::from_field_unchecked(out, field_ptr) };
        rkyv::Archive::resolve(&self.terminator, resolver.terminator, field_out);
    }
}

#[cfg(feature = "rkyv")]
impl<P: Clone + rkyv::Archive, S: rkyv::rancor::Fallible + ?Sized> rkyv::Serialize<S> for BIrBlock<P>
where
    u32: rkyv::Serialize<S>,
    alloc::vec::Vec<volar_ir_common::Node<crate::boolar::BIrStmt, P>>: rkyv::Serialize<S>,
    crate::boolar::BIrTerminator: rkyv::Serialize<S>,
{
    fn serialize(&self, serializer: &mut S) -> Result<Self::Resolver, S::Error> {
        Ok(BIrBlockResolver {
            params: rkyv::Serialize::serialize(&self.params, serializer)?,
            stmts: rkyv::Serialize::serialize(&self.stmts, serializer)?,
            terminator: rkyv::Serialize::serialize(&self.terminator, serializer)?,
        })
    }
}

#[cfg(feature = "rkyv")]
impl<P: Clone + rkyv::Archive, D: rkyv::rancor::Fallible + ?Sized> rkyv::Deserialize<BIrBlock<P>, D>
    for ArchivedBIrBlock<P>
where
    <u32 as rkyv::Archive>::Archived: rkyv::Deserialize<u32, D>,
    <alloc::vec::Vec<volar_ir_common::Node<crate::boolar::BIrStmt, P>> as rkyv::Archive>::Archived: rkyv::Deserialize<alloc::vec::Vec<volar_ir_common::Node<crate::boolar::BIrStmt, P>>, D>,
    <crate::boolar::BIrTerminator as rkyv::Archive>::Archived: rkyv::Deserialize<crate::boolar::BIrTerminator, D>,
{
    fn deserialize(&self, deserializer: &mut D) -> Result<BIrBlock<P>, D::Error> {
        Ok(BIrBlock {
            params: rkyv::Deserialize::deserialize(&self.params, deserializer)?,
            stmts: rkyv::Deserialize::deserialize(&self.stmts, deserializer)?,
            terminator: rkyv::Deserialize::deserialize(&self.terminator, deserializer)?,
        })
    }
}

/// A Boolar branch destination and its argument list.
#[derive(Clone, PartialEq, Eq, PartialOrd, Ord, Hash, Debug)]
pub struct BIrTarget<Var = crate::ir::IRVarId> {
    pub block: crate::ir::IRBlockTargetId<Var>,
    pub args: alloc::vec::Vec<Var>,
}

#[cfg(feature = "rkyv")]
#[derive(rkyv::bytecheck::CheckBytes)]
#[bytecheck(crate = rkyv::bytecheck)]
#[repr(C)]
pub struct ArchivedBIrTarget<Var: rkyv::Archive = crate::ir::IRVarId> {
    pub block: <crate::ir::IRBlockTargetId<Var> as rkyv::Archive>::Archived,
    pub args: <alloc::vec::Vec<Var> as rkyv::Archive>::Archived,
}

#[cfg(feature = "rkyv")]
#[allow(dead_code)]
pub struct BIrTargetResolver<Var: rkyv::Archive = crate::ir::IRVarId> {
    block: <crate::ir::IRBlockTargetId<Var> as rkyv::Archive>::Resolver,
    args: <alloc::vec::Vec<Var> as rkyv::Archive>::Resolver,
}

#[cfg(feature = "rkyv")]
unsafe impl<Var: rkyv::Archive> rkyv::Portable for ArchivedBIrTarget<Var>
where
    <crate::ir::IRBlockTargetId<Var> as rkyv::Archive>::Archived: rkyv::Portable,
    <alloc::vec::Vec<Var> as rkyv::Archive>::Archived: rkyv::Portable,
{}

#[cfg(feature = "rkyv")]
impl<Var: rkyv::Archive> rkyv::Archive for BIrTarget<Var> {
    type Archived = ArchivedBIrTarget<Var>;
    type Resolver = BIrTargetResolver<Var>;

    fn resolve(&self, resolver: Self::Resolver, out: rkyv::Place<Self::Archived>) {
        let field_ptr = unsafe { ::core::ptr::addr_of_mut!((*out.ptr()).block) };
        let field_out = unsafe { rkyv::Place::from_field_unchecked(out, field_ptr) };
        rkyv::Archive::resolve(&self.block, resolver.block, field_out);
        let field_ptr = unsafe { ::core::ptr::addr_of_mut!((*out.ptr()).args) };
        let field_out = unsafe { rkyv::Place::from_field_unchecked(out, field_ptr) };
        rkyv::Archive::resolve(&self.args, resolver.args, field_out);
    }
}

#[cfg(feature = "rkyv")]
impl<Var: rkyv::Archive, S: rkyv::rancor::Fallible + ?Sized> rkyv::Serialize<S> for BIrTarget<Var>
where
    crate::ir::IRBlockTargetId<Var>: rkyv::Serialize<S>,
    alloc::vec::Vec<Var>: rkyv::Serialize<S>,
{
    fn serialize(&self, serializer: &mut S) -> Result<Self::Resolver, S::Error> {
        Ok(BIrTargetResolver {
            block: rkyv::Serialize::serialize(&self.block, serializer)?,
            args: rkyv::Serialize::serialize(&self.args, serializer)?,
        })
    }
}

#[cfg(feature = "rkyv")]
impl<Var: rkyv::Archive, D: rkyv::rancor::Fallible + ?Sized> rkyv::Deserialize<BIrTarget<Var>, D>
    for ArchivedBIrTarget<Var>
where
    <crate::ir::IRBlockTargetId<Var> as rkyv::Archive>::Archived: rkyv::Deserialize<crate::ir::IRBlockTargetId<Var>, D>,
    <alloc::vec::Vec<Var> as rkyv::Archive>::Archived: rkyv::Deserialize<alloc::vec::Vec<Var>, D>,
{
    fn deserialize(&self, deserializer: &mut D) -> Result<BIrTarget<Var>, D::Error> {
        Ok(BIrTarget {
            block: rkyv::Deserialize::deserialize(&self.block, deserializer)?,
            args: rkyv::Deserialize::deserialize(&self.args, deserializer)?,
        })
    }
}
