// Generated by volar-ir-schema-gen; do not edit.
//
// This code deliberately implements rkyv's three traits directly and
// generates byte validation for archived values. The archived layout matches
// rkyv_derive's `#[repr(C)]` scalar-newtype layout, so pinned-rkyv binary
// artifacts remain byte-compatible.

/// Opaque index of a block in an IR block list.
#[derive(Clone, Copy, PartialEq, Eq, PartialOrd, Ord, Hash, Debug)]
pub struct IRBlockId(pub u32);

#[cfg(feature = "rkyv")]
#[derive(Clone, Copy, PartialEq, Eq, PartialOrd, Ord, Debug, rkyv::bytecheck::CheckBytes)]
#[bytecheck(crate = rkyv::bytecheck)]
#[repr(C)]
pub struct ArchivedIRBlockId(pub rkyv::primitive::ArchivedU32);

#[cfg(feature = "rkyv")]
unsafe impl rkyv::Portable for ArchivedIRBlockId {}

#[cfg(feature = "rkyv")]
impl rkyv::Archive for IRBlockId {
    type Archived = ArchivedIRBlockId;
    type Resolver = ();

    fn resolve(&self, (): Self::Resolver, out: rkyv::Place<Self::Archived>) {
        // SAFETY: the generated archived newtype is repr(C), contains exactly
        // one initialized portable scalar, and has no padding.
        unsafe {
            out.write_unchecked(ArchivedIRBlockId(rkyv::primitive::ArchivedU32::from_native(self.0)))
        }
    }
}

#[cfg(feature = "rkyv")]
impl<S: rkyv::rancor::Fallible + ?Sized> rkyv::Serialize<S> for IRBlockId {
    fn serialize(&self, _: &mut S) -> Result<Self::Resolver, S::Error> {
        Ok(())
    }
}

#[cfg(feature = "rkyv")]
impl<D: rkyv::rancor::Fallible + ?Sized> rkyv::Deserialize<IRBlockId, D>
    for ArchivedIRBlockId
{
    fn deserialize(&self, _: &mut D) -> Result<IRBlockId, D::Error> {
        Ok(IRBlockId(self.0.to_native()))
    }
}

/// Opaque identifier of an SSA value in a block.
#[derive(Clone, Copy, PartialEq, Eq, PartialOrd, Ord, Hash, Debug)]
pub struct IRVarId(pub u32);

#[cfg(feature = "rkyv")]
#[derive(Clone, Copy, PartialEq, Eq, PartialOrd, Ord, Debug, rkyv::bytecheck::CheckBytes)]
#[bytecheck(crate = rkyv::bytecheck)]
#[repr(C)]
pub struct ArchivedIRVarId(pub rkyv::primitive::ArchivedU32);

#[cfg(feature = "rkyv")]
unsafe impl rkyv::Portable for ArchivedIRVarId {}

#[cfg(feature = "rkyv")]
impl rkyv::Archive for IRVarId {
    type Archived = ArchivedIRVarId;
    type Resolver = ();

    fn resolve(&self, (): Self::Resolver, out: rkyv::Place<Self::Archived>) {
        // SAFETY: the generated archived newtype is repr(C), contains exactly
        // one initialized portable scalar, and has no padding.
        unsafe {
            out.write_unchecked(ArchivedIRVarId(rkyv::primitive::ArchivedU32::from_native(self.0)))
        }
    }
}

#[cfg(feature = "rkyv")]
impl<S: rkyv::rancor::Fallible + ?Sized> rkyv::Serialize<S> for IRVarId {
    fn serialize(&self, _: &mut S) -> Result<Self::Resolver, S::Error> {
        Ok(())
    }
}

#[cfg(feature = "rkyv")]
impl<D: rkyv::rancor::Fallible + ?Sized> rkyv::Deserialize<IRVarId, D>
    for ArchivedIRVarId
{
    fn deserialize(&self, _: &mut D) -> Result<IRVarId, D::Error> {
        Ok(IRVarId(self.0.to_native()))
    }
}

/// A complete Volar IR circuit module with declarations, blocks, and pre-initialized storage.
#[derive(Clone, PartialEq, Eq, PartialOrd, Ord, Hash, Debug)]
pub struct IRBlocks<P: Clone = ()> {
    pub oracles: alloc::vec::Vec<volar_ir_common::OracleDecl>,
    pub actions: alloc::vec::Vec<volar_ir_common::ActionDecl>,
    pub rngs: alloc::vec::Vec<volar_ir_common::RngDecl>,
    pub blocks: alloc::vec::Vec<crate::ir::IRBlock<P>>,
    pub pre_init: alloc::vec::Vec<volar_ir_common::PreInitSegment>,
}

#[cfg(feature = "rkyv")]
#[derive(rkyv::bytecheck::CheckBytes)]
#[bytecheck(crate = rkyv::bytecheck)]
#[repr(C)]
pub struct ArchivedIRBlocks<P: Clone + rkyv::Archive = ()> {
    pub oracles: <alloc::vec::Vec<volar_ir_common::OracleDecl> as rkyv::Archive>::Archived,
    pub actions: <alloc::vec::Vec<volar_ir_common::ActionDecl> as rkyv::Archive>::Archived,
    pub rngs: <alloc::vec::Vec<volar_ir_common::RngDecl> as rkyv::Archive>::Archived,
    pub blocks: <alloc::vec::Vec<crate::ir::IRBlock<P>> as rkyv::Archive>::Archived,
    pub pre_init: <alloc::vec::Vec<volar_ir_common::PreInitSegment> as rkyv::Archive>::Archived,
}

#[cfg(feature = "rkyv")]
#[allow(dead_code)]
pub struct IRBlocksResolver<P: Clone + rkyv::Archive = ()> {
    oracles: <alloc::vec::Vec<volar_ir_common::OracleDecl> as rkyv::Archive>::Resolver,
    actions: <alloc::vec::Vec<volar_ir_common::ActionDecl> as rkyv::Archive>::Resolver,
    rngs: <alloc::vec::Vec<volar_ir_common::RngDecl> as rkyv::Archive>::Resolver,
    blocks: <alloc::vec::Vec<crate::ir::IRBlock<P>> as rkyv::Archive>::Resolver,
    pre_init: <alloc::vec::Vec<volar_ir_common::PreInitSegment> as rkyv::Archive>::Resolver,
}

#[cfg(feature = "rkyv")]
unsafe impl<P: Clone + rkyv::Archive> rkyv::Portable for ArchivedIRBlocks<P>
where
    <alloc::vec::Vec<volar_ir_common::OracleDecl> as rkyv::Archive>::Archived: rkyv::Portable,
    <alloc::vec::Vec<volar_ir_common::ActionDecl> as rkyv::Archive>::Archived: rkyv::Portable,
    <alloc::vec::Vec<volar_ir_common::RngDecl> as rkyv::Archive>::Archived: rkyv::Portable,
    <alloc::vec::Vec<crate::ir::IRBlock<P>> as rkyv::Archive>::Archived: rkyv::Portable,
    <alloc::vec::Vec<volar_ir_common::PreInitSegment> as rkyv::Archive>::Archived: rkyv::Portable,
{}

#[cfg(feature = "rkyv")]
impl<P: Clone + rkyv::Archive> rkyv::Archive for IRBlocks<P> {
    type Archived = ArchivedIRBlocks<P>;
    type Resolver = IRBlocksResolver<P>;

    fn resolve(&self, resolver: Self::Resolver, out: rkyv::Place<Self::Archived>) {
        let field_ptr = unsafe { ::core::ptr::addr_of_mut!((*out.ptr()).oracles) };
        let field_out = unsafe { rkyv::Place::from_field_unchecked(out, field_ptr) };
        rkyv::Archive::resolve(&self.oracles, resolver.oracles, field_out);
        let field_ptr = unsafe { ::core::ptr::addr_of_mut!((*out.ptr()).actions) };
        let field_out = unsafe { rkyv::Place::from_field_unchecked(out, field_ptr) };
        rkyv::Archive::resolve(&self.actions, resolver.actions, field_out);
        let field_ptr = unsafe { ::core::ptr::addr_of_mut!((*out.ptr()).rngs) };
        let field_out = unsafe { rkyv::Place::from_field_unchecked(out, field_ptr) };
        rkyv::Archive::resolve(&self.rngs, resolver.rngs, field_out);
        let field_ptr = unsafe { ::core::ptr::addr_of_mut!((*out.ptr()).blocks) };
        let field_out = unsafe { rkyv::Place::from_field_unchecked(out, field_ptr) };
        rkyv::Archive::resolve(&self.blocks, resolver.blocks, field_out);
        let field_ptr = unsafe { ::core::ptr::addr_of_mut!((*out.ptr()).pre_init) };
        let field_out = unsafe { rkyv::Place::from_field_unchecked(out, field_ptr) };
        rkyv::Archive::resolve(&self.pre_init, resolver.pre_init, field_out);
    }
}

#[cfg(feature = "rkyv")]
impl<P: Clone + rkyv::Archive, S: rkyv::rancor::Fallible + ?Sized> rkyv::Serialize<S> for IRBlocks<P>
where
    alloc::vec::Vec<volar_ir_common::OracleDecl>: rkyv::Serialize<S>,
    alloc::vec::Vec<volar_ir_common::ActionDecl>: rkyv::Serialize<S>,
    alloc::vec::Vec<volar_ir_common::RngDecl>: rkyv::Serialize<S>,
    alloc::vec::Vec<crate::ir::IRBlock<P>>: rkyv::Serialize<S>,
    alloc::vec::Vec<volar_ir_common::PreInitSegment>: rkyv::Serialize<S>,
{
    fn serialize(&self, serializer: &mut S) -> Result<Self::Resolver, S::Error> {
        Ok(IRBlocksResolver {
            oracles: rkyv::Serialize::serialize(&self.oracles, serializer)?,
            actions: rkyv::Serialize::serialize(&self.actions, serializer)?,
            rngs: rkyv::Serialize::serialize(&self.rngs, serializer)?,
            blocks: rkyv::Serialize::serialize(&self.blocks, serializer)?,
            pre_init: rkyv::Serialize::serialize(&self.pre_init, serializer)?,
        })
    }
}

#[cfg(feature = "rkyv")]
impl<P: Clone + rkyv::Archive, D: rkyv::rancor::Fallible + ?Sized> rkyv::Deserialize<IRBlocks<P>, D>
    for ArchivedIRBlocks<P>
where
    <alloc::vec::Vec<volar_ir_common::OracleDecl> as rkyv::Archive>::Archived: rkyv::Deserialize<alloc::vec::Vec<volar_ir_common::OracleDecl>, D>,
    <alloc::vec::Vec<volar_ir_common::ActionDecl> as rkyv::Archive>::Archived: rkyv::Deserialize<alloc::vec::Vec<volar_ir_common::ActionDecl>, D>,
    <alloc::vec::Vec<volar_ir_common::RngDecl> as rkyv::Archive>::Archived: rkyv::Deserialize<alloc::vec::Vec<volar_ir_common::RngDecl>, D>,
    <alloc::vec::Vec<crate::ir::IRBlock<P>> as rkyv::Archive>::Archived: rkyv::Deserialize<alloc::vec::Vec<crate::ir::IRBlock<P>>, D>,
    <alloc::vec::Vec<volar_ir_common::PreInitSegment> as rkyv::Archive>::Archived: rkyv::Deserialize<alloc::vec::Vec<volar_ir_common::PreInitSegment>, D>,
{
    fn deserialize(&self, deserializer: &mut D) -> Result<IRBlocks<P>, D::Error> {
        Ok(IRBlocks {
            oracles: rkyv::Deserialize::deserialize(&self.oracles, deserializer)?,
            actions: rkyv::Deserialize::deserialize(&self.actions, deserializer)?,
            rngs: rkyv::Deserialize::deserialize(&self.rngs, deserializer)?,
            blocks: rkyv::Deserialize::deserialize(&self.blocks, deserializer)?,
            pre_init: rkyv::Deserialize::deserialize(&self.pre_init, deserializer)?,
        })
    }
}

/// One typed Volar IR block with statements and a terminator.
#[derive(Clone, PartialEq, Eq, PartialOrd, Ord, Hash, Debug)]
pub struct IRBlock<P: Clone = ()> {
    pub params: alloc::vec::Vec<volar_ir_common::TypeId>,
    pub stmts: alloc::vec::Vec<volar_ir_common::Node<crate::ir::IRStmt, P>>,
    pub terminator: crate::ir::IRTerminator,
}

#[cfg(feature = "rkyv")]
#[derive(rkyv::bytecheck::CheckBytes)]
#[bytecheck(crate = rkyv::bytecheck)]
#[repr(C)]
pub struct ArchivedIRBlock<P: Clone + rkyv::Archive = ()> {
    pub params: <alloc::vec::Vec<volar_ir_common::TypeId> as rkyv::Archive>::Archived,
    pub stmts: <alloc::vec::Vec<volar_ir_common::Node<crate::ir::IRStmt, P>> as rkyv::Archive>::Archived,
    pub terminator: <crate::ir::IRTerminator as rkyv::Archive>::Archived,
}

#[cfg(feature = "rkyv")]
#[allow(dead_code)]
pub struct IRBlockResolver<P: Clone + rkyv::Archive = ()> {
    params: <alloc::vec::Vec<volar_ir_common::TypeId> as rkyv::Archive>::Resolver,
    stmts: <alloc::vec::Vec<volar_ir_common::Node<crate::ir::IRStmt, P>> as rkyv::Archive>::Resolver,
    terminator: <crate::ir::IRTerminator as rkyv::Archive>::Resolver,
}

#[cfg(feature = "rkyv")]
unsafe impl<P: Clone + rkyv::Archive> rkyv::Portable for ArchivedIRBlock<P>
where
    <alloc::vec::Vec<volar_ir_common::TypeId> as rkyv::Archive>::Archived: rkyv::Portable,
    <alloc::vec::Vec<volar_ir_common::Node<crate::ir::IRStmt, P>> as rkyv::Archive>::Archived: rkyv::Portable,
    <crate::ir::IRTerminator as rkyv::Archive>::Archived: rkyv::Portable,
{}

#[cfg(feature = "rkyv")]
impl<P: Clone + rkyv::Archive> rkyv::Archive for IRBlock<P> {
    type Archived = ArchivedIRBlock<P>;
    type Resolver = IRBlockResolver<P>;

    fn resolve(&self, resolver: Self::Resolver, out: rkyv::Place<Self::Archived>) {
        let field_ptr = unsafe { ::core::ptr::addr_of_mut!((*out.ptr()).params) };
        let field_out = unsafe { rkyv::Place::from_field_unchecked(out, field_ptr) };
        rkyv::Archive::resolve(&self.params, resolver.params, field_out);
        let field_ptr = unsafe { ::core::ptr::addr_of_mut!((*out.ptr()).stmts) };
        let field_out = unsafe { rkyv::Place::from_field_unchecked(out, field_ptr) };
        rkyv::Archive::resolve(&self.stmts, resolver.stmts, field_out);
        let field_ptr = unsafe { ::core::ptr::addr_of_mut!((*out.ptr()).terminator) };
        let field_out = unsafe { rkyv::Place::from_field_unchecked(out, field_ptr) };
        rkyv::Archive::resolve(&self.terminator, resolver.terminator, field_out);
    }
}

#[cfg(feature = "rkyv")]
impl<P: Clone + rkyv::Archive, S: rkyv::rancor::Fallible + ?Sized> rkyv::Serialize<S> for IRBlock<P>
where
    alloc::vec::Vec<volar_ir_common::TypeId>: rkyv::Serialize<S>,
    alloc::vec::Vec<volar_ir_common::Node<crate::ir::IRStmt, P>>: rkyv::Serialize<S>,
    crate::ir::IRTerminator: rkyv::Serialize<S>,
{
    fn serialize(&self, serializer: &mut S) -> Result<Self::Resolver, S::Error> {
        Ok(IRBlockResolver {
            params: rkyv::Serialize::serialize(&self.params, serializer)?,
            stmts: rkyv::Serialize::serialize(&self.stmts, serializer)?,
            terminator: rkyv::Serialize::serialize(&self.terminator, serializer)?,
        })
    }
}

#[cfg(feature = "rkyv")]
impl<P: Clone + rkyv::Archive, D: rkyv::rancor::Fallible + ?Sized> rkyv::Deserialize<IRBlock<P>, D>
    for ArchivedIRBlock<P>
where
    <alloc::vec::Vec<volar_ir_common::TypeId> as rkyv::Archive>::Archived: rkyv::Deserialize<alloc::vec::Vec<volar_ir_common::TypeId>, D>,
    <alloc::vec::Vec<volar_ir_common::Node<crate::ir::IRStmt, P>> as rkyv::Archive>::Archived: rkyv::Deserialize<alloc::vec::Vec<volar_ir_common::Node<crate::ir::IRStmt, P>>, D>,
    <crate::ir::IRTerminator as rkyv::Archive>::Archived: rkyv::Deserialize<crate::ir::IRTerminator, D>,
{
    fn deserialize(&self, deserializer: &mut D) -> Result<IRBlock<P>, D::Error> {
        Ok(IRBlock {
            params: rkyv::Deserialize::deserialize(&self.params, deserializer)?,
            stmts: rkyv::Deserialize::deserialize(&self.stmts, deserializer)?,
            terminator: rkyv::Deserialize::deserialize(&self.terminator, deserializer)?,
        })
    }
}

/// A Volar IR branch destination, its argument list, and optional reentry hint.
#[derive(Clone, PartialEq, Eq, PartialOrd, Ord, Hash, Debug)]
pub struct IRBranchTarget<Var = IRVarId> {
    pub dest: crate::ir::IRBlockTargetId<Var>,
    pub args: alloc::vec::Vec<Var>,
    pub reentry: core::option::Option<volar_ir_common::ReentryHint>,
}

#[cfg(feature = "rkyv")]
#[derive(rkyv::bytecheck::CheckBytes)]
#[bytecheck(crate = rkyv::bytecheck)]
#[repr(C)]
pub struct ArchivedIRBranchTarget<Var: rkyv::Archive = IRVarId> {
    pub dest: <crate::ir::IRBlockTargetId<Var> as rkyv::Archive>::Archived,
    pub args: <alloc::vec::Vec<Var> as rkyv::Archive>::Archived,
    pub reentry: <core::option::Option<volar_ir_common::ReentryHint> as rkyv::Archive>::Archived,
}

#[cfg(feature = "rkyv")]
#[allow(dead_code)]
pub struct IRBranchTargetResolver<Var: rkyv::Archive = IRVarId> {
    dest: <crate::ir::IRBlockTargetId<Var> as rkyv::Archive>::Resolver,
    args: <alloc::vec::Vec<Var> as rkyv::Archive>::Resolver,
    reentry: <core::option::Option<volar_ir_common::ReentryHint> as rkyv::Archive>::Resolver,
}

#[cfg(feature = "rkyv")]
unsafe impl<Var: rkyv::Archive> rkyv::Portable for ArchivedIRBranchTarget<Var>
where
    <crate::ir::IRBlockTargetId<Var> as rkyv::Archive>::Archived: rkyv::Portable,
    <alloc::vec::Vec<Var> as rkyv::Archive>::Archived: rkyv::Portable,
    <core::option::Option<volar_ir_common::ReentryHint> as rkyv::Archive>::Archived: rkyv::Portable,
{}

#[cfg(feature = "rkyv")]
impl<Var: rkyv::Archive> rkyv::Archive for IRBranchTarget<Var> {
    type Archived = ArchivedIRBranchTarget<Var>;
    type Resolver = IRBranchTargetResolver<Var>;

    fn resolve(&self, resolver: Self::Resolver, out: rkyv::Place<Self::Archived>) {
        let field_ptr = unsafe { ::core::ptr::addr_of_mut!((*out.ptr()).dest) };
        let field_out = unsafe { rkyv::Place::from_field_unchecked(out, field_ptr) };
        rkyv::Archive::resolve(&self.dest, resolver.dest, field_out);
        let field_ptr = unsafe { ::core::ptr::addr_of_mut!((*out.ptr()).args) };
        let field_out = unsafe { rkyv::Place::from_field_unchecked(out, field_ptr) };
        rkyv::Archive::resolve(&self.args, resolver.args, field_out);
        let field_ptr = unsafe { ::core::ptr::addr_of_mut!((*out.ptr()).reentry) };
        let field_out = unsafe { rkyv::Place::from_field_unchecked(out, field_ptr) };
        rkyv::Archive::resolve(&self.reentry, resolver.reentry, field_out);
    }
}

#[cfg(feature = "rkyv")]
impl<Var: rkyv::Archive, S: rkyv::rancor::Fallible + ?Sized> rkyv::Serialize<S> for IRBranchTarget<Var>
where
    crate::ir::IRBlockTargetId<Var>: rkyv::Serialize<S>,
    alloc::vec::Vec<Var>: rkyv::Serialize<S>,
    core::option::Option<volar_ir_common::ReentryHint>: rkyv::Serialize<S>,
{
    fn serialize(&self, serializer: &mut S) -> Result<Self::Resolver, S::Error> {
        Ok(IRBranchTargetResolver {
            dest: rkyv::Serialize::serialize(&self.dest, serializer)?,
            args: rkyv::Serialize::serialize(&self.args, serializer)?,
            reentry: rkyv::Serialize::serialize(&self.reentry, serializer)?,
        })
    }
}

#[cfg(feature = "rkyv")]
impl<Var: rkyv::Archive, D: rkyv::rancor::Fallible + ?Sized> rkyv::Deserialize<IRBranchTarget<Var>, D>
    for ArchivedIRBranchTarget<Var>
where
    <crate::ir::IRBlockTargetId<Var> as rkyv::Archive>::Archived: rkyv::Deserialize<crate::ir::IRBlockTargetId<Var>, D>,
    <alloc::vec::Vec<Var> as rkyv::Archive>::Archived: rkyv::Deserialize<alloc::vec::Vec<Var>, D>,
    <core::option::Option<volar_ir_common::ReentryHint> as rkyv::Archive>::Archived: rkyv::Deserialize<core::option::Option<volar_ir_common::ReentryHint>, D>,
{
    fn deserialize(&self, deserializer: &mut D) -> Result<IRBranchTarget<Var>, D::Error> {
        Ok(IRBranchTarget {
            dest: rkyv::Deserialize::deserialize(&self.dest, deserializer)?,
            args: rkyv::Deserialize::deserialize(&self.args, deserializer)?,
            reentry: rkyv::Deserialize::deserialize(&self.reentry, deserializer)?,
        })
    }
}
