// @generated by retrop-emit-volar — do not edit.
//! Golden vectors: retrop's decoder + semantics interpreter is the
//! ground truth. Each vector runs through both engines in this crate:
//! the concrete software interpreter and the Boolar circuit evaluated
//! with volar-fuzz's `eval_biir`.

use retro_cpus::bir::step_bir;
use retro_cpus::cpu::Machine;
use retro_cpus::table::State;

struct Golden {
    name: &'static str,
    ram: &'static [(u16, &'static [u8])],
    init: State,
    out: State,
    writes: &'static [(u16, u8)],
}

static GOLDEN: &[Golden] = &[
    Golden {
        name: "lda_zp",
        ram: &[(512, &[0xA5, 0x40, ]), (64, &[0x7F, ]), ],
        init: State { a: 0x11, x: 0x22, y: 0x33, s: 0xFD, pc: 0x0200, f: [false, false, false, false, false, false] },
        out: State { a: 0x7F, x: 0x22, y: 0x33, s: 0xFD, pc: 0x0202, f: [false, false, false, false, false, false] },
        writes: &[],
    },
    Golden {
        name: "lda_zpx",
        ram: &[(512, &[0xB5, 0x40, ]), (98, &[0x81, ]), ],
        init: State { a: 0x11, x: 0x22, y: 0x33, s: 0xFD, pc: 0x0200, f: [false, false, false, false, false, false] },
        out: State { a: 0x81, x: 0x22, y: 0x33, s: 0xFD, pc: 0x0202, f: [false, false, false, false, false, true] },
        writes: &[],
    },
    Golden {
        name: "lda_absy",
        ram: &[(512, &[0xB9, 0x00, 0x12, ]), (4659, &[0xFF, ]), ],
        init: State { a: 0x11, x: 0x22, y: 0x33, s: 0xFD, pc: 0x0200, f: [false, false, false, false, false, false] },
        out: State { a: 0xFF, x: 0x22, y: 0x33, s: 0xFD, pc: 0x0203, f: [false, false, false, false, false, true] },
        writes: &[],
    },
    Golden {
        name: "lda_indy",
        ram: &[(512, &[0xB1, 0x40, ]), (64, &[0x30, ]), (65, &[0x12, ]), (4707, &[0x5A, ]), ],
        init: State { a: 0x11, x: 0x22, y: 0x33, s: 0xFD, pc: 0x0200, f: [false, false, false, false, false, false] },
        out: State { a: 0x5A, x: 0x22, y: 0x33, s: 0xFD, pc: 0x0202, f: [false, false, false, false, false, false] },
        writes: &[],
    },
    Golden {
        name: "ldx_imm",
        ram: &[(512, &[0xA2, 0x99, ]), ],
        init: State { a: 0x11, x: 0x22, y: 0x33, s: 0xFD, pc: 0x0200, f: [false, false, false, false, false, false] },
        out: State { a: 0x11, x: 0x99, y: 0x33, s: 0xFD, pc: 0x0202, f: [false, false, false, false, false, true] },
        writes: &[],
    },
    Golden {
        name: "sta_absy",
        ram: &[(512, &[0x99, 0x00, 0xD0, ]), ],
        init: State { a: 0x11, x: 0x22, y: 0x33, s: 0xFD, pc: 0x0200, f: [false, false, false, false, false, false] },
        out: State { a: 0x11, x: 0x22, y: 0x33, s: 0xFD, pc: 0x0203, f: [false, false, false, false, false, false] },
        writes: &[(0xD033, 0x11), ],
    },
    Golden {
        name: "sta_indzp",
        ram: &[(512, &[0x81, 0x40, ]), (85, &[0x34, ]), (86, &[0x12, ]), (4660, &[0xAA, ]), ],
        init: State { a: 0x11, x: 0x22, y: 0x33, s: 0xFD, pc: 0x0200, f: [false, false, false, false, false, false] },
        out: State { a: 0x11, x: 0x22, y: 0x33, s: 0xFD, pc: 0x0202, f: [false, false, false, false, false, false] },
        writes: &[(0x0000, 0x11), ],
    },
    Golden {
        name: "stz_zpx",
        ram: &[(512, &[0x74, 0x20, ]), (66, &[0x77, ]), ],
        init: State { a: 0x11, x: 0x22, y: 0x33, s: 0xFD, pc: 0x0200, f: [false, false, false, false, false, false] },
        out: State { a: 0x11, x: 0x22, y: 0x33, s: 0xFD, pc: 0x0202, f: [false, false, false, false, false, false] },
        writes: &[(0x0042, 0x00), ],
    },
    Golden {
        name: "adc_carry",
        ram: &[(512, &[0x65, 0x40, ]), (64, &[0x80, ]), ],
        init: State { a: 0x80, x: 0x00, y: 0x00, s: 0xFD, pc: 0x0200, f: [true, false, false, false, false, false] },
        out: State { a: 0x00, x: 0x00, y: 0x00, s: 0xFD, pc: 0x0202, f: [true, true, false, false, true, false] },
        writes: &[],
    },
    Golden {
        name: "adc_overflow",
        ram: &[(512, &[0x65, 0x40, ]), (64, &[0x01, ]), ],
        init: State { a: 0x7F, x: 0x00, y: 0x00, s: 0xFD, pc: 0x0200, f: [false, false, false, false, false, false] },
        out: State { a: 0x80, x: 0x00, y: 0x00, s: 0xFD, pc: 0x0202, f: [false, false, false, false, true, true] },
        writes: &[],
    },
    Golden {
        name: "sbc_borrow",
        ram: &[(512, &[0xE5, 0x40, ]), (64, &[0x20, ]), ],
        init: State { a: 0x10, x: 0x00, y: 0x00, s: 0xFD, pc: 0x0200, f: [false, false, false, false, false, false] },
        out: State { a: 0xEF, x: 0x00, y: 0x00, s: 0xFD, pc: 0x0202, f: [false, false, false, false, false, true] },
        writes: &[],
    },
    Golden {
        name: "and_imm",
        ram: &[(512, &[0x29, 0x0F, ]), ],
        init: State { a: 0x11, x: 0x22, y: 0x33, s: 0xFD, pc: 0x0200, f: [false, false, false, false, false, false] },
        out: State { a: 0x01, x: 0x22, y: 0x33, s: 0xFD, pc: 0x0202, f: [false, false, false, false, false, false] },
        writes: &[],
    },
    Golden {
        name: "eor_zp",
        ram: &[(512, &[0x45, 0x40, ]), (64, &[0xFF, ]), ],
        init: State { a: 0x11, x: 0x22, y: 0x33, s: 0xFD, pc: 0x0200, f: [false, false, false, false, false, false] },
        out: State { a: 0xEE, x: 0x22, y: 0x33, s: 0xFD, pc: 0x0202, f: [false, false, false, false, false, true] },
        writes: &[],
    },
    Golden {
        name: "cmp_equal",
        ram: &[(512, &[0xC9, 0x11, ]), ],
        init: State { a: 0x11, x: 0x22, y: 0x33, s: 0xFD, pc: 0x0200, f: [false, false, false, false, false, false] },
        out: State { a: 0x11, x: 0x22, y: 0x33, s: 0xFD, pc: 0x0202, f: [false, false, false, false, false, true] },
        writes: &[],
    },
    Golden {
        name: "cpy_less",
        ram: &[(512, &[0xCC, 0x50, 0x00, ]), ],
        init: State { a: 0x11, x: 0x22, y: 0x33, s: 0xFD, pc: 0x0200, f: [false, false, false, false, false, false] },
        out: State { a: 0x11, x: 0x22, y: 0x33, s: 0xFD, pc: 0x0203, f: [true, false, false, false, false, false] },
        writes: &[],
    },
    Golden {
        name: "asl_zp",
        ram: &[(512, &[0x06, 0x40, ]), (64, &[0xC0, ]), ],
        init: State { a: 0x11, x: 0x22, y: 0x33, s: 0xFD, pc: 0x0200, f: [false, false, false, false, false, false] },
        out: State { a: 0x11, x: 0x22, y: 0x33, s: 0xFD, pc: 0x0202, f: [true, false, false, false, false, true] },
        writes: &[(0x0040, 0x80), ],
    },
    Golden {
        name: "ror_acc_c",
        ram: &[(512, &[0x6A, ]), ],
        init: State { a: 0x11, x: 0x00, y: 0x00, s: 0xFD, pc: 0x0200, f: [true, false, false, false, false, false] },
        out: State { a: 0x88, x: 0x00, y: 0x00, s: 0xFD, pc: 0x0201, f: [true, false, false, false, false, true] },
        writes: &[],
    },
    Golden {
        name: "rol_zp",
        ram: &[(512, &[0x26, 0x40, ]), (64, &[0x7F, ]), ],
        init: State { a: 0x11, x: 0x00, y: 0x00, s: 0xFD, pc: 0x0200, f: [false, false, false, false, false, false] },
        out: State { a: 0x11, x: 0x00, y: 0x00, s: 0xFD, pc: 0x0202, f: [false, false, false, false, false, true] },
        writes: &[(0x0040, 0xFE), ],
    },
    Golden {
        name: "inc_wrap",
        ram: &[(512, &[0xE6, 0x40, ]), (64, &[0xFF, ]), ],
        init: State { a: 0x11, x: 0x22, y: 0x33, s: 0xFD, pc: 0x0200, f: [false, false, false, false, false, false] },
        out: State { a: 0x11, x: 0x22, y: 0x33, s: 0xFD, pc: 0x0202, f: [false, true, false, false, false, false] },
        writes: &[(0x0040, 0x00), ],
    },
    Golden {
        name: "dex",
        ram: &[(512, &[0xCA, ]), ],
        init: State { a: 0x11, x: 0x22, y: 0x33, s: 0xFD, pc: 0x0200, f: [false, false, false, false, false, false] },
        out: State { a: 0x11, x: 0x20, y: 0x33, s: 0xFD, pc: 0x0201, f: [false, false, false, false, false, false] },
        writes: &[],
    },
    Golden {
        name: "ina",
        ram: &[(512, &[0x1A, ]), ],
        init: State { a: 0xFF, x: 0x00, y: 0x00, s: 0xFD, pc: 0x0200, f: [false, false, false, false, false, false] },
        out: State { a: 0x00, x: 0x00, y: 0x00, s: 0xFD, pc: 0x0201, f: [false, true, false, false, false, false] },
        writes: &[],
    },
    Golden {
        name: "bit_zp",
        ram: &[(512, &[0x24, 0x40, ]), (64, &[0xC5, ]), ],
        init: State { a: 0x11, x: 0x22, y: 0x33, s: 0xFD, pc: 0x0200, f: [false, false, false, false, false, false] },
        out: State { a: 0x11, x: 0x22, y: 0x33, s: 0xFD, pc: 0x0202, f: [false, false, false, false, true, true] },
        writes: &[],
    },
    Golden {
        name: "bit_imm",
        ram: &[(512, &[0x89, 0x11, ]), ],
        init: State { a: 0x11, x: 0x22, y: 0x33, s: 0xFD, pc: 0x0200, f: [false, false, false, false, false, false] },
        out: State { a: 0x11, x: 0x22, y: 0x33, s: 0xFD, pc: 0x0202, f: [false, false, false, false, false, false] },
        writes: &[],
    },
    Golden {
        name: "tsb_zp",
        ram: &[(512, &[0x04, 0x40, ]), (64, &[0x3C, ]), ],
        init: State { a: 0x11, x: 0x22, y: 0x33, s: 0xFD, pc: 0x0200, f: [false, false, false, false, false, false] },
        out: State { a: 0x11, x: 0x22, y: 0x33, s: 0xFD, pc: 0x0202, f: [false, false, false, false, false, false] },
        writes: &[(0x0040, 0x3D), ],
    },
    Golden {
        name: "trb_zp",
        ram: &[(512, &[0x14, 0x40, ]), (64, &[0x3F, ]), ],
        init: State { a: 0x11, x: 0x22, y: 0x33, s: 0xFD, pc: 0x0200, f: [false, false, false, false, false, false] },
        out: State { a: 0x11, x: 0x22, y: 0x33, s: 0xFD, pc: 0x0202, f: [false, false, false, false, false, false] },
        writes: &[(0x0040, 0x2E), ],
    },
    Golden {
        name: "rmb3",
        ram: &[(512, &[0x27, 0x40, ]), (64, &[0xF7, ]), ],
        init: State { a: 0x11, x: 0x22, y: 0x33, s: 0xFD, pc: 0x0200, f: [false, false, false, false, false, false] },
        out: State { a: 0x11, x: 0x22, y: 0x33, s: 0xFD, pc: 0x0202, f: [false, false, false, false, false, false] },
        writes: &[(0x0040, 0xF3), ],
    },
    Golden {
        name: "smb6",
        ram: &[(512, &[0xE7, 0x40, ]), (64, &[0x00, ]), ],
        init: State { a: 0x11, x: 0x22, y: 0x33, s: 0xFD, pc: 0x0200, f: [false, false, false, false, false, false] },
        out: State { a: 0x11, x: 0x22, y: 0x33, s: 0xFD, pc: 0x0202, f: [false, false, false, false, false, false] },
        writes: &[(0x0040, 0x40), ],
    },
    Golden {
        name: "beq_taken",
        ram: &[(512, &[0xF0, 0x08, ]), ],
        init: State { a: 0x00, x: 0x00, y: 0x00, s: 0xFD, pc: 0x0200, f: [false, true, false, false, false, false] },
        out: State { a: 0x00, x: 0x00, y: 0x00, s: 0xFD, pc: 0x020A, f: [false, true, false, false, false, false] },
        writes: &[],
    },
    Golden {
        name: "bne_not_taken",
        ram: &[(512, &[0xD0, 0x08, ]), ],
        init: State { a: 0x00, x: 0x00, y: 0x00, s: 0xFD, pc: 0x0200, f: [false, true, false, false, false, false] },
        out: State { a: 0x00, x: 0x00, y: 0x00, s: 0xFD, pc: 0x0202, f: [false, true, false, false, false, false] },
        writes: &[],
    },
    Golden {
        name: "bra_back",
        ram: &[(512, &[0x80, 0xFE, ]), ],
        init: State { a: 0x11, x: 0x22, y: 0x33, s: 0xFD, pc: 0x0200, f: [false, false, false, false, false, false] },
        out: State { a: 0x11, x: 0x22, y: 0x33, s: 0xFD, pc: 0x0200, f: [false, false, false, false, false, false] },
        writes: &[],
    },
    Golden {
        name: "bbs2_taken",
        ram: &[(512, &[0x6F, 0x40, 0x05, ]), (64, &[0x04, ]), ],
        init: State { a: 0x11, x: 0x22, y: 0x33, s: 0xFD, pc: 0x0200, f: [false, false, false, false, false, false] },
        out: State { a: 0x11, x: 0x22, y: 0x33, s: 0xFD, pc: 0x0208, f: [false, false, false, false, false, false] },
        writes: &[],
    },
    Golden {
        name: "bbr5_not_taken",
        ram: &[(512, &[0x5F, 0x40, 0x05, ]), (64, &[0x20, ]), ],
        init: State { a: 0x11, x: 0x22, y: 0x33, s: 0xFD, pc: 0x0200, f: [false, false, false, false, false, false] },
        out: State { a: 0x11, x: 0x22, y: 0x33, s: 0xFD, pc: 0x0203, f: [false, false, false, false, false, false] },
        writes: &[],
    },
    Golden {
        name: "sec_sei",
        ram: &[(512, &[0x38, ]), ],
        init: State { a: 0x11, x: 0x22, y: 0x33, s: 0xFD, pc: 0x0200, f: [false, false, false, false, false, false] },
        out: State { a: 0x11, x: 0x22, y: 0x33, s: 0xFD, pc: 0x0201, f: [true, false, false, false, false, false] },
        writes: &[],
    },
    Golden {
        name: "clv",
        ram: &[(512, &[0xB8, ]), ],
        init: State { a: 0x00, x: 0x00, y: 0x00, s: 0xFD, pc: 0x0200, f: [false, false, false, false, true, false] },
        out: State { a: 0x00, x: 0x00, y: 0x00, s: 0xFD, pc: 0x0201, f: [false, false, false, false, false, false] },
        writes: &[],
    },
    Golden {
        name: "pha",
        ram: &[(512, &[0x48, ]), ],
        init: State { a: 0x11, x: 0x22, y: 0x33, s: 0xFD, pc: 0x0200, f: [false, false, false, false, false, false] },
        out: State { a: 0x11, x: 0x22, y: 0x33, s: 0xFC, pc: 0x0201, f: [false, false, false, false, false, false] },
        writes: &[(0x01FD, 0x11), ],
    },
    Golden {
        name: "php",
        ram: &[(512, &[0x08, ]), ],
        init: State { a: 0x42, x: 0x00, y: 0x00, s: 0xFD, pc: 0x0200, f: [false, true, false, false, false, true] },
        out: State { a: 0x42, x: 0x00, y: 0x00, s: 0xFC, pc: 0x0201, f: [false, true, false, false, false, true] },
        writes: &[(0x01FD, 0x82), ],
    },
    Golden {
        name: "pla",
        ram: &[(512, &[0x68, ]), (508, &[0xE1, ]), ],
        init: State { a: 0x99, x: 0x00, y: 0x00, s: 0xFB, pc: 0x0200, f: [false, false, false, false, false, false] },
        out: State { a: 0xE1, x: 0x00, y: 0x00, s: 0xFC, pc: 0x0201, f: [false, false, false, false, false, true] },
        writes: &[],
    },
    Golden {
        name: "plz_zero",
        ram: &[(512, &[0x7A, ]), (508, &[0x00, ]), ],
        init: State { a: 0x11, x: 0xEE, y: 0x00, s: 0xFB, pc: 0x0200, f: [true, false, false, false, false, false] },
        out: State { a: 0x11, x: 0xEE, y: 0x00, s: 0xFC, pc: 0x0201, f: [true, true, false, false, false, false] },
        writes: &[],
    },
    Golden {
        name: "plx",
        ram: &[(512, &[0xFA, ]), (510, &[0x9C, ]), ],
        init: State { a: 0x11, x: 0x22, y: 0x33, s: 0xFD, pc: 0x0200, f: [false, false, false, false, false, false] },
        out: State { a: 0x11, x: 0x9C, y: 0x33, s: 0xFE, pc: 0x0201, f: [false, false, false, false, false, true] },
        writes: &[],
    },
    Golden {
        name: "jmp_ind",
        ram: &[(512, &[0x6C, 0xFC, 0x03, ]), (1020, &[0x44, ]), (1021, &[0xC0, ]), ],
        init: State { a: 0x11, x: 0x22, y: 0x33, s: 0xFD, pc: 0x0200, f: [false, false, false, false, false, false] },
        out: State { a: 0x11, x: 0x22, y: 0x33, s: 0xFD, pc: 0xC044, f: [false, false, false, false, false, false] },
        writes: &[],
    },
    Golden {
        name: "jmp_ipax",
        ram: &[(512, &[0x7C, 0x00, 0x30, ]), (12322, &[0x55, ]), (12323, &[0xA0, ]), ],
        init: State { a: 0x11, x: 0x22, y: 0x00, s: 0xFD, pc: 0x0200, f: [false, false, false, false, false, false] },
        out: State { a: 0x11, x: 0x22, y: 0x00, s: 0xFD, pc: 0xA055, f: [false, false, false, false, false, false] },
        writes: &[],
    },
    Golden {
        name: "jsr",
        ram: &[(512, &[0x20, 0x00, 0xC0, ]), ],
        init: State { a: 0x11, x: 0x22, y: 0x33, s: 0xFD, pc: 0x0200, f: [false, false, false, false, false, false] },
        out: State { a: 0x11, x: 0x22, y: 0x33, s: 0xFB, pc: 0xC000, f: [false, false, false, false, false, false] },
        writes: &[(0x01FC, 0x02), (0x01FD, 0x02), ],
    },
    Golden {
        name: "rts",
        ram: &[(512, &[0x60, ]), (508, &[0x07, ]), (509, &[0xC0, ]), ],
        init: State { a: 0x00, x: 0x00, y: 0x00, s: 0xFB, pc: 0x0200, f: [false, false, false, false, false, false] },
        out: State { a: 0x00, x: 0x00, y: 0x00, s: 0xFD, pc: 0xC008, f: [false, false, false, false, false, false] },
        writes: &[],
    },
    Golden {
        name: "rti",
        ram: &[(512, &[0x40, ]), (507, &[0x07, ]), (508, &[0x34, ]), (509, &[0x12, ]), ],
        init: State { a: 0x00, x: 0x00, y: 0x00, s: 0xFA, pc: 0x0200, f: [false, false, false, false, false, false] },
        out: State { a: 0x00, x: 0x00, y: 0x00, s: 0xFD, pc: 0x1234, f: [true, true, true, false, false, false] },
        writes: &[],
    },
    Golden {
        name: "brk",
        ram: &[(512, &[0x00, ]), (65534, &[0x34, ]), (65535, &[0x12, ]), ],
        init: State { a: 0x11, x: 0x22, y: 0x33, s: 0xFD, pc: 0x0200, f: [false, false, false, false, false, false] },
        out: State { a: 0x11, x: 0x22, y: 0x33, s: 0xFA, pc: 0x1234, f: [false, false, true, false, false, false] },
        writes: &[(0x01FC, 0x02), (0x01FD, 0x02), ],
    },
    Golden {
        name: "taysx",
        ram: &[(512, &[0xA8, 0xBA, ]), ],
        init: State { a: 0x11, x: 0x22, y: 0x33, s: 0xFD, pc: 0x0200, f: [false, false, false, false, false, false] },
        out: State { a: 0x11, x: 0x22, y: 0x11, s: 0xFD, pc: 0x0201, f: [false, false, false, false, false, false] },
        writes: &[],
    },
    Golden {
        name: "txa",
        ram: &[(512, &[0x8A, ]), ],
        init: State { a: 0x11, x: 0x22, y: 0x33, s: 0xFD, pc: 0x0200, f: [false, false, false, false, false, false] },
        out: State { a: 0x22, x: 0x22, y: 0x33, s: 0xFD, pc: 0x0201, f: [false, false, false, false, false, false] },
        writes: &[],
    },
    Golden {
        name: "invalid_02",
        ram: &[(512, &[0x02, 0xEA, ]), ],
        init: State { a: 0x11, x: 0x22, y: 0x33, s: 0xFD, pc: 0x0200, f: [false, false, false, false, false, false] },
        out: State { a: 0x11, x: 0x22, y: 0x33, s: 0xFD, pc: 0x0201, f: [false, false, false, false, false, false] },
        writes: &[],
    },
    Golden {
        name: "nop",
        ram: &[(512, &[0xEA, 0xEA, ]), ],
        init: State { a: 0x11, x: 0x22, y: 0x33, s: 0xFD, pc: 0x0200, f: [false, false, false, false, false, false] },
        out: State { a: 0x11, x: 0x22, y: 0x33, s: 0xFD, pc: 0x0201, f: [false, false, false, false, false, false] },
        writes: &[],
    },
];

fn load(m: &mut Machine, ram: &[(u16, &[u8])]) {
    for &(addr, bytes) in ram {
        m.ram[addr as usize..addr as usize + bytes.len()].copy_from_slice(bytes);
    }
}

fn check_state(which: &str, name: &str, got: &State, want: &State) {
    assert_eq!(got.a, want.a, "{which}/{name}: A");
    assert_eq!(got.x, want.x, "{which}/{name}: X");
    assert_eq!(got.y, want.y, "{which}/{name}: Y");
    assert_eq!(got.s, want.s, "{which}/{name}: S");
    assert_eq!(got.pc, want.pc, "{which}/{name}: PC");
    assert_eq!(got.f, want.f, "{which}/{name}: flags");
}

fn byte_before(g: &Golden, addr: u16) -> u8 {
    for &(start, bytes) in g.ram {
        if addr >= start && (addr as usize) < start as usize + bytes.len() {
            return bytes[(addr - start) as usize];
        }
    }
    0
}

#[test]
fn software_interpreter_matches_golden() {
    for g in GOLDEN {
        let mut m = Machine::new(g.init);
        load(&mut m, g.ram);
        m.step();
        check_state("sw", g.name, &m.state(), &g.out);
        for &(addr, want) in g.writes {
            assert_eq!(m.ram[addr as usize], want, "sw/{}: mem[{addr:04X}]", g.name);
        }
        // No unlisted cell may have changed.
        let listed = |a: u16| g.writes.iter().any(|&(wa, _)| wa == a);
        for a in 0..=0xFFFFu16 {
            assert!(
                listed(a) || m.ram[a as usize] == byte_before(g, a),
                "sw/{}: unexpected write at {a:04X}",
                g.name
            );
        }
    }
}
#[test]
fn boolar_circuit_matches_golden() {
    let bir = step_bir();
    // Pre-init storage segments from every vector's RAM image (union).
    for g in GOLDEN {
        let mut blocks = bir.clone();
        blocks.pre_init.clear();
        for &(addr, bytes) in g.ram {
            for (i, b) in bytes.iter().enumerate() {
                for bit in 0..8u64 {
                    blocks.pre_init.push(volar_ir::boolar::BIrPreInitSegment {
                        storage: retro_cpus::bir::RETRO_RAM,
                        lane: retro_cpus::bir::LANE_RAM,
                        offset: (addr as u64 + i as u64) + (bit << 16),
                        data: vec![(b >> bit) & 1 == 1],
                    });
                }
            }
        }
        let inputs = g.init.bits();
        let out = volar_fuzz::interpreter::biir::eval_biir(&blocks, &inputs)
            .unwrap_or_else(|| panic!("bir/{}: evaluation failed", g.name));
        let got = State::from_bits(&out);
        check_state("bir", g.name, &got, &g.out);
        // memory writes visible through re-evaluation of read-back? The
        // evaluator's storage map is internal; instead spot-check by
        // re-running eval and reading back via a second pass is unsupported,
        // so write verification happens in the software test above.
        let _ = g.writes;
    }
}
