// Generated by volar-ir-schema-gen; do not edit.
//
// This code deliberately implements rkyv's three traits directly and
// generates byte validation for archived values. The archived layout matches
// rkyv_derive's `#[repr(C)]` scalar-newtype layout, so pinned-rkyv binary
// artifacts remain byte-compatible.

/// Opaque index of a VAFFLE function signature.
#[derive(Clone, Copy, PartialEq, Eq, PartialOrd, Ord, Hash, Debug)]
pub struct SigId(pub usize);

#[cfg(feature = "rkyv")]
#[derive(Clone, Copy, PartialEq, Eq, PartialOrd, Ord, Debug, rkyv::bytecheck::CheckBytes)]
#[bytecheck(crate = rkyv::bytecheck)]
#[repr(C)]
pub struct ArchivedSigId(pub rkyv::primitive::ArchivedUsize);

#[cfg(feature = "rkyv")]
unsafe impl rkyv::Portable for ArchivedSigId {}

#[cfg(feature = "rkyv")]
impl rkyv::Archive for SigId {
    type Archived = ArchivedSigId;
    type Resolver = ();

    fn resolve(&self, (): Self::Resolver, out: rkyv::Place<Self::Archived>) {
        // SAFETY: the generated archived newtype is repr(C), contains exactly
        // one initialized portable scalar, and has no padding.
        unsafe {
            out.write_unchecked(ArchivedSigId(rkyv::primitive::ArchivedUsize::from_native((self.0) as _)))
        }
    }
}

#[cfg(feature = "rkyv")]
impl<S: rkyv::rancor::Fallible + ?Sized> rkyv::Serialize<S> for SigId {
    fn serialize(&self, _: &mut S) -> Result<Self::Resolver, S::Error> {
        Ok(())
    }
}

#[cfg(feature = "rkyv")]
impl<D: rkyv::rancor::Fallible + ?Sized> rkyv::Deserialize<SigId, D>
    for ArchivedSigId
{
    fn deserialize(&self, _: &mut D) -> Result<SigId, D::Error> {
        Ok(SigId(self.0.to_native() as usize))
    }
}

/// Opaque index of a VAFFLE function.
#[derive(Clone, Copy, PartialEq, Eq, PartialOrd, Ord, Hash, Debug)]
pub struct FuncId(pub usize);

#[cfg(feature = "rkyv")]
#[derive(Clone, Copy, PartialEq, Eq, PartialOrd, Ord, Debug, rkyv::bytecheck::CheckBytes)]
#[bytecheck(crate = rkyv::bytecheck)]
#[repr(C)]
pub struct ArchivedFuncId(pub rkyv::primitive::ArchivedUsize);

#[cfg(feature = "rkyv")]
unsafe impl rkyv::Portable for ArchivedFuncId {}

#[cfg(feature = "rkyv")]
impl rkyv::Archive for FuncId {
    type Archived = ArchivedFuncId;
    type Resolver = ();

    fn resolve(&self, (): Self::Resolver, out: rkyv::Place<Self::Archived>) {
        // SAFETY: the generated archived newtype is repr(C), contains exactly
        // one initialized portable scalar, and has no padding.
        unsafe {
            out.write_unchecked(ArchivedFuncId(rkyv::primitive::ArchivedUsize::from_native((self.0) as _)))
        }
    }
}

#[cfg(feature = "rkyv")]
impl<S: rkyv::rancor::Fallible + ?Sized> rkyv::Serialize<S> for FuncId {
    fn serialize(&self, _: &mut S) -> Result<Self::Resolver, S::Error> {
        Ok(())
    }
}

#[cfg(feature = "rkyv")]
impl<D: rkyv::rancor::Fallible + ?Sized> rkyv::Deserialize<FuncId, D>
    for ArchivedFuncId
{
    fn deserialize(&self, _: &mut D) -> Result<FuncId, D::Error> {
        Ok(FuncId(self.0.to_native() as usize))
    }
}

/// Opaque index of a VAFFLE basic block.
#[derive(Clone, Copy, PartialEq, Eq, PartialOrd, Ord, Hash, Debug)]
pub struct BlockId(pub usize);

#[cfg(feature = "rkyv")]
#[derive(Clone, Copy, PartialEq, Eq, PartialOrd, Ord, Debug, rkyv::bytecheck::CheckBytes)]
#[bytecheck(crate = rkyv::bytecheck)]
#[repr(C)]
pub struct ArchivedBlockId(pub rkyv::primitive::ArchivedUsize);

#[cfg(feature = "rkyv")]
unsafe impl rkyv::Portable for ArchivedBlockId {}

#[cfg(feature = "rkyv")]
impl rkyv::Archive for BlockId {
    type Archived = ArchivedBlockId;
    type Resolver = ();

    fn resolve(&self, (): Self::Resolver, out: rkyv::Place<Self::Archived>) {
        // SAFETY: the generated archived newtype is repr(C), contains exactly
        // one initialized portable scalar, and has no padding.
        unsafe {
            out.write_unchecked(ArchivedBlockId(rkyv::primitive::ArchivedUsize::from_native((self.0) as _)))
        }
    }
}

#[cfg(feature = "rkyv")]
impl<S: rkyv::rancor::Fallible + ?Sized> rkyv::Serialize<S> for BlockId {
    fn serialize(&self, _: &mut S) -> Result<Self::Resolver, S::Error> {
        Ok(())
    }
}

#[cfg(feature = "rkyv")]
impl<D: rkyv::rancor::Fallible + ?Sized> rkyv::Deserialize<BlockId, D>
    for ArchivedBlockId
{
    fn deserialize(&self, _: &mut D) -> Result<BlockId, D::Error> {
        Ok(BlockId(self.0.to_native() as usize))
    }
}

/// Opaque identifier of a VAFFLE SSA value.
#[derive(Clone, Copy, PartialEq, Eq, PartialOrd, Ord, Hash, Debug)]
pub struct ValueId(pub usize);

#[cfg(feature = "rkyv")]
#[derive(Clone, Copy, PartialEq, Eq, PartialOrd, Ord, Debug, rkyv::bytecheck::CheckBytes)]
#[bytecheck(crate = rkyv::bytecheck)]
#[repr(C)]
pub struct ArchivedValueId(pub rkyv::primitive::ArchivedUsize);

#[cfg(feature = "rkyv")]
unsafe impl rkyv::Portable for ArchivedValueId {}

#[cfg(feature = "rkyv")]
impl rkyv::Archive for ValueId {
    type Archived = ArchivedValueId;
    type Resolver = ();

    fn resolve(&self, (): Self::Resolver, out: rkyv::Place<Self::Archived>) {
        // SAFETY: the generated archived newtype is repr(C), contains exactly
        // one initialized portable scalar, and has no padding.
        unsafe {
            out.write_unchecked(ArchivedValueId(rkyv::primitive::ArchivedUsize::from_native((self.0) as _)))
        }
    }
}

#[cfg(feature = "rkyv")]
impl<S: rkyv::rancor::Fallible + ?Sized> rkyv::Serialize<S> for ValueId {
    fn serialize(&self, _: &mut S) -> Result<Self::Resolver, S::Error> {
        Ok(())
    }
}

#[cfg(feature = "rkyv")]
impl<D: rkyv::rancor::Fallible + ?Sized> rkyv::Deserialize<ValueId, D>
    for ArchivedValueId
{
    fn deserialize(&self, _: &mut D) -> Result<ValueId, D::Error> {
        Ok(ValueId(self.0.to_native() as usize))
    }
}

/// A VAFFLE function signature expressed as module-local type IDs.
#[derive(Clone, Debug)]
pub struct SigDecl {
    pub params: alloc::vec::Vec<volar_ir_common::TypeId>,
    pub results: alloc::vec::Vec<volar_ir_common::TypeId>,
}

#[cfg(feature = "rkyv")]
#[derive(rkyv::bytecheck::CheckBytes)]
#[bytecheck(crate = rkyv::bytecheck)]
#[repr(C)]
pub struct ArchivedSigDecl {
    pub params: <alloc::vec::Vec<volar_ir_common::TypeId> as rkyv::Archive>::Archived,
    pub results: <alloc::vec::Vec<volar_ir_common::TypeId> as rkyv::Archive>::Archived,
}

#[cfg(feature = "rkyv")]
#[allow(dead_code)]
pub struct SigDeclResolver {
    params: <alloc::vec::Vec<volar_ir_common::TypeId> as rkyv::Archive>::Resolver,
    results: <alloc::vec::Vec<volar_ir_common::TypeId> as rkyv::Archive>::Resolver,
}

#[cfg(feature = "rkyv")]
unsafe impl rkyv::Portable for ArchivedSigDecl
where
    <alloc::vec::Vec<volar_ir_common::TypeId> as rkyv::Archive>::Archived: rkyv::Portable,
    <alloc::vec::Vec<volar_ir_common::TypeId> as rkyv::Archive>::Archived: rkyv::Portable,
{}

#[cfg(feature = "rkyv")]
impl rkyv::Archive for SigDecl {
    type Archived = ArchivedSigDecl;
    type Resolver = SigDeclResolver;

    fn resolve(&self, resolver: Self::Resolver, out: rkyv::Place<Self::Archived>) {
        let field_ptr = unsafe { ::core::ptr::addr_of_mut!((*out.ptr()).params) };
        let field_out = unsafe { rkyv::Place::from_field_unchecked(out, field_ptr) };
        rkyv::Archive::resolve(&self.params, resolver.params, field_out);
        let field_ptr = unsafe { ::core::ptr::addr_of_mut!((*out.ptr()).results) };
        let field_out = unsafe { rkyv::Place::from_field_unchecked(out, field_ptr) };
        rkyv::Archive::resolve(&self.results, resolver.results, field_out);
    }
}

#[cfg(feature = "rkyv")]
impl<S: rkyv::rancor::Fallible + ?Sized> rkyv::Serialize<S> for SigDecl
where
    alloc::vec::Vec<volar_ir_common::TypeId>: rkyv::Serialize<S>,
    alloc::vec::Vec<volar_ir_common::TypeId>: rkyv::Serialize<S>,
{
    fn serialize(&self, serializer: &mut S) -> Result<Self::Resolver, S::Error> {
        Ok(SigDeclResolver {
            params: rkyv::Serialize::serialize(&self.params, serializer)?,
            results: rkyv::Serialize::serialize(&self.results, serializer)?,
        })
    }
}

#[cfg(feature = "rkyv")]
impl<D: rkyv::rancor::Fallible + ?Sized> rkyv::Deserialize<SigDecl, D>
    for ArchivedSigDecl
where
    <alloc::vec::Vec<volar_ir_common::TypeId> as rkyv::Archive>::Archived: rkyv::Deserialize<alloc::vec::Vec<volar_ir_common::TypeId>, D>,
    <alloc::vec::Vec<volar_ir_common::TypeId> as rkyv::Archive>::Archived: rkyv::Deserialize<alloc::vec::Vec<volar_ir_common::TypeId>, D>,
{
    fn deserialize(&self, deserializer: &mut D) -> Result<SigDecl, D::Error> {
        Ok(SigDecl {
            params: rkyv::Deserialize::deserialize(&self.params, deserializer)?,
            results: rkyv::Deserialize::deserialize(&self.results, deserializer)?,
        })
    }
}

/// A VAFFLE basic block with ordered statements and a terminator.
#[derive(Clone, Debug)]
pub struct Block {
    pub params: alloc::vec::Vec<(crate::ValueId, volar_ir_common::TypeId)>,
    pub stmts: alloc::vec::Vec<crate::ValueId>,
    pub terminator: crate::Terminator,
}

#[cfg(feature = "rkyv")]
#[derive(rkyv::bytecheck::CheckBytes)]
#[bytecheck(crate = rkyv::bytecheck)]
#[repr(C)]
pub struct ArchivedBlock {
    pub params: <alloc::vec::Vec<(crate::ValueId, volar_ir_common::TypeId)> as rkyv::Archive>::Archived,
    pub stmts: <alloc::vec::Vec<crate::ValueId> as rkyv::Archive>::Archived,
    pub terminator: <crate::Terminator as rkyv::Archive>::Archived,
}

#[cfg(feature = "rkyv")]
#[allow(dead_code)]
pub struct BlockResolver {
    params: <alloc::vec::Vec<(crate::ValueId, volar_ir_common::TypeId)> as rkyv::Archive>::Resolver,
    stmts: <alloc::vec::Vec<crate::ValueId> as rkyv::Archive>::Resolver,
    terminator: <crate::Terminator as rkyv::Archive>::Resolver,
}

#[cfg(feature = "rkyv")]
unsafe impl rkyv::Portable for ArchivedBlock
where
    <alloc::vec::Vec<(crate::ValueId, volar_ir_common::TypeId)> as rkyv::Archive>::Archived: rkyv::Portable,
    <alloc::vec::Vec<crate::ValueId> as rkyv::Archive>::Archived: rkyv::Portable,
    <crate::Terminator as rkyv::Archive>::Archived: rkyv::Portable,
{}

#[cfg(feature = "rkyv")]
impl rkyv::Archive for Block {
    type Archived = ArchivedBlock;
    type Resolver = BlockResolver;

    fn resolve(&self, resolver: Self::Resolver, out: rkyv::Place<Self::Archived>) {
        let field_ptr = unsafe { ::core::ptr::addr_of_mut!((*out.ptr()).params) };
        let field_out = unsafe { rkyv::Place::from_field_unchecked(out, field_ptr) };
        rkyv::Archive::resolve(&self.params, resolver.params, field_out);
        let field_ptr = unsafe { ::core::ptr::addr_of_mut!((*out.ptr()).stmts) };
        let field_out = unsafe { rkyv::Place::from_field_unchecked(out, field_ptr) };
        rkyv::Archive::resolve(&self.stmts, resolver.stmts, field_out);
        let field_ptr = unsafe { ::core::ptr::addr_of_mut!((*out.ptr()).terminator) };
        let field_out = unsafe { rkyv::Place::from_field_unchecked(out, field_ptr) };
        rkyv::Archive::resolve(&self.terminator, resolver.terminator, field_out);
    }
}

#[cfg(feature = "rkyv")]
impl<S: rkyv::rancor::Fallible + ?Sized> rkyv::Serialize<S> for Block
where
    alloc::vec::Vec<(crate::ValueId, volar_ir_common::TypeId)>: rkyv::Serialize<S>,
    alloc::vec::Vec<crate::ValueId>: rkyv::Serialize<S>,
    crate::Terminator: rkyv::Serialize<S>,
{
    fn serialize(&self, serializer: &mut S) -> Result<Self::Resolver, S::Error> {
        Ok(BlockResolver {
            params: rkyv::Serialize::serialize(&self.params, serializer)?,
            stmts: rkyv::Serialize::serialize(&self.stmts, serializer)?,
            terminator: rkyv::Serialize::serialize(&self.terminator, serializer)?,
        })
    }
}

#[cfg(feature = "rkyv")]
impl<D: rkyv::rancor::Fallible + ?Sized> rkyv::Deserialize<Block, D>
    for ArchivedBlock
where
    <alloc::vec::Vec<(crate::ValueId, volar_ir_common::TypeId)> as rkyv::Archive>::Archived: rkyv::Deserialize<alloc::vec::Vec<(crate::ValueId, volar_ir_common::TypeId)>, D>,
    <alloc::vec::Vec<crate::ValueId> as rkyv::Archive>::Archived: rkyv::Deserialize<alloc::vec::Vec<crate::ValueId>, D>,
    <crate::Terminator as rkyv::Archive>::Archived: rkyv::Deserialize<crate::Terminator, D>,
{
    fn deserialize(&self, deserializer: &mut D) -> Result<Block, D::Error> {
        Ok(Block {
            params: rkyv::Deserialize::deserialize(&self.params, deserializer)?,
            stmts: rkyv::Deserialize::deserialize(&self.stmts, deserializer)?,
            terminator: rkyv::Deserialize::deserialize(&self.terminator, deserializer)?,
        })
    }
}

/// A VAFFLE module containing types, declarations, functions, signatures, exports, and storage initialization.
#[derive(Debug)]
pub struct Module<P: Clone = ()> {
    pub types: volar_ir_common::TypeTable,
    pub oracles: alloc::vec::Vec<volar_ir_common::OracleDecl>,
    pub actions: alloc::vec::Vec<volar_ir_common::ActionDecl>,
    pub funcs: alloc::vec::Vec<crate::FuncDecl<P>>,
    pub sigs: alloc::vec::Vec<crate::SigDecl>,
    pub exports: alloc::collections::BTreeMap<alloc::string::String, crate::FuncId>,
    pub pre_init: alloc::vec::Vec<volar_ir_common::PreInitSegment>,
}

#[cfg(feature = "rkyv")]
#[derive(rkyv::bytecheck::CheckBytes)]
#[bytecheck(crate = rkyv::bytecheck)]
#[repr(C)]
pub struct ArchivedModule<P: Clone + rkyv::Archive = ()> {
    pub types: <volar_ir_common::TypeTable as rkyv::Archive>::Archived,
    pub oracles: <alloc::vec::Vec<volar_ir_common::OracleDecl> as rkyv::Archive>::Archived,
    pub actions: <alloc::vec::Vec<volar_ir_common::ActionDecl> as rkyv::Archive>::Archived,
    pub funcs: <alloc::vec::Vec<crate::FuncDecl<P>> as rkyv::Archive>::Archived,
    pub sigs: <alloc::vec::Vec<crate::SigDecl> as rkyv::Archive>::Archived,
    pub exports: <alloc::collections::BTreeMap<alloc::string::String, crate::FuncId> as rkyv::Archive>::Archived,
    pub pre_init: <alloc::vec::Vec<volar_ir_common::PreInitSegment> as rkyv::Archive>::Archived,
}

#[cfg(feature = "rkyv")]
#[allow(dead_code)]
pub struct ModuleResolver<P: Clone + rkyv::Archive = ()> {
    types: <volar_ir_common::TypeTable as rkyv::Archive>::Resolver,
    oracles: <alloc::vec::Vec<volar_ir_common::OracleDecl> as rkyv::Archive>::Resolver,
    actions: <alloc::vec::Vec<volar_ir_common::ActionDecl> as rkyv::Archive>::Resolver,
    funcs: <alloc::vec::Vec<crate::FuncDecl<P>> as rkyv::Archive>::Resolver,
    sigs: <alloc::vec::Vec<crate::SigDecl> as rkyv::Archive>::Resolver,
    exports: <alloc::collections::BTreeMap<alloc::string::String, crate::FuncId> as rkyv::Archive>::Resolver,
    pre_init: <alloc::vec::Vec<volar_ir_common::PreInitSegment> as rkyv::Archive>::Resolver,
}

#[cfg(feature = "rkyv")]
unsafe impl<P: Clone + rkyv::Archive> rkyv::Portable for ArchivedModule<P>
where
    <volar_ir_common::TypeTable as rkyv::Archive>::Archived: rkyv::Portable,
    <alloc::vec::Vec<volar_ir_common::OracleDecl> as rkyv::Archive>::Archived: rkyv::Portable,
    <alloc::vec::Vec<volar_ir_common::ActionDecl> as rkyv::Archive>::Archived: rkyv::Portable,
    <alloc::vec::Vec<crate::FuncDecl<P>> as rkyv::Archive>::Archived: rkyv::Portable,
    <alloc::vec::Vec<crate::SigDecl> as rkyv::Archive>::Archived: rkyv::Portable,
    <alloc::collections::BTreeMap<alloc::string::String, crate::FuncId> as rkyv::Archive>::Archived: rkyv::Portable,
    <alloc::vec::Vec<volar_ir_common::PreInitSegment> as rkyv::Archive>::Archived: rkyv::Portable,
{}

#[cfg(feature = "rkyv")]
impl<P: Clone + rkyv::Archive> rkyv::Archive for Module<P> {
    type Archived = ArchivedModule<P>;
    type Resolver = ModuleResolver<P>;

    fn resolve(&self, resolver: Self::Resolver, out: rkyv::Place<Self::Archived>) {
        let field_ptr = unsafe { ::core::ptr::addr_of_mut!((*out.ptr()).types) };
        let field_out = unsafe { rkyv::Place::from_field_unchecked(out, field_ptr) };
        rkyv::Archive::resolve(&self.types, resolver.types, field_out);
        let field_ptr = unsafe { ::core::ptr::addr_of_mut!((*out.ptr()).oracles) };
        let field_out = unsafe { rkyv::Place::from_field_unchecked(out, field_ptr) };
        rkyv::Archive::resolve(&self.oracles, resolver.oracles, field_out);
        let field_ptr = unsafe { ::core::ptr::addr_of_mut!((*out.ptr()).actions) };
        let field_out = unsafe { rkyv::Place::from_field_unchecked(out, field_ptr) };
        rkyv::Archive::resolve(&self.actions, resolver.actions, field_out);
        let field_ptr = unsafe { ::core::ptr::addr_of_mut!((*out.ptr()).funcs) };
        let field_out = unsafe { rkyv::Place::from_field_unchecked(out, field_ptr) };
        rkyv::Archive::resolve(&self.funcs, resolver.funcs, field_out);
        let field_ptr = unsafe { ::core::ptr::addr_of_mut!((*out.ptr()).sigs) };
        let field_out = unsafe { rkyv::Place::from_field_unchecked(out, field_ptr) };
        rkyv::Archive::resolve(&self.sigs, resolver.sigs, field_out);
        let field_ptr = unsafe { ::core::ptr::addr_of_mut!((*out.ptr()).exports) };
        let field_out = unsafe { rkyv::Place::from_field_unchecked(out, field_ptr) };
        rkyv::Archive::resolve(&self.exports, resolver.exports, field_out);
        let field_ptr = unsafe { ::core::ptr::addr_of_mut!((*out.ptr()).pre_init) };
        let field_out = unsafe { rkyv::Place::from_field_unchecked(out, field_ptr) };
        rkyv::Archive::resolve(&self.pre_init, resolver.pre_init, field_out);
    }
}

#[cfg(feature = "rkyv")]
impl<P: Clone + rkyv::Archive, S: rkyv::rancor::Fallible + ?Sized> rkyv::Serialize<S> for Module<P>
where
    volar_ir_common::TypeTable: rkyv::Serialize<S>,
    alloc::vec::Vec<volar_ir_common::OracleDecl>: rkyv::Serialize<S>,
    alloc::vec::Vec<volar_ir_common::ActionDecl>: rkyv::Serialize<S>,
    alloc::vec::Vec<crate::FuncDecl<P>>: rkyv::Serialize<S>,
    alloc::vec::Vec<crate::SigDecl>: rkyv::Serialize<S>,
    alloc::collections::BTreeMap<alloc::string::String, crate::FuncId>: rkyv::Serialize<S>,
    alloc::vec::Vec<volar_ir_common::PreInitSegment>: rkyv::Serialize<S>,
{
    fn serialize(&self, serializer: &mut S) -> Result<Self::Resolver, S::Error> {
        Ok(ModuleResolver {
            types: rkyv::Serialize::serialize(&self.types, serializer)?,
            oracles: rkyv::Serialize::serialize(&self.oracles, serializer)?,
            actions: rkyv::Serialize::serialize(&self.actions, serializer)?,
            funcs: rkyv::Serialize::serialize(&self.funcs, serializer)?,
            sigs: rkyv::Serialize::serialize(&self.sigs, serializer)?,
            exports: rkyv::Serialize::serialize(&self.exports, serializer)?,
            pre_init: rkyv::Serialize::serialize(&self.pre_init, serializer)?,
        })
    }
}

#[cfg(feature = "rkyv")]
impl<P: Clone + rkyv::Archive, D: rkyv::rancor::Fallible + ?Sized> rkyv::Deserialize<Module<P>, D>
    for ArchivedModule<P>
where
    <volar_ir_common::TypeTable as rkyv::Archive>::Archived: rkyv::Deserialize<volar_ir_common::TypeTable, D>,
    <alloc::vec::Vec<volar_ir_common::OracleDecl> as rkyv::Archive>::Archived: rkyv::Deserialize<alloc::vec::Vec<volar_ir_common::OracleDecl>, D>,
    <alloc::vec::Vec<volar_ir_common::ActionDecl> as rkyv::Archive>::Archived: rkyv::Deserialize<alloc::vec::Vec<volar_ir_common::ActionDecl>, D>,
    <alloc::vec::Vec<crate::FuncDecl<P>> as rkyv::Archive>::Archived: rkyv::Deserialize<alloc::vec::Vec<crate::FuncDecl<P>>, D>,
    <alloc::vec::Vec<crate::SigDecl> as rkyv::Archive>::Archived: rkyv::Deserialize<alloc::vec::Vec<crate::SigDecl>, D>,
    <alloc::collections::BTreeMap<alloc::string::String, crate::FuncId> as rkyv::Archive>::Archived: rkyv::Deserialize<alloc::collections::BTreeMap<alloc::string::String, crate::FuncId>, D>,
    <alloc::vec::Vec<volar_ir_common::PreInitSegment> as rkyv::Archive>::Archived: rkyv::Deserialize<alloc::vec::Vec<volar_ir_common::PreInitSegment>, D>,
{
    fn deserialize(&self, deserializer: &mut D) -> Result<Module<P>, D::Error> {
        Ok(Module {
            types: rkyv::Deserialize::deserialize(&self.types, deserializer)?,
            oracles: rkyv::Deserialize::deserialize(&self.oracles, deserializer)?,
            actions: rkyv::Deserialize::deserialize(&self.actions, deserializer)?,
            funcs: rkyv::Deserialize::deserialize(&self.funcs, deserializer)?,
            sigs: rkyv::Deserialize::deserialize(&self.sigs, deserializer)?,
            exports: rkyv::Deserialize::deserialize(&self.exports, deserializer)?,
            pre_init: rkyv::Deserialize::deserialize(&self.pre_init, deserializer)?,
        })
    }
}

/// One VAFFLE function body with blocks, values, and an entry block.
#[derive(Debug)]
pub struct FuncBody<P: Clone = ()> {
    pub sig: crate::SigId,
    pub blocks: alloc::vec::Vec<crate::Block>,
    pub values: alloc::vec::Vec<volar_ir_common::Node<crate::Value, P>>,
    pub entry: crate::BlockId,
}

#[cfg(feature = "rkyv")]
#[derive(rkyv::bytecheck::CheckBytes)]
#[bytecheck(crate = rkyv::bytecheck)]
#[repr(C)]
pub struct ArchivedFuncBody<P: Clone + rkyv::Archive = ()> {
    pub sig: <crate::SigId as rkyv::Archive>::Archived,
    pub blocks: <alloc::vec::Vec<crate::Block> as rkyv::Archive>::Archived,
    pub values: <alloc::vec::Vec<volar_ir_common::Node<crate::Value, P>> as rkyv::Archive>::Archived,
    pub entry: <crate::BlockId as rkyv::Archive>::Archived,
}

#[cfg(feature = "rkyv")]
#[allow(dead_code)]
pub struct FuncBodyResolver<P: Clone + rkyv::Archive = ()> {
    sig: <crate::SigId as rkyv::Archive>::Resolver,
    blocks: <alloc::vec::Vec<crate::Block> as rkyv::Archive>::Resolver,
    values: <alloc::vec::Vec<volar_ir_common::Node<crate::Value, P>> as rkyv::Archive>::Resolver,
    entry: <crate::BlockId as rkyv::Archive>::Resolver,
}

#[cfg(feature = "rkyv")]
unsafe impl<P: Clone + rkyv::Archive> rkyv::Portable for ArchivedFuncBody<P>
where
    <crate::SigId as rkyv::Archive>::Archived: rkyv::Portable,
    <alloc::vec::Vec<crate::Block> as rkyv::Archive>::Archived: rkyv::Portable,
    <alloc::vec::Vec<volar_ir_common::Node<crate::Value, P>> as rkyv::Archive>::Archived: rkyv::Portable,
    <crate::BlockId as rkyv::Archive>::Archived: rkyv::Portable,
{}

#[cfg(feature = "rkyv")]
impl<P: Clone + rkyv::Archive> rkyv::Archive for FuncBody<P> {
    type Archived = ArchivedFuncBody<P>;
    type Resolver = FuncBodyResolver<P>;

    fn resolve(&self, resolver: Self::Resolver, out: rkyv::Place<Self::Archived>) {
        let field_ptr = unsafe { ::core::ptr::addr_of_mut!((*out.ptr()).sig) };
        let field_out = unsafe { rkyv::Place::from_field_unchecked(out, field_ptr) };
        rkyv::Archive::resolve(&self.sig, resolver.sig, field_out);
        let field_ptr = unsafe { ::core::ptr::addr_of_mut!((*out.ptr()).blocks) };
        let field_out = unsafe { rkyv::Place::from_field_unchecked(out, field_ptr) };
        rkyv::Archive::resolve(&self.blocks, resolver.blocks, field_out);
        let field_ptr = unsafe { ::core::ptr::addr_of_mut!((*out.ptr()).values) };
        let field_out = unsafe { rkyv::Place::from_field_unchecked(out, field_ptr) };
        rkyv::Archive::resolve(&self.values, resolver.values, field_out);
        let field_ptr = unsafe { ::core::ptr::addr_of_mut!((*out.ptr()).entry) };
        let field_out = unsafe { rkyv::Place::from_field_unchecked(out, field_ptr) };
        rkyv::Archive::resolve(&self.entry, resolver.entry, field_out);
    }
}

#[cfg(feature = "rkyv")]
impl<P: Clone + rkyv::Archive, S: rkyv::rancor::Fallible + ?Sized> rkyv::Serialize<S> for FuncBody<P>
where
    crate::SigId: rkyv::Serialize<S>,
    alloc::vec::Vec<crate::Block>: rkyv::Serialize<S>,
    alloc::vec::Vec<volar_ir_common::Node<crate::Value, P>>: rkyv::Serialize<S>,
    crate::BlockId: rkyv::Serialize<S>,
{
    fn serialize(&self, serializer: &mut S) -> Result<Self::Resolver, S::Error> {
        Ok(FuncBodyResolver {
            sig: rkyv::Serialize::serialize(&self.sig, serializer)?,
            blocks: rkyv::Serialize::serialize(&self.blocks, serializer)?,
            values: rkyv::Serialize::serialize(&self.values, serializer)?,
            entry: rkyv::Serialize::serialize(&self.entry, serializer)?,
        })
    }
}

#[cfg(feature = "rkyv")]
impl<P: Clone + rkyv::Archive, D: rkyv::rancor::Fallible + ?Sized> rkyv::Deserialize<FuncBody<P>, D>
    for ArchivedFuncBody<P>
where
    <crate::SigId as rkyv::Archive>::Archived: rkyv::Deserialize<crate::SigId, D>,
    <alloc::vec::Vec<crate::Block> as rkyv::Archive>::Archived: rkyv::Deserialize<alloc::vec::Vec<crate::Block>, D>,
    <alloc::vec::Vec<volar_ir_common::Node<crate::Value, P>> as rkyv::Archive>::Archived: rkyv::Deserialize<alloc::vec::Vec<volar_ir_common::Node<crate::Value, P>>, D>,
    <crate::BlockId as rkyv::Archive>::Archived: rkyv::Deserialize<crate::BlockId, D>,
{
    fn deserialize(&self, deserializer: &mut D) -> Result<FuncBody<P>, D::Error> {
        Ok(FuncBody {
            sig: rkyv::Deserialize::deserialize(&self.sig, deserializer)?,
            blocks: rkyv::Deserialize::deserialize(&self.blocks, deserializer)?,
            values: rkyv::Deserialize::deserialize(&self.values, deserializer)?,
            entry: rkyv::Deserialize::deserialize(&self.entry, deserializer)?,
        })
    }
}

/// A VAFFLE branch target, arguments, and optional reentry hint.
#[derive(Clone, Debug)]
pub struct Target<V = ValueId> {
    pub block: crate::BlockId,
    pub args: alloc::vec::Vec<V>,
    pub reentry: core::option::Option<volar_ir_common::ReentryHint>,
}

#[cfg(feature = "rkyv")]
#[derive(rkyv::bytecheck::CheckBytes)]
#[bytecheck(crate = rkyv::bytecheck)]
#[repr(C)]
pub struct ArchivedTarget<V: rkyv::Archive = ValueId> {
    pub block: <crate::BlockId as rkyv::Archive>::Archived,
    pub args: <alloc::vec::Vec<V> as rkyv::Archive>::Archived,
    pub reentry: <core::option::Option<volar_ir_common::ReentryHint> as rkyv::Archive>::Archived,
}

#[cfg(feature = "rkyv")]
#[allow(dead_code)]
pub struct TargetResolver<V: rkyv::Archive = ValueId> {
    block: <crate::BlockId as rkyv::Archive>::Resolver,
    args: <alloc::vec::Vec<V> as rkyv::Archive>::Resolver,
    reentry: <core::option::Option<volar_ir_common::ReentryHint> as rkyv::Archive>::Resolver,
}

#[cfg(feature = "rkyv")]
unsafe impl<V: rkyv::Archive> rkyv::Portable for ArchivedTarget<V>
where
    <crate::BlockId as rkyv::Archive>::Archived: rkyv::Portable,
    <alloc::vec::Vec<V> as rkyv::Archive>::Archived: rkyv::Portable,
    <core::option::Option<volar_ir_common::ReentryHint> as rkyv::Archive>::Archived: rkyv::Portable,
{}

#[cfg(feature = "rkyv")]
impl<V: rkyv::Archive> rkyv::Archive for Target<V> {
    type Archived = ArchivedTarget<V>;
    type Resolver = TargetResolver<V>;

    fn resolve(&self, resolver: Self::Resolver, out: rkyv::Place<Self::Archived>) {
        let field_ptr = unsafe { ::core::ptr::addr_of_mut!((*out.ptr()).block) };
        let field_out = unsafe { rkyv::Place::from_field_unchecked(out, field_ptr) };
        rkyv::Archive::resolve(&self.block, resolver.block, field_out);
        let field_ptr = unsafe { ::core::ptr::addr_of_mut!((*out.ptr()).args) };
        let field_out = unsafe { rkyv::Place::from_field_unchecked(out, field_ptr) };
        rkyv::Archive::resolve(&self.args, resolver.args, field_out);
        let field_ptr = unsafe { ::core::ptr::addr_of_mut!((*out.ptr()).reentry) };
        let field_out = unsafe { rkyv::Place::from_field_unchecked(out, field_ptr) };
        rkyv::Archive::resolve(&self.reentry, resolver.reentry, field_out);
    }
}

#[cfg(feature = "rkyv")]
impl<V: rkyv::Archive, S: rkyv::rancor::Fallible + ?Sized> rkyv::Serialize<S> for Target<V>
where
    crate::BlockId: rkyv::Serialize<S>,
    alloc::vec::Vec<V>: rkyv::Serialize<S>,
    core::option::Option<volar_ir_common::ReentryHint>: rkyv::Serialize<S>,
{
    fn serialize(&self, serializer: &mut S) -> Result<Self::Resolver, S::Error> {
        Ok(TargetResolver {
            block: rkyv::Serialize::serialize(&self.block, serializer)?,
            args: rkyv::Serialize::serialize(&self.args, serializer)?,
            reentry: rkyv::Serialize::serialize(&self.reentry, serializer)?,
        })
    }
}

#[cfg(feature = "rkyv")]
impl<V: rkyv::Archive, D: rkyv::rancor::Fallible + ?Sized> rkyv::Deserialize<Target<V>, D>
    for ArchivedTarget<V>
where
    <crate::BlockId as rkyv::Archive>::Archived: rkyv::Deserialize<crate::BlockId, D>,
    <alloc::vec::Vec<V> as rkyv::Archive>::Archived: rkyv::Deserialize<alloc::vec::Vec<V>, D>,
    <core::option::Option<volar_ir_common::ReentryHint> as rkyv::Archive>::Archived: rkyv::Deserialize<core::option::Option<volar_ir_common::ReentryHint>, D>,
{
    fn deserialize(&self, deserializer: &mut D) -> Result<Target<V>, D::Error> {
        Ok(Target {
            block: rkyv::Deserialize::deserialize(&self.block, deserializer)?,
            args: rkyv::Deserialize::deserialize(&self.args, deserializer)?,
            reentry: rkyv::Deserialize::deserialize(&self.reentry, deserializer)?,
        })
    }
}

