[package]
name = "vaffle"
version = "0.1.0"
edition = "2024"
license.workspace = true
description.workspace = true
repository.workspace = true

[features]
log-trace = ["dep:log"]
rkyv = ["dep:rkyv", "volar-ir-common/rkyv"]

[dependencies]
log = { version = "0.4", optional = true }
volar-ir-common.workspace = true
rkyv = { workspace = true, optional = true }
