// Generated by volar-ir-schema-gen; do not edit.
//
// This code deliberately implements rkyv's three traits directly and
// generates byte validation for archived values. The archived layout matches
// rkyv_derive's `#[repr(C)]` scalar-newtype layout, so pinned-rkyv binary
// artifacts remain byte-compatible.

/// Root metadata for a Boolar circuit whose statement body is loaded in semantic ranges.
#[derive(Clone, Debug, Eq, PartialEq)]
pub struct ChunkedBCircuit {
    pub version: u32,
    pub params: u32,
    pub pre_init: alloc::vec::Vec<crate::boolar::BIrPreInitSegment>,
    pub outputs: alloc::vec::Vec<crate::ir::IRVarId>,
    pub statement_chunks: alloc::vec::Vec<crate::lazy::BStmtChunkRef>,
    pub wire_schedule: crate::lazy::WireSchedule,
}

#[cfg(feature = "rkyv")]
#[derive(rkyv::bytecheck::CheckBytes)]
#[bytecheck(crate = rkyv::bytecheck)]
#[repr(C)]
pub struct ArchivedChunkedBCircuit {
    pub version: <u32 as rkyv::Archive>::Archived,
    pub params: <u32 as rkyv::Archive>::Archived,
    pub pre_init: <alloc::vec::Vec<crate::boolar::BIrPreInitSegment> as rkyv::Archive>::Archived,
    pub outputs: <alloc::vec::Vec<crate::ir::IRVarId> as rkyv::Archive>::Archived,
    pub statement_chunks: <alloc::vec::Vec<crate::lazy::BStmtChunkRef> as rkyv::Archive>::Archived,
    pub wire_schedule: <crate::lazy::WireSchedule as rkyv::Archive>::Archived,
}

#[cfg(feature = "rkyv")]
#[allow(dead_code)]
pub struct ChunkedBCircuitResolver {
    version: <u32 as rkyv::Archive>::Resolver,
    params: <u32 as rkyv::Archive>::Resolver,
    pre_init: <alloc::vec::Vec<crate::boolar::BIrPreInitSegment> as rkyv::Archive>::Resolver,
    outputs: <alloc::vec::Vec<crate::ir::IRVarId> as rkyv::Archive>::Resolver,
    statement_chunks: <alloc::vec::Vec<crate::lazy::BStmtChunkRef> as rkyv::Archive>::Resolver,
    wire_schedule: <crate::lazy::WireSchedule as rkyv::Archive>::Resolver,
}

#[cfg(feature = "rkyv")]
unsafe impl rkyv::Portable for ArchivedChunkedBCircuit
where
    <u32 as rkyv::Archive>::Archived: rkyv::Portable,
    <u32 as rkyv::Archive>::Archived: rkyv::Portable,
    <alloc::vec::Vec<crate::boolar::BIrPreInitSegment> as rkyv::Archive>::Archived: rkyv::Portable,
    <alloc::vec::Vec<crate::ir::IRVarId> as rkyv::Archive>::Archived: rkyv::Portable,
    <alloc::vec::Vec<crate::lazy::BStmtChunkRef> as rkyv::Archive>::Archived: rkyv::Portable,
    <crate::lazy::WireSchedule as rkyv::Archive>::Archived: rkyv::Portable,
{}

#[cfg(feature = "rkyv")]
impl rkyv::Archive for ChunkedBCircuit {
    type Archived = ArchivedChunkedBCircuit;
    type Resolver = ChunkedBCircuitResolver;

    fn resolve(&self, resolver: Self::Resolver, out: rkyv::Place<Self::Archived>) {
        let field_ptr = unsafe { ::core::ptr::addr_of_mut!((*out.ptr()).version) };
        let field_out = unsafe { rkyv::Place::from_field_unchecked(out, field_ptr) };
        rkyv::Archive::resolve(&self.version, resolver.version, field_out);
        let field_ptr = unsafe { ::core::ptr::addr_of_mut!((*out.ptr()).params) };
        let field_out = unsafe { rkyv::Place::from_field_unchecked(out, field_ptr) };
        rkyv::Archive::resolve(&self.params, resolver.params, field_out);
        let field_ptr = unsafe { ::core::ptr::addr_of_mut!((*out.ptr()).pre_init) };
        let field_out = unsafe { rkyv::Place::from_field_unchecked(out, field_ptr) };
        rkyv::Archive::resolve(&self.pre_init, resolver.pre_init, field_out);
        let field_ptr = unsafe { ::core::ptr::addr_of_mut!((*out.ptr()).outputs) };
        let field_out = unsafe { rkyv::Place::from_field_unchecked(out, field_ptr) };
        rkyv::Archive::resolve(&self.outputs, resolver.outputs, field_out);
        let field_ptr = unsafe { ::core::ptr::addr_of_mut!((*out.ptr()).statement_chunks) };
        let field_out = unsafe { rkyv::Place::from_field_unchecked(out, field_ptr) };
        rkyv::Archive::resolve(&self.statement_chunks, resolver.statement_chunks, field_out);
        let field_ptr = unsafe { ::core::ptr::addr_of_mut!((*out.ptr()).wire_schedule) };
        let field_out = unsafe { rkyv::Place::from_field_unchecked(out, field_ptr) };
        rkyv::Archive::resolve(&self.wire_schedule, resolver.wire_schedule, field_out);
    }
}

#[cfg(feature = "rkyv")]
impl<S: rkyv::rancor::Fallible + ?Sized> rkyv::Serialize<S> for ChunkedBCircuit
where
    u32: rkyv::Serialize<S>,
    u32: rkyv::Serialize<S>,
    alloc::vec::Vec<crate::boolar::BIrPreInitSegment>: rkyv::Serialize<S>,
    alloc::vec::Vec<crate::ir::IRVarId>: rkyv::Serialize<S>,
    alloc::vec::Vec<crate::lazy::BStmtChunkRef>: rkyv::Serialize<S>,
    crate::lazy::WireSchedule: rkyv::Serialize<S>,
{
    fn serialize(&self, serializer: &mut S) -> Result<Self::Resolver, S::Error> {
        Ok(ChunkedBCircuitResolver {
            version: rkyv::Serialize::serialize(&self.version, serializer)?,
            params: rkyv::Serialize::serialize(&self.params, serializer)?,
            pre_init: rkyv::Serialize::serialize(&self.pre_init, serializer)?,
            outputs: rkyv::Serialize::serialize(&self.outputs, serializer)?,
            statement_chunks: rkyv::Serialize::serialize(&self.statement_chunks, serializer)?,
            wire_schedule: rkyv::Serialize::serialize(&self.wire_schedule, serializer)?,
        })
    }
}

#[cfg(feature = "rkyv")]
impl<D: rkyv::rancor::Fallible + ?Sized> rkyv::Deserialize<ChunkedBCircuit, D>
    for ArchivedChunkedBCircuit
where
    <u32 as rkyv::Archive>::Archived: rkyv::Deserialize<u32, D>,
    <u32 as rkyv::Archive>::Archived: rkyv::Deserialize<u32, D>,
    <alloc::vec::Vec<crate::boolar::BIrPreInitSegment> as rkyv::Archive>::Archived: rkyv::Deserialize<alloc::vec::Vec<crate::boolar::BIrPreInitSegment>, D>,
    <alloc::vec::Vec<crate::ir::IRVarId> as rkyv::Archive>::Archived: rkyv::Deserialize<alloc::vec::Vec<crate::ir::IRVarId>, D>,
    <alloc::vec::Vec<crate::lazy::BStmtChunkRef> as rkyv::Archive>::Archived: rkyv::Deserialize<alloc::vec::Vec<crate::lazy::BStmtChunkRef>, D>,
    <crate::lazy::WireSchedule as rkyv::Archive>::Archived: rkyv::Deserialize<crate::lazy::WireSchedule, D>,
{
    fn deserialize(&self, deserializer: &mut D) -> Result<ChunkedBCircuit, D::Error> {
        Ok(ChunkedBCircuit {
            version: rkyv::Deserialize::deserialize(&self.version, deserializer)?,
            params: rkyv::Deserialize::deserialize(&self.params, deserializer)?,
            pre_init: rkyv::Deserialize::deserialize(&self.pre_init, deserializer)?,
            outputs: rkyv::Deserialize::deserialize(&self.outputs, deserializer)?,
            statement_chunks: rkyv::Deserialize::deserialize(&self.statement_chunks, deserializer)?,
            wire_schedule: rkyv::Deserialize::deserialize(&self.wire_schedule, deserializer)?,
        })
    }
}

/// A content reference plus the semantic statement range it contains.
#[derive(Clone, Debug, Eq, PartialEq)]
pub struct BStmtChunkRef {
    pub chunk: lazy_repo::ChunkRef,
    pub first: u32,
    pub statements: u32,
}

#[cfg(feature = "rkyv")]
#[derive(rkyv::bytecheck::CheckBytes)]
#[bytecheck(crate = rkyv::bytecheck)]
#[repr(C)]
pub struct ArchivedBStmtChunkRef {
    pub chunk: <lazy_repo::ChunkRef as rkyv::Archive>::Archived,
    pub first: <u32 as rkyv::Archive>::Archived,
    pub statements: <u32 as rkyv::Archive>::Archived,
}

#[cfg(feature = "rkyv")]
#[allow(dead_code)]
pub struct BStmtChunkRefResolver {
    chunk: <lazy_repo::ChunkRef as rkyv::Archive>::Resolver,
    first: <u32 as rkyv::Archive>::Resolver,
    statements: <u32 as rkyv::Archive>::Resolver,
}

#[cfg(feature = "rkyv")]
unsafe impl rkyv::Portable for ArchivedBStmtChunkRef
where
    <lazy_repo::ChunkRef as rkyv::Archive>::Archived: rkyv::Portable,
    <u32 as rkyv::Archive>::Archived: rkyv::Portable,
    <u32 as rkyv::Archive>::Archived: rkyv::Portable,
{}

#[cfg(feature = "rkyv")]
impl rkyv::Archive for BStmtChunkRef {
    type Archived = ArchivedBStmtChunkRef;
    type Resolver = BStmtChunkRefResolver;

    fn resolve(&self, resolver: Self::Resolver, out: rkyv::Place<Self::Archived>) {
        let field_ptr = unsafe { ::core::ptr::addr_of_mut!((*out.ptr()).chunk) };
        let field_out = unsafe { rkyv::Place::from_field_unchecked(out, field_ptr) };
        rkyv::Archive::resolve(&self.chunk, resolver.chunk, field_out);
        let field_ptr = unsafe { ::core::ptr::addr_of_mut!((*out.ptr()).first) };
        let field_out = unsafe { rkyv::Place::from_field_unchecked(out, field_ptr) };
        rkyv::Archive::resolve(&self.first, resolver.first, field_out);
        let field_ptr = unsafe { ::core::ptr::addr_of_mut!((*out.ptr()).statements) };
        let field_out = unsafe { rkyv::Place::from_field_unchecked(out, field_ptr) };
        rkyv::Archive::resolve(&self.statements, resolver.statements, field_out);
    }
}

#[cfg(feature = "rkyv")]
impl<S: rkyv::rancor::Fallible + ?Sized> rkyv::Serialize<S> for BStmtChunkRef
where
    lazy_repo::ChunkRef: rkyv::Serialize<S>,
    u32: rkyv::Serialize<S>,
    u32: rkyv::Serialize<S>,
{
    fn serialize(&self, serializer: &mut S) -> Result<Self::Resolver, S::Error> {
        Ok(BStmtChunkRefResolver {
            chunk: rkyv::Serialize::serialize(&self.chunk, serializer)?,
            first: rkyv::Serialize::serialize(&self.first, serializer)?,
            statements: rkyv::Serialize::serialize(&self.statements, serializer)?,
        })
    }
}

#[cfg(feature = "rkyv")]
impl<D: rkyv::rancor::Fallible + ?Sized> rkyv::Deserialize<BStmtChunkRef, D>
    for ArchivedBStmtChunkRef
where
    <lazy_repo::ChunkRef as rkyv::Archive>::Archived: rkyv::Deserialize<lazy_repo::ChunkRef, D>,
    <u32 as rkyv::Archive>::Archived: rkyv::Deserialize<u32, D>,
    <u32 as rkyv::Archive>::Archived: rkyv::Deserialize<u32, D>,
{
    fn deserialize(&self, deserializer: &mut D) -> Result<BStmtChunkRef, D::Error> {
        Ok(BStmtChunkRef {
            chunk: rkyv::Deserialize::deserialize(&self.chunk, deserializer)?,
            first: rkyv::Deserialize::deserialize(&self.first, deserializer)?,
            statements: rkyv::Deserialize::deserialize(&self.statements, deserializer)?,
        })
    }
}

/// The decoded payload of one content-addressed Boolar statement chunk.
#[derive(Clone, Debug, Eq, PartialEq)]
pub struct BStmtChunk<P: Clone> {
    pub first: u32,
    pub stmts: alloc::vec::Vec<volar_ir_common::Node<crate::boolar::BIrStmt, P>>,
}

#[cfg(feature = "rkyv")]
#[derive(rkyv::bytecheck::CheckBytes)]
#[bytecheck(crate = rkyv::bytecheck)]
#[repr(C)]
pub struct ArchivedBStmtChunk<P: Clone + rkyv::Archive> {
    pub first: <u32 as rkyv::Archive>::Archived,
    pub stmts: <alloc::vec::Vec<volar_ir_common::Node<crate::boolar::BIrStmt, P>> as rkyv::Archive>::Archived,
}

#[cfg(feature = "rkyv")]
#[allow(dead_code)]
pub struct BStmtChunkResolver<P: Clone + rkyv::Archive> {
    first: <u32 as rkyv::Archive>::Resolver,
    stmts: <alloc::vec::Vec<volar_ir_common::Node<crate::boolar::BIrStmt, P>> as rkyv::Archive>::Resolver,
}

#[cfg(feature = "rkyv")]
unsafe impl<P: Clone + rkyv::Archive> rkyv::Portable for ArchivedBStmtChunk<P>
where
    <u32 as rkyv::Archive>::Archived: rkyv::Portable,
    <alloc::vec::Vec<volar_ir_common::Node<crate::boolar::BIrStmt, P>> as rkyv::Archive>::Archived: rkyv::Portable,
{}

#[cfg(feature = "rkyv")]
impl<P: Clone + rkyv::Archive> rkyv::Archive for BStmtChunk<P> {
    type Archived = ArchivedBStmtChunk<P>;
    type Resolver = BStmtChunkResolver<P>;

    fn resolve(&self, resolver: Self::Resolver, out: rkyv::Place<Self::Archived>) {
        let field_ptr = unsafe { ::core::ptr::addr_of_mut!((*out.ptr()).first) };
        let field_out = unsafe { rkyv::Place::from_field_unchecked(out, field_ptr) };
        rkyv::Archive::resolve(&self.first, resolver.first, field_out);
        let field_ptr = unsafe { ::core::ptr::addr_of_mut!((*out.ptr()).stmts) };
        let field_out = unsafe { rkyv::Place::from_field_unchecked(out, field_ptr) };
        rkyv::Archive::resolve(&self.stmts, resolver.stmts, field_out);
    }
}

#[cfg(feature = "rkyv")]
impl<P: Clone + rkyv::Archive, S: rkyv::rancor::Fallible + ?Sized> rkyv::Serialize<S> for BStmtChunk<P>
where
    u32: rkyv::Serialize<S>,
    alloc::vec::Vec<volar_ir_common::Node<crate::boolar::BIrStmt, P>>: rkyv::Serialize<S>,
{
    fn serialize(&self, serializer: &mut S) -> Result<Self::Resolver, S::Error> {
        Ok(BStmtChunkResolver {
            first: rkyv::Serialize::serialize(&self.first, serializer)?,
            stmts: rkyv::Serialize::serialize(&self.stmts, serializer)?,
        })
    }
}

#[cfg(feature = "rkyv")]
impl<P: Clone + rkyv::Archive, D: rkyv::rancor::Fallible + ?Sized> rkyv::Deserialize<BStmtChunk<P>, D>
    for ArchivedBStmtChunk<P>
where
    <u32 as rkyv::Archive>::Archived: rkyv::Deserialize<u32, D>,
    <alloc::vec::Vec<volar_ir_common::Node<crate::boolar::BIrStmt, P>> as rkyv::Archive>::Archived: rkyv::Deserialize<alloc::vec::Vec<volar_ir_common::Node<crate::boolar::BIrStmt, P>>, D>,
{
    fn deserialize(&self, deserializer: &mut D) -> Result<BStmtChunk<P>, D::Error> {
        Ok(BStmtChunk {
            first: rkyv::Deserialize::deserialize(&self.first, deserializer)?,
            stmts: rkyv::Deserialize::deserialize(&self.stmts, deserializer)?,
        })
    }
}

/// Build-time wire liveness data consumed by bounded lazy runners.
#[derive(Clone, PartialEq, Eq, PartialOrd, Ord, Hash, Debug)]
pub struct WireSchedule {
    pub resident_wires: u32,
    pub temporary_wires: u32,
    pub last_use: alloc::vec::Vec<u32>,
    pub release_at: alloc::vec::Vec<alloc::vec::Vec<u32>>,
}

#[cfg(feature = "rkyv")]
#[derive(rkyv::bytecheck::CheckBytes)]
#[bytecheck(crate = rkyv::bytecheck)]
#[repr(C)]
pub struct ArchivedWireSchedule {
    pub resident_wires: <u32 as rkyv::Archive>::Archived,
    pub temporary_wires: <u32 as rkyv::Archive>::Archived,
    pub last_use: <alloc::vec::Vec<u32> as rkyv::Archive>::Archived,
    pub release_at: <alloc::vec::Vec<alloc::vec::Vec<u32>> as rkyv::Archive>::Archived,
}

#[cfg(feature = "rkyv")]
#[allow(dead_code)]
pub struct WireScheduleResolver {
    resident_wires: <u32 as rkyv::Archive>::Resolver,
    temporary_wires: <u32 as rkyv::Archive>::Resolver,
    last_use: <alloc::vec::Vec<u32> as rkyv::Archive>::Resolver,
    release_at: <alloc::vec::Vec<alloc::vec::Vec<u32>> as rkyv::Archive>::Resolver,
}

#[cfg(feature = "rkyv")]
unsafe impl rkyv::Portable for ArchivedWireSchedule
where
    <u32 as rkyv::Archive>::Archived: rkyv::Portable,
    <u32 as rkyv::Archive>::Archived: rkyv::Portable,
    <alloc::vec::Vec<u32> as rkyv::Archive>::Archived: rkyv::Portable,
    <alloc::vec::Vec<alloc::vec::Vec<u32>> as rkyv::Archive>::Archived: rkyv::Portable,
{}

#[cfg(feature = "rkyv")]
impl rkyv::Archive for WireSchedule {
    type Archived = ArchivedWireSchedule;
    type Resolver = WireScheduleResolver;

    fn resolve(&self, resolver: Self::Resolver, out: rkyv::Place<Self::Archived>) {
        let field_ptr = unsafe { ::core::ptr::addr_of_mut!((*out.ptr()).resident_wires) };
        let field_out = unsafe { rkyv::Place::from_field_unchecked(out, field_ptr) };
        rkyv::Archive::resolve(&self.resident_wires, resolver.resident_wires, field_out);
        let field_ptr = unsafe { ::core::ptr::addr_of_mut!((*out.ptr()).temporary_wires) };
        let field_out = unsafe { rkyv::Place::from_field_unchecked(out, field_ptr) };
        rkyv::Archive::resolve(&self.temporary_wires, resolver.temporary_wires, field_out);
        let field_ptr = unsafe { ::core::ptr::addr_of_mut!((*out.ptr()).last_use) };
        let field_out = unsafe { rkyv::Place::from_field_unchecked(out, field_ptr) };
        rkyv::Archive::resolve(&self.last_use, resolver.last_use, field_out);
        let field_ptr = unsafe { ::core::ptr::addr_of_mut!((*out.ptr()).release_at) };
        let field_out = unsafe { rkyv::Place::from_field_unchecked(out, field_ptr) };
        rkyv::Archive::resolve(&self.release_at, resolver.release_at, field_out);
    }
}

#[cfg(feature = "rkyv")]
impl<S: rkyv::rancor::Fallible + ?Sized> rkyv::Serialize<S> for WireSchedule
where
    u32: rkyv::Serialize<S>,
    u32: rkyv::Serialize<S>,
    alloc::vec::Vec<u32>: rkyv::Serialize<S>,
    alloc::vec::Vec<alloc::vec::Vec<u32>>: rkyv::Serialize<S>,
{
    fn serialize(&self, serializer: &mut S) -> Result<Self::Resolver, S::Error> {
        Ok(WireScheduleResolver {
            resident_wires: rkyv::Serialize::serialize(&self.resident_wires, serializer)?,
            temporary_wires: rkyv::Serialize::serialize(&self.temporary_wires, serializer)?,
            last_use: rkyv::Serialize::serialize(&self.last_use, serializer)?,
            release_at: rkyv::Serialize::serialize(&self.release_at, serializer)?,
        })
    }
}

#[cfg(feature = "rkyv")]
impl<D: rkyv::rancor::Fallible + ?Sized> rkyv::Deserialize<WireSchedule, D>
    for ArchivedWireSchedule
where
    <u32 as rkyv::Archive>::Archived: rkyv::Deserialize<u32, D>,
    <u32 as rkyv::Archive>::Archived: rkyv::Deserialize<u32, D>,
    <alloc::vec::Vec<u32> as rkyv::Archive>::Archived: rkyv::Deserialize<alloc::vec::Vec<u32>, D>,
    <alloc::vec::Vec<alloc::vec::Vec<u32>> as rkyv::Archive>::Archived: rkyv::Deserialize<alloc::vec::Vec<alloc::vec::Vec<u32>>, D>,
{
    fn deserialize(&self, deserializer: &mut D) -> Result<WireSchedule, D::Error> {
        Ok(WireSchedule {
            resident_wires: rkyv::Deserialize::deserialize(&self.resident_wires, deserializer)?,
            temporary_wires: rkyv::Deserialize::deserialize(&self.temporary_wires, deserializer)?,
            last_use: rkyv::Deserialize::deserialize(&self.last_use, deserializer)?,
            release_at: rkyv::Deserialize::deserialize(&self.release_at, deserializer)?,
        })
    }
}

