// Generated by volar-ir-schema-gen; do not edit.
//
// This code deliberately implements rkyv's three traits directly and
// generates byte validation for archived values. The archived layout matches
// rkyv_derive's `#[repr(C)]` scalar-newtype layout, so pinned-rkyv binary
// artifacts remain byte-compatible.

/// Opaque identifier naming which actor, party, or role a value belongs to.
#[derive(Clone, Copy, PartialEq, Eq, PartialOrd, Ord, Hash, Debug)]
pub struct SideId(pub u32);

#[cfg(feature = "rkyv")]
#[derive(Clone, Copy, PartialEq, Eq, PartialOrd, Ord, Debug, rkyv::bytecheck::CheckBytes)]
#[bytecheck(crate = rkyv::bytecheck)]
#[repr(C)]
pub struct ArchivedSideId(pub rkyv::primitive::ArchivedU32);

#[cfg(feature = "rkyv")]
unsafe impl rkyv::Portable for ArchivedSideId {}

#[cfg(feature = "rkyv")]
impl rkyv::Archive for SideId {
    type Archived = ArchivedSideId;
    type Resolver = ();

    fn resolve(&self, (): Self::Resolver, out: rkyv::Place<Self::Archived>) {
        // SAFETY: the generated archived newtype is repr(C), contains exactly
        // one initialized portable scalar, and has no padding.
        unsafe {
            out.write_unchecked(ArchivedSideId(rkyv::primitive::ArchivedU32::from_native(self.0)))
        }
    }
}

#[cfg(feature = "rkyv")]
impl<S: rkyv::rancor::Fallible + ?Sized> rkyv::Serialize<S> for SideId {
    fn serialize(&self, _: &mut S) -> Result<Self::Resolver, S::Error> {
        Ok(())
    }
}

#[cfg(feature = "rkyv")]
impl<D: rkyv::rancor::Fallible + ?Sized> rkyv::Deserialize<SideId, D>
    for ArchivedSideId
{
    fn deserialize(&self, _: &mut D) -> Result<SideId, D::Error> {
        Ok(SideId(self.0.to_native()))
    }
}

