//! Straight-line TypeScript source generation for Summon.

use std::fmt::Write as _;

use volar_ir::boolar::{BIrBlocks, BIrStmt};
use volar_ir::ir::IRVarId;

use crate::{InteropError, validate_bool_circuit};

/// Emit a reusable Summon-compatible Boolean helper function.
///
/// The generated function accepts one flat Boolean input array and returns the
/// ordered Boolar outputs. It is static straight-line source: circuit wires are
/// fixed identifiers, never dynamically indexed by signal values.
pub fn emit_summon_source<P: Clone>(blocks: &BIrBlocks<P>) -> Result<String, InteropError> {
    let circuit = validate_bool_circuit(blocks)?;
    let mut source = String::new();
    source.push_str("/** generated by volar-circuit-interop */\n");
    source.push_str("export default function evalCircuit(input: boolean[]): boolean[] {\n");
    writeln!(
        &mut source,
        "  if (input.length !== {}) throw new Error(\"input length\");",
        circuit.params()
    )
    .expect("writing to String cannot fail");
    source.push('\n');

    for (index, node) in circuit.stmts().iter().enumerate() {
        let id = circuit.params() as usize + index;
        let expression = match &node.kind {
            BIrStmt::Zero => "false".to_string(),
            BIrStmt::One => "true".to_string(),
            BIrStmt::And(a, b) => binary_expr(*a, *b, circuit.params(), "&&"),
            BIrStmt::Or(a, b) => binary_expr(*a, *b, circuit.params(), "||"),
            BIrStmt::Xor(a, b) => binary_expr(*a, *b, circuit.params(), "!=="),
            BIrStmt::Not(value) => format!("!{}", value_expr(*value, circuit.params())),
            _ => return Err(InteropError::UnsupportedStatement { index }),
        };
        writeln!(&mut source, "  const w{id} = {expression};")
            .expect("writing to String cannot fail");
    }

    source.push_str("  return [");
    for (index, output) in circuit.outputs().iter().enumerate() {
        if index != 0 {
            source.push_str(", ");
        }
        source.push_str(&value_expr(*output, circuit.params()));
    }
    source.push_str("];\n}\n");
    Ok(source)
}

fn binary_expr(a: IRVarId, b: IRVarId, params: u32, operator: &str) -> String {
    format!(
        "{} {operator} {}",
        value_expr(a, params),
        value_expr(b, params)
    )
}

fn value_expr(value: IRVarId, params: u32) -> String {
    if value.0 < params {
        format!("input[{}]", value.0)
    } else {
        format!("w{}", value.0)
    }
}
