// @reliability: normal
// @ai: assisted

use volar_circuit_source::{
    EmitError, EmitOptions, NamedBoolCircuit, NamedBoolOp, SourceFile, SourcePackage,
};
use volar_ir::ir::IRVarId;

use crate::ident::sanitize_ident;

pub fn emit_bool(
    circuit: &NamedBoolCircuit,
    opt: &EmitOptions,
) -> Result<SourcePackage, EmitError> {
    if circuit.has_externals() {
        return Err(EmitError::unsupported(
            "oracle/action/rng",
            "v1 Noir backend rejects externals",
        ));
    }
    if circuit.has_storage() {
        return Err(EmitError::unsupported(
            "storage",
            "run StorageToMux or use the POD2 backend",
        ));
    }

    let pkg = sanitize_ident(&opt.package_name)?;
    let fn_name = sanitize_ident(&opt.circuit_name)?;
    let n_in = circuit.inputs.len();
    let n_out = circuit.outputs.len();

    let mut body = String::new();
    for (i, inp) in circuit.inputs.iter().enumerate() {
        if inp.name != format!("in{i}") {
            body.push_str(&format!("    let {} = w[{i}];\n", inp.name));
        }
    }

    for stmt in &circuit.stmts {
        if !stmt.dst.bind {
            continue;
        }
        let expr = render_op(circuit, &stmt.op)?;
        body.push_str(&format!("    let {} = {expr};\n", stmt.dst.name));
    }

    let outs: Result<Vec<String>, EmitError> = circuit
        .outputs
        .iter()
        .map(|id| render_ref(circuit, *id))
        .collect();
    let outs = outs?;
    let ret = match n_out {
        0 => String::from("    ()\n"),
        1 => format!("    [{}]\n", outs[0]),
        _ => format!("    [{}]\n", outs.join(", ")),
    };
    body.push_str(&ret);

    let (ret_ty, param) = match (n_in, n_out) {
        (0, 0) => (String::from("()"), String::new()),
        (0, n) => (format!("[bool; {n}]"), String::new()),
        (n, 0) => (String::from("()"), format!("w: [bool; {n}]")),
        (n, m) => (format!("[bool; {m}]"), format!("w: [bool; {n}]")),
    };

    let lib = format!(
        "// Generated by volar-noir-backend. Library only — the embedder owns `main`\n\
         // and public/private witness flags.\n\
         pub fn {fn_name}({param}) -> {ret_ty} {{\n\
         {body}}}\n"
    );

    let embed = embed_snippet(&pkg, &fn_name, n_in, n_out);
    Ok(package_files(&pkg, &lib, &embed))
}

fn embed_snippet(pkg: &str, fn_name: &str, n_in: usize, n_out: usize) -> String {
    format!(
        "// Embedder-owned entry. `pub` on the return is the verifier-visible ABI.\n\
         use {pkg}::{fn_name};\n\
         fn main(w: [bool; {n_in}]) -> pub [bool; {n_out}] {{\n\
             {fn_name}(w)\n\
         }}\n"
    )
}

fn render_ref(circuit: &NamedBoolCircuit, id: IRVarId) -> Result<String, EmitError> {
    let wire = circuit.wire(id).ok_or(EmitError::UnknownVar { id })?;
    if circuit.is_input(id) {
        let idx = id.0 as usize;
        if wire.name == format!("in{idx}") {
            return Ok(format!("w[{idx}]"));
        }
        return Ok(wire.name.clone());
    }
    if wire.bind {
        return Ok(wire.name.clone());
    }
    let stmt = circuit
        .stmt_defining(id)
        .ok_or(EmitError::UnknownVar { id })?;
    render_op(circuit, &stmt.op)
}

fn render_op(circuit: &NamedBoolCircuit, op: &NamedBoolOp) -> Result<String, EmitError> {
    match op {
        NamedBoolOp::Zero => Ok(String::from("false")),
        NamedBoolOp::One => Ok(String::from("true")),
        NamedBoolOp::And(a, b) => Ok(format!(
            "({}) & ({})",
            render_ref(circuit, *a)?,
            render_ref(circuit, *b)?
        )),
        NamedBoolOp::Or(a, b) => Ok(format!(
            "({}) | ({})",
            render_ref(circuit, *a)?,
            render_ref(circuit, *b)?
        )),
        NamedBoolOp::Xor(a, b) => Ok(format!(
            "({}) != ({})",
            render_ref(circuit, *a)?,
            render_ref(circuit, *b)?
        )),
        NamedBoolOp::Not(a) => Ok(format!("!({})", render_ref(circuit, *a)?)),
        NamedBoolOp::StorageRead { .. } | NamedBoolOp::StorageWrite { .. } => {
            Err(EmitError::unsupported(
                "storage",
                "run StorageToMux or use the POD2 backend",
            ))
        }
        NamedBoolOp::External { kind, name } => Err(EmitError::unsupported(
            format!("{kind:?} `{name}`"),
            "v1 Noir backend rejects externals",
        )),
    }
}

pub fn package_files_for_lib(pkg: &str, lib: &str, embed: &str) -> SourcePackage {
    package_files(pkg, lib, embed)
}

fn package_files(pkg: &str, lib: &str, embed: &str) -> SourcePackage {
    SourcePackage::new(vec![
        SourceFile::new(
            "Nargo.toml",
            format!(
                "[package]\n\
                 name = \"{pkg}\"\n\
                 type = \"lib\"\n\
                 compiler_version = \">=1.0.0-beta.26\"\n"
            ),
        ),
        SourceFile::new("src/lib.nr", lib.to_string()),
        SourceFile::new("examples/embed.nr", embed.to_string()),
    ])
}
