// @reliability: normal
// @ai: assisted
//! Noir (`type = "lib"`) backend for [`volar_circuit_source`].
//!
//! Boolean circuits become `pub fn` over `[bool; N]`. Volar IR circuits
//! become typed `pub fn`s. Storage, oracles, actions, and RNG fail closed.

use volar_circuit_source::{
    BackendCaps, CircuitSourceBackend, EmitError, EmitOptions, NamedBoolCircuit, NamedVolarCircuit,
    SourcePackage,
};

mod bool;
mod ident;
mod volar;

pub use ident::sanitize_ident;

/// Noir library emitter.
#[derive(Clone, Copy, Debug, Default)]
pub struct NoirBackend;

impl CircuitSourceBackend for NoirBackend {
    fn caps() -> BackendCaps {
        BackendCaps {
            bool_circuit: true,
            volar_ir: true,
            merkle_storage: false,
            array_storage: false,
        }
    }

    fn sanitize_ident(name: &str) -> Result<String, EmitError> {
        ident::sanitize_ident(name)
    }

    fn emit_bool(
        &self,
        circuit: &NamedBoolCircuit,
        opt: &EmitOptions,
    ) -> Result<SourcePackage, EmitError> {
        bool::emit_bool(circuit, opt)
    }

    fn emit_volar(
        &self,
        circuit: &NamedVolarCircuit,
        opt: &EmitOptions,
    ) -> Result<SourcePackage, EmitError> {
        volar::emit_volar(circuit, opt)
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use volar_circuit_source::{emit_bool_circuit, emit_volar_circuit, EmitOptions, WireNames};
    use volar_ir::boolar::BIrStmt;
    use volar_ir::circuit::{BCircuit, VCircuit};
    use volar_ir::ir::{IRStmt, IRVarId};
    use volar_ir_common::{Constant, PolyCoeffs, TypeTable};

    fn and_xor_circuit() -> BCircuit<()> {
        let mut c = BCircuit::new(3);
        c.push_stmt(BIrStmt::And(IRVarId(0), IRVarId(1)), ());
        c.push_stmt(BIrStmt::Xor(IRVarId(2), IRVarId(2)), ());
        c.outputs = vec![IRVarId(2), IRVarId(3)];
        c
    }

    #[test]
    fn bool_lib_not_main() {
        let pkg = emit_bool_circuit(&and_xor_circuit(), &NoirBackend, &EmitOptions::default())
            .unwrap();
        let toml = pkg.file_text("Nargo.toml").unwrap();
        assert!(toml.contains("type = \"lib\""));
        assert!(!toml.contains("type = \"bin\""));
        let lib = pkg.file_text("src/lib.nr").unwrap();
        assert!(lib.contains("pub fn eval_circuit"));
        assert!(!lib.contains("fn main"));
        assert!(pkg.file_text("examples/embed.nr").unwrap().contains("fn main"));
    }

    #[test]
    fn golden_and_lib() {
        let mut c = BCircuit::new(2);
        c.push_stmt(BIrStmt::And(IRVarId(0), IRVarId(1)), ());
        c.outputs = vec![IRVarId(2)];
        let pkg = emit_bool_circuit(&c, &NoirBackend, &EmitOptions::default()).unwrap();
        assert_eq!(
            pkg.file_text("src/lib.nr").unwrap(),
            concat!(
                "// Generated by volar-noir-backend. Library only — the embedder owns `main`\n",
                "// and public/private witness flags.\n",
                "pub fn eval_circuit(w: [bool; 2]) -> [bool; 1] {\n",
                "    [(w[0]) & (w[1])]\n",
                "}\n",
            )
        );
    }

    #[test]
    fn named_wire_appears() {
        let mut opt = EmitOptions::default();
        opt.wires = WireNames::new();
        opt.wires.name_var(IRVarId(2), "carry");
        let pkg = emit_bool_circuit(&and_xor_circuit(), &NoirBackend, &opt).unwrap();
        let lib = pkg.file_text("src/lib.nr").unwrap();
        assert!(lib.contains("let carry ="));
        assert!(lib.contains("!="));
    }

    #[test]
    fn storage_is_rejected() {
        let mut c = BCircuit::new(1);
        c.push_stmt(
            BIrStmt::StorageRead {
                storage: volar_ir_common::StorageId(0),
                lane: volar_ir::boolar::LaneId(0),
                addr: vec![IRVarId(0)],
            },
            (),
        );
        c.outputs = vec![IRVarId(1)];
        let err = emit_bool_circuit(&c, &NoirBackend, &EmitOptions::default()).unwrap_err();
        assert!(matches!(err, EmitError::Unsupported { .. }));
    }

    #[test]
    fn volar_bit_poly_and() {
        let mut types = TypeTable::new();
        let bit = types.bit();
        let mut c = VCircuit::new(vec![bit, bit]);
        let mut coeffs = PolyCoeffs::new();
        coeffs.insert(vec![IRVarId(0), IRVarId(1)], 1u8);
        c.push_stmt(
            IRStmt::Poly {
                ty: bit,
                coeffs,
                constant: Constant { hi: 0, lo: 0 },
            },
            (),
        );
        c.outputs = vec![IRVarId(2)];
        let pkg = emit_volar_circuit(&c, &types, &NoirBackend, &EmitOptions::default()).unwrap();
        let lib = pkg.file_text("src/lib.nr").unwrap();
        assert!(lib.contains("pub fn eval_circuit"));
        assert!(lib.contains("bool"));
        assert!(lib.contains('&') || lib.contains("!="));
    }
}
