// @reliability: normal
// @ai: assisted

use volar_circuit_source::{
    ir_type_bit_width, type_is_bit, EmitError, EmitOptions, NamedVolarCircuit, NamedVolarOp,
    SourcePackage,
};
use volar_ir::ir::{IRTypes, IRVarId};
use volar_ir_common::{Constant, IrType, PolyCoeffs, Type, TypeId};

use crate::bool::package_files_for_lib;
use crate::ident::sanitize_ident;

pub fn emit_volar(
    circuit: &NamedVolarCircuit,
    opt: &EmitOptions,
) -> Result<SourcePackage, EmitError> {
    if circuit.has_externals() {
        return Err(EmitError::unsupported(
            "oracle/action/rng",
            "v1 Noir backend rejects externals",
        ));
    }
    if circuit.has_storage() {
        return Err(EmitError::unsupported(
            "storage",
            "run StorageToMux or use the POD2 backend",
        ));
    }

    let pkg = sanitize_ident(&opt.package_name)?;
    let fn_name = sanitize_ident(&opt.circuit_name)?;
    let types = &circuit.types;

    let params: Result<Vec<String>, EmitError> = circuit
        .inputs
        .iter()
        .map(|p| Ok(format!("{}: {}", p.wire.name, noir_type(types, p.ty)?)))
        .collect();
    let params = params?.join(", ");

    let mut body = String::new();
    for stmt in &circuit.stmts {
        if !stmt.dst.bind {
            continue;
        }
        let ty = noir_stmt_ty(circuit, &stmt.op)?;
        let expr = render_op(circuit, &stmt.op)?;
        body.push_str(&format!("    let {}: {ty} = {expr};\n", stmt.dst.name));
    }

    let out_tys: Result<Vec<String>, EmitError> = circuit
        .outputs
        .iter()
        .map(|id| {
            let ty = circuit
                .type_of
                .get(id)
                .copied()
                .ok_or(EmitError::UnknownVar { id: *id })?;
            noir_type(types, ty)
        })
        .collect();
    let out_tys = out_tys?;
    let outs: Result<Vec<String>, EmitError> = circuit
        .outputs
        .iter()
        .map(|id| render_ref(circuit, *id))
        .collect();
    let outs = outs?;

    let (ret_ty, ret_expr) = match outs.len() {
        0 => (String::from("()"), String::from("    ()\n")),
        1 => (out_tys[0].clone(), format!("    {}\n", outs[0])),
        _ => (
            format!("({})", out_tys.join(", ")),
            format!("    ({})\n", outs.join(", ")),
        ),
    };
    body.push_str(&ret_expr);

    let lib = format!(
        "// Generated by volar-noir-backend. Library only — the embedder owns `main`\n\
         // and public/private witness flags.\n\
         // Integer ops are wrapping in Volar IR; Noir integer overflow fails the proof.\n\
         pub fn {fn_name}({params}) -> {ret_ty} {{\n\
         {body}}}\n"
    );

    let embed_params: Result<Vec<String>, EmitError> = circuit
        .inputs
        .iter()
        .map(|p| Ok(format!("{}: {}", p.wire.name, noir_type(types, p.ty)?)))
        .collect();
    let embed_args: Vec<String> = circuit
        .inputs
        .iter()
        .map(|p| p.wire.name.clone())
        .collect();
    let embed = format!(
        "// Embedder-owned entry. `pub` on the return is the verifier-visible ABI.\n\
         use {pkg}::{fn_name};\n\
         fn main({}) -> pub {ret_ty} {{\n\
             {fn_name}({})\n\
         }}\n",
        embed_params?.join(", "),
        embed_args.join(", ")
    );

    Ok(package_files_for_lib(&pkg, &lib, &embed))
}

fn noir_stmt_ty(circuit: &NamedVolarCircuit, op: &NamedVolarOp) -> Result<String, EmitError> {
    match op {
        NamedVolarOp::Const { ty, .. }
        | NamedVolarOp::Poly { ty, .. }
        | NamedVolarOp::Rol { ty, .. }
        | NamedVolarOp::Ror { ty, .. }
        | NamedVolarOp::Merge { ty, .. }
        | NamedVolarOp::Splat { ty, .. }
        | NamedVolarOp::Shuffle { ty, .. }
        | NamedVolarOp::StorageRead { ty, .. } => noir_type(&circuit.types, *ty),
        NamedVolarOp::Transmute { dst_ty, .. } => noir_type(&circuit.types, *dst_ty),
        NamedVolarOp::StorageWrite { .. } => Ok(String::from("bool")),
        NamedVolarOp::External { .. } => Ok(String::from("bool")),
    }
}

pub fn noir_type(types: &IRTypes, id: TypeId) -> Result<String, EmitError> {
    let ty = types.0.get(id.0 as usize).ok_or_else(|| EmitError::TypeUnsupported {
        ty: format!("unknown type id {}", id.0),
    })?;
    match ty {
        IrType::Primitive(Type::Bit) => Ok(String::from("bool")),
        IrType::Primitive(Type::_8) => Ok(String::from("u8")),
        IrType::Primitive(Type::_16) => Ok(String::from("u16")),
        IrType::Primitive(Type::_32) => Ok(String::from("u32")),
        IrType::Primitive(Type::_64) => Ok(String::from("u64")),
        IrType::Primitive(other) => Err(EmitError::TypeUnsupported {
            ty: format!("{other:?}"),
        }),
        IrType::Vec(n, elem) => Ok(format!("[{}; {n}]", noir_type(types, *elem)?)),
        IrType::Tuple(fields) => {
            let parts: Result<Vec<String>, EmitError> =
                fields.iter().map(|f| noir_type(types, *f)).collect();
            Ok(format!("({})", parts?.join(", ")))
        }
        IrType::Block { .. } => Err(EmitError::TypeUnsupported {
            ty: "Block".into(),
        }),
        IrType::Func { .. } => Err(EmitError::TypeUnsupported { ty: "Func".into() }),
        _ => panic!("noir_type: unhandled IrType variant — add lowering for this variant"),
    }
}

fn render_ref(circuit: &NamedVolarCircuit, id: IRVarId) -> Result<String, EmitError> {
    let wire = circuit.wire(id).ok_or(EmitError::UnknownVar { id })?;
    if wire.bind || circuit.is_input(id) {
        return Ok(wire.name.clone());
    }
    let stmt = circuit
        .stmt_defining(id)
        .ok_or(EmitError::UnknownVar { id })?;
    Ok(format!("({})", render_op(circuit, &stmt.op)?))
}

fn render_op(circuit: &NamedVolarCircuit, op: &NamedVolarOp) -> Result<String, EmitError> {
    let types = &circuit.types;
    match op {
        NamedVolarOp::Const { value, ty } => const_lit(types, *ty, value),
        NamedVolarOp::Transmute {
            src,
            src_ty,
            dst_ty,
        } => {
            let src_s = render_ref(circuit, *src)?;
            transmute_expr(types, *src_ty, *dst_ty, &src_s)
        }
        NamedVolarOp::Poly {
            ty,
            coeffs,
            constant,
        } => render_poly(circuit, *ty, coeffs, constant),
        NamedVolarOp::Rol { src, ty, n } => {
            let w = ir_type_bit_width(types, *ty)?;
            let n = if w == 0 { 0 } else { n % w };
            let s = render_ref(circuit, *src)?;
            let t = noir_type(types, *ty)?;
            Ok(format!(
                "(({s} << ({n} as u32)) | ({s} >> ((({w} - {n}) as u32)))) as {t}"
            ))
        }
        NamedVolarOp::Ror { src, ty, n } => {
            let w = ir_type_bit_width(types, *ty)?;
            let n = if w == 0 { 0 } else { n % w };
            let s = render_ref(circuit, *src)?;
            let t = noir_type(types, *ty)?;
            Ok(format!(
                "(({s} >> ({n} as u32)) | ({s} << ((({w} - {n}) as u32)))) as {t}"
            ))
        }
        NamedVolarOp::Merge { parts, ty } => render_merge(circuit, parts, *ty),
        NamedVolarOp::Splat { src, ty } => {
            let s = render_ref(circuit, *src)?;
            let ones = all_ones_lit(types, *ty)?;
            let t = noir_type(types, *ty)?;
            if type_is_bit(types, *ty) {
                Ok(s)
            } else {
                Ok(format!("if {s} {{ {ones} }} else {{ (0 as {t}) }}"))
            }
        }
        NamedVolarOp::Shuffle { result_bits, ty } => render_shuffle(circuit, result_bits, *ty),
        NamedVolarOp::StorageRead { .. } | NamedVolarOp::StorageWrite { .. } => {
            Err(EmitError::unsupported(
                "storage",
                "run StorageToMux or use the POD2 backend",
            ))
        }
        NamedVolarOp::External { kind, name } => Err(EmitError::unsupported(
            format!("{kind:?} `{name}`"),
            "v1 Noir backend rejects externals",
        )),
    }
}

fn const_lit(types: &IRTypes, ty: TypeId, c: &Constant) -> Result<String, EmitError> {
    let w = ir_type_bit_width(types, ty)?;
    if type_is_bit(types, ty) {
        return Ok(if (c.lo & 1) != 0 {
            String::from("true")
        } else {
            String::from("false")
        });
    }
    if w > 64 {
        return Err(EmitError::TypeUnsupported {
            ty: format!("{w}-bit constant"),
        });
    }
    let mask = if w == 64 { u64::MAX } else { (1u64 << w) - 1 };
    let val = (c.lo as u64) & mask;
    let t = noir_type(types, ty)?;
    Ok(format!("{val} as {t}"))
}

fn all_ones_lit(types: &IRTypes, ty: TypeId) -> Result<String, EmitError> {
    let w = ir_type_bit_width(types, ty)?;
    if type_is_bit(types, ty) {
        return Ok(String::from("true"));
    }
    if w > 64 {
        return Err(EmitError::TypeUnsupported {
            ty: format!("{w}-bit ones"),
        });
    }
    let mask = if w == 64 { u64::MAX } else { (1u64 << w) - 1 };
    let t = noir_type(types, ty)?;
    Ok(format!("{mask} as {t}"))
}

fn transmute_expr(
    types: &IRTypes,
    src_ty: TypeId,
    dst_ty: TypeId,
    src: &str,
) -> Result<String, EmitError> {
    let dst_t = noir_type(types, dst_ty)?;
    if type_is_bit(types, dst_ty) {
        if type_is_bit(types, src_ty) {
            return Ok(src.to_string());
        }
        return Ok(format!("(({src} as u64) & 1) == 1"));
    }
    if type_is_bit(types, src_ty) {
        return Ok(format!("if {src} {{ 1 as {dst_t} }} else {{ 0 as {dst_t} }}"));
    }
    Ok(format!("{src} as {dst_t}"))
}

fn render_poly(
    circuit: &NamedVolarCircuit,
    ty: TypeId,
    coeffs: &PolyCoeffs<IRVarId>,
    constant: &Constant,
) -> Result<String, EmitError> {
    let types = &circuit.types;
    let dest_bit = type_is_bit(types, ty);
    let mut acc = const_lit(types, ty, constant)?;
    for (mono, coeff) in coeffs {
        if coeff & 1 == 0 {
            continue;
        }
        let prod = monomial(circuit, ty, mono)?;
        if dest_bit {
            acc = format!("({acc}) != ({prod})");
        } else {
            acc = format!("({acc}) ^ ({prod})");
        }
    }
    Ok(acc)
}

fn monomial(
    circuit: &NamedVolarCircuit,
    dest_ty: TypeId,
    vars: &[IRVarId],
) -> Result<String, EmitError> {
    let types = &circuit.types;
    let dest_bit = type_is_bit(types, dest_ty);
    if vars.is_empty() {
        return if dest_bit {
            Ok(String::from("true"))
        } else {
            all_ones_lit(types, dest_ty)
        };
    }
    if dest_bit {
        let parts: Result<Vec<String>, EmitError> =
            vars.iter().map(|v| render_ref(circuit, *v)).collect();
        return Ok(parts?.join(" & "));
    }
    let t = noir_type(types, dest_ty)?;
    let mut prod = all_ones_lit(types, dest_ty)?;
    for v in vars {
        let s = render_ref(circuit, *v)?;
        let src_bit = circuit
            .type_of
            .get(v)
            .map(|ty| type_is_bit(types, *ty))
            .unwrap_or(false);
        if src_bit {
            prod = format!("if {s} {{ {prod} }} else {{ (0 as {t}) }}");
        } else {
            prod = format!("({prod}) & ({s})");
        }
    }
    Ok(prod)
}

fn render_merge(
    circuit: &NamedVolarCircuit,
    parts: &[IRVarId],
    ty: TypeId,
) -> Result<String, EmitError> {
    let types = &circuit.types;
    if type_is_bit(types, ty) {
        return match parts.first() {
            Some(id) => render_ref(circuit, *id),
            None => Ok(String::from("false")),
        };
    }
    let t = noir_type(types, ty)?;
    let mut shift = 0usize;
    let mut terms = Vec::new();
    for part in parts {
        let s = render_ref(circuit, *part)?;
        let part_ty = circuit.type_of.get(part).copied();
        let part_w = match part_ty {
            Some(pt) => ir_type_bit_width(types, pt)?,
            None => 1,
        };
        if part_ty.is_some_and(|pt| type_is_bit(types, pt)) {
            terms.push(format!("(if {s} {{ 1 as {t} }} else {{ 0 as {t} }}) << ({shift} as u32)"));
        } else {
            terms.push(format!("(({s} as {t}) << ({shift} as u32))"));
        }
        shift += part_w;
    }
    if terms.is_empty() {
        return Ok(format!("0 as {t}"));
    }
    Ok(terms.join(" | "))
}

fn render_shuffle(
    circuit: &NamedVolarCircuit,
    result_bits: &[(u8, IRVarId)],
    ty: TypeId,
) -> Result<String, EmitError> {
    let types = &circuit.types;
    let t = noir_type(types, ty)?;
    if type_is_bit(types, ty) {
        return match result_bits.first() {
            Some((bit_idx, var)) => extract_bit(circuit, *var, *bit_idx as usize),
            None => Ok(String::from("false")),
        };
    }
    let mut terms = Vec::new();
    for (i, (bit_idx, var)) in result_bits.iter().enumerate() {
        let bit = extract_bit(circuit, *var, *bit_idx as usize)?;
        terms.push(format!(
            "(if {bit} {{ 1 as {t} }} else {{ 0 as {t} }}) << ({i} as u32)"
        ));
    }
    if terms.is_empty() {
        return Ok(format!("0 as {t}"));
    }
    Ok(terms.join(" | "))
}

fn extract_bit(
    circuit: &NamedVolarCircuit,
    var: IRVarId,
    bit_idx: usize,
) -> Result<String, EmitError> {
    let s = render_ref(circuit, var)?;
    let src_bit = circuit
        .type_of
        .get(&var)
        .map(|ty| type_is_bit(&circuit.types, *ty))
        .unwrap_or(false);
    if src_bit {
        if bit_idx == 0 {
            Ok(s)
        } else {
            Ok(String::from("false"))
        }
    } else {
        Ok(format!("(({s} as u64) >> ({bit_idx} as u64)) & 1 == 1"))
    }
}
