[package]
name = "volar-lir"
version = "0.1.0"
edition = "2024"
license.workspace = true
description.workspace = true
repository.workspace = true

[features]
rkyv = ["dep:rkyv", "volar-ir-common/rkyv", "volar-side/rkyv"]

[dependencies]
volar-ir-common.workspace = true
volar-side.workspace = true
rkyv = { workspace = true, optional = true }
