// Generated by volar-ir-schema-gen; do not edit.
//
// This code deliberately implements rkyv's three traits directly and
// generates byte validation for archived values. The archived layout matches
// rkyv_derive's `#[repr(C)]` scalar-newtype layout, so pinned-rkyv binary
// artifacts remain byte-compatible.

/// Primitive (non-compound) type shared across Volar IR and VAFFLE.
#[derive(Clone, Copy, PartialEq, Eq, PartialOrd, Ord, Hash, Debug)]
#[non_exhaustive]
pub enum Type {
    Bit,
    _8,
    _16,
    _32,
    _64,
    _128,
    _256,
    AES8,
    Galois64,
    Z3,
}

#[cfg(feature = "rkyv")]
#[derive(Clone, Copy, PartialEq, Eq, PartialOrd, Ord, Hash, Debug, rkyv::bytecheck::CheckBytes)]
#[bytecheck(crate = rkyv::bytecheck)]
#[repr(u8)]
pub enum ArchivedType {
    Bit,
    _8,
    _16,
    _32,
    _64,
    _128,
    _256,
    AES8,
    Galois64,
    Z3,
}

#[cfg(feature = "rkyv")]
#[derive(Clone, Copy, Debug)]
pub enum TypeResolver {
    Bit,
    _8,
    _16,
    _32,
    _64,
    _128,
    _256,
    AES8,
    Galois64,
    Z3,
}

#[cfg(feature = "rkyv")]
unsafe impl rkyv::Portable for ArchivedType {}

#[cfg(feature = "rkyv")]
impl rkyv::Archive for Type {
    type Archived = ArchivedType;
    type Resolver = TypeResolver;

    fn resolve(&self, resolver: Self::Resolver, out: rkyv::Place<Self::Archived>) {
        let archived = match resolver {
            TypeResolver::Bit => ArchivedType::Bit,
            TypeResolver::_8 => ArchivedType::_8,
            TypeResolver::_16 => ArchivedType::_16,
            TypeResolver::_32 => ArchivedType::_32,
            TypeResolver::_64 => ArchivedType::_64,
            TypeResolver::_128 => ArchivedType::_128,
            TypeResolver::_256 => ArchivedType::_256,
            TypeResolver::AES8 => ArchivedType::AES8,
            TypeResolver::Galois64 => ArchivedType::Galois64,
            TypeResolver::Z3 => ArchivedType::Z3,
        };
        // SAFETY: `archived` is a fully initialized repr(u8) discriminant.
        unsafe { out.write_unchecked(archived) }
    }
}

#[cfg(feature = "rkyv")]
impl<S: rkyv::rancor::Fallible + ?Sized> rkyv::Serialize<S> for Type {
    fn serialize(&self, _: &mut S) -> Result<Self::Resolver, S::Error> {
        Ok(match self {
            Type::Bit => TypeResolver::Bit,
            Type::_8 => TypeResolver::_8,
            Type::_16 => TypeResolver::_16,
            Type::_32 => TypeResolver::_32,
            Type::_64 => TypeResolver::_64,
            Type::_128 => TypeResolver::_128,
            Type::_256 => TypeResolver::_256,
            Type::AES8 => TypeResolver::AES8,
            Type::Galois64 => TypeResolver::Galois64,
            Type::Z3 => TypeResolver::Z3,
        })
    }
}

#[cfg(feature = "rkyv")]
impl<D: rkyv::rancor::Fallible + ?Sized> rkyv::Deserialize<Type, D> for ArchivedType {
    fn deserialize(&self, _: &mut D) -> Result<Type, D::Error> {
        Ok(match self {
            ArchivedType::Bit => Type::Bit,
            ArchivedType::_8 => Type::_8,
            ArchivedType::_16 => Type::_16,
            ArchivedType::_32 => Type::_32,
            ArchivedType::_64 => Type::_64,
            ArchivedType::_128 => Type::_128,
            ArchivedType::_256 => Type::_256,
            ArchivedType::AES8 => Type::AES8,
            ArchivedType::Galois64 => Type::Galois64,
            ArchivedType::Z3 => Type::Z3,
        })
    }
}

/// A 256-bit compile-time constant, split into high and low 128-bit halves.
#[derive(Clone, Copy, PartialEq, Eq, PartialOrd, Ord, Hash, Debug)]
pub struct Constant {
    pub hi: u128,
    pub lo: u128,
}

#[cfg(feature = "rkyv")]
#[derive(PartialEq, Eq, PartialOrd, Ord, rkyv::bytecheck::CheckBytes)]
#[bytecheck(crate = rkyv::bytecheck)]
#[repr(C)]
pub struct ArchivedConstant {
    pub hi: <u128 as rkyv::Archive>::Archived,
    pub lo: <u128 as rkyv::Archive>::Archived,
}

#[cfg(feature = "rkyv")]
#[allow(dead_code)]
pub struct ConstantResolver {
    hi: <u128 as rkyv::Archive>::Resolver,
    lo: <u128 as rkyv::Archive>::Resolver,
}

#[cfg(feature = "rkyv")]
unsafe impl rkyv::Portable for ArchivedConstant
where
    <u128 as rkyv::Archive>::Archived: rkyv::Portable,
    <u128 as rkyv::Archive>::Archived: rkyv::Portable,
{
}

#[cfg(feature = "rkyv")]
impl rkyv::Archive for Constant {
    type Archived = ArchivedConstant;
    type Resolver = ConstantResolver;

    fn resolve(&self, resolver: Self::Resolver, out: rkyv::Place<Self::Archived>) {
        let field_ptr = unsafe { ::core::ptr::addr_of_mut!((*out.ptr()).hi) };
        let field_out = unsafe { rkyv::Place::from_field_unchecked(out, field_ptr) };
        rkyv::Archive::resolve(&self.hi, resolver.hi, field_out);
        let field_ptr = unsafe { ::core::ptr::addr_of_mut!((*out.ptr()).lo) };
        let field_out = unsafe { rkyv::Place::from_field_unchecked(out, field_ptr) };
        rkyv::Archive::resolve(&self.lo, resolver.lo, field_out);
    }
}

#[cfg(feature = "rkyv")]
impl<S: rkyv::rancor::Fallible + ?Sized> rkyv::Serialize<S> for Constant
where
    u128: rkyv::Serialize<S>,
    u128: rkyv::Serialize<S>,
{
    fn serialize(&self, serializer: &mut S) -> Result<Self::Resolver, S::Error> {
        Ok(ConstantResolver {
            hi: rkyv::Serialize::serialize(&self.hi, serializer)?,
            lo: rkyv::Serialize::serialize(&self.lo, serializer)?,
        })
    }
}

#[cfg(feature = "rkyv")]
impl<D: rkyv::rancor::Fallible + ?Sized> rkyv::Deserialize<Constant, D> for ArchivedConstant
where
    <u128 as rkyv::Archive>::Archived: rkyv::Deserialize<u128, D>,
    <u128 as rkyv::Archive>::Archived: rkyv::Deserialize<u128, D>,
{
    fn deserialize(&self, deserializer: &mut D) -> Result<Constant, D::Error> {
        Ok(Constant {
            hi: rkyv::Deserialize::deserialize(&self.hi, deserializer)?,
            lo: rkyv::Deserialize::deserialize(&self.lo, deserializer)?,
        })
    }
}

/// Public MPC party assigned to execute an external primitive.
#[derive(Clone, Copy, PartialEq, Eq, PartialOrd, Ord, Hash, Debug)]
pub enum ExternalExecutor {
    Garbler,
    Evaluator,
}

#[cfg(feature = "rkyv")]
#[derive(Clone, Copy, PartialEq, Eq, PartialOrd, Ord, Hash, Debug, rkyv::bytecheck::CheckBytes)]
#[bytecheck(crate = rkyv::bytecheck)]
#[repr(u8)]
pub enum ArchivedExternalExecutor {
    Garbler,
    Evaluator,
}

#[cfg(feature = "rkyv")]
#[derive(Clone, Copy, Debug)]
pub enum ExternalExecutorResolver {
    Garbler,
    Evaluator,
}

#[cfg(feature = "rkyv")]
unsafe impl rkyv::Portable for ArchivedExternalExecutor {}

#[cfg(feature = "rkyv")]
impl rkyv::Archive for ExternalExecutor {
    type Archived = ArchivedExternalExecutor;
    type Resolver = ExternalExecutorResolver;

    fn resolve(&self, resolver: Self::Resolver, out: rkyv::Place<Self::Archived>) {
        let archived = match resolver {
            ExternalExecutorResolver::Garbler => ArchivedExternalExecutor::Garbler,
            ExternalExecutorResolver::Evaluator => ArchivedExternalExecutor::Evaluator,
        };
        // SAFETY: `archived` is a fully initialized repr(u8) discriminant.
        unsafe { out.write_unchecked(archived) }
    }
}

#[cfg(feature = "rkyv")]
impl<S: rkyv::rancor::Fallible + ?Sized> rkyv::Serialize<S> for ExternalExecutor {
    fn serialize(&self, _: &mut S) -> Result<Self::Resolver, S::Error> {
        Ok(match self {
            ExternalExecutor::Garbler => ExternalExecutorResolver::Garbler,
            ExternalExecutor::Evaluator => ExternalExecutorResolver::Evaluator,
        })
    }
}

#[cfg(feature = "rkyv")]
impl<D: rkyv::rancor::Fallible + ?Sized> rkyv::Deserialize<ExternalExecutor, D>
    for ArchivedExternalExecutor
{
    fn deserialize(&self, _: &mut D) -> Result<ExternalExecutor, D::Error> {
        Ok(match self {
            ArchivedExternalExecutor::Garbler => ExternalExecutor::Garbler,
            ArchivedExternalExecutor::Evaluator => ExternalExecutor::Evaluator,
        })
    }
}

/// Public authorization describing which roles receive clear external inputs.
#[derive(Clone, Copy, PartialEq, Eq, PartialOrd, Ord, Hash, Debug)]
pub enum ExternalRevealPolicy {
    ExecutorOnly,
    BothRoles,
}

#[cfg(feature = "rkyv")]
#[derive(Clone, Copy, PartialEq, Eq, PartialOrd, Ord, Hash, Debug, rkyv::bytecheck::CheckBytes)]
#[bytecheck(crate = rkyv::bytecheck)]
#[repr(u8)]
pub enum ArchivedExternalRevealPolicy {
    ExecutorOnly,
    BothRoles,
}

#[cfg(feature = "rkyv")]
#[derive(Clone, Copy, Debug)]
pub enum ExternalRevealPolicyResolver {
    ExecutorOnly,
    BothRoles,
}

#[cfg(feature = "rkyv")]
unsafe impl rkyv::Portable for ArchivedExternalRevealPolicy {}

#[cfg(feature = "rkyv")]
impl rkyv::Archive for ExternalRevealPolicy {
    type Archived = ArchivedExternalRevealPolicy;
    type Resolver = ExternalRevealPolicyResolver;

    fn resolve(&self, resolver: Self::Resolver, out: rkyv::Place<Self::Archived>) {
        let archived = match resolver {
            ExternalRevealPolicyResolver::ExecutorOnly => {
                ArchivedExternalRevealPolicy::ExecutorOnly
            }
            ExternalRevealPolicyResolver::BothRoles => ArchivedExternalRevealPolicy::BothRoles,
        };
        // SAFETY: `archived` is a fully initialized repr(u8) discriminant.
        unsafe { out.write_unchecked(archived) }
    }
}

#[cfg(feature = "rkyv")]
impl<S: rkyv::rancor::Fallible + ?Sized> rkyv::Serialize<S> for ExternalRevealPolicy {
    fn serialize(&self, _: &mut S) -> Result<Self::Resolver, S::Error> {
        Ok(match self {
            ExternalRevealPolicy::ExecutorOnly => ExternalRevealPolicyResolver::ExecutorOnly,
            ExternalRevealPolicy::BothRoles => ExternalRevealPolicyResolver::BothRoles,
        })
    }
}

#[cfg(feature = "rkyv")]
impl<D: rkyv::rancor::Fallible + ?Sized> rkyv::Deserialize<ExternalRevealPolicy, D>
    for ArchivedExternalRevealPolicy
{
    fn deserialize(&self, _: &mut D) -> Result<ExternalRevealPolicy, D::Error> {
        Ok(match self {
            ArchivedExternalRevealPolicy::ExecutorOnly => ExternalRevealPolicy::ExecutorOnly,
            ArchivedExternalRevealPolicy::BothRoles => ExternalRevealPolicy::BothRoles,
        })
    }
}

/// Whether a pure oracle is assigned to one executor or replicated.
#[derive(Clone, Copy, PartialEq, Eq, PartialOrd, Ord, Hash, Debug)]
pub enum OracleExecutionKind {
    Assigned,
    Replicated,
}

#[cfg(feature = "rkyv")]
#[derive(Clone, Copy, PartialEq, Eq, PartialOrd, Ord, Hash, Debug, rkyv::bytecheck::CheckBytes)]
#[bytecheck(crate = rkyv::bytecheck)]
#[repr(u8)]
pub enum ArchivedOracleExecutionKind {
    Assigned,
    Replicated,
}

#[cfg(feature = "rkyv")]
#[derive(Clone, Copy, Debug)]
pub enum OracleExecutionKindResolver {
    Assigned,
    Replicated,
}

#[cfg(feature = "rkyv")]
unsafe impl rkyv::Portable for ArchivedOracleExecutionKind {}

#[cfg(feature = "rkyv")]
impl rkyv::Archive for OracleExecutionKind {
    type Archived = ArchivedOracleExecutionKind;
    type Resolver = OracleExecutionKindResolver;

    fn resolve(&self, resolver: Self::Resolver, out: rkyv::Place<Self::Archived>) {
        let archived = match resolver {
            OracleExecutionKindResolver::Assigned => ArchivedOracleExecutionKind::Assigned,
            OracleExecutionKindResolver::Replicated => ArchivedOracleExecutionKind::Replicated,
        };
        // SAFETY: `archived` is a fully initialized repr(u8) discriminant.
        unsafe { out.write_unchecked(archived) }
    }
}

#[cfg(feature = "rkyv")]
impl<S: rkyv::rancor::Fallible + ?Sized> rkyv::Serialize<S> for OracleExecutionKind {
    fn serialize(&self, _: &mut S) -> Result<Self::Resolver, S::Error> {
        Ok(match self {
            OracleExecutionKind::Assigned => OracleExecutionKindResolver::Assigned,
            OracleExecutionKind::Replicated => OracleExecutionKindResolver::Replicated,
        })
    }
}

#[cfg(feature = "rkyv")]
impl<D: rkyv::rancor::Fallible + ?Sized> rkyv::Deserialize<OracleExecutionKind, D>
    for ArchivedOracleExecutionKind
{
    fn deserialize(&self, _: &mut D) -> Result<OracleExecutionKind, D::Error> {
        Ok(match self {
            ArchivedOracleExecutionKind::Assigned => OracleExecutionKind::Assigned,
            ArchivedOracleExecutionKind::Replicated => OracleExecutionKind::Replicated,
        })
    }
}

/// Public action executor, reveal policy, and declaration fingerprint.
#[derive(Clone, Copy, PartialEq, Eq, PartialOrd, Ord, Hash, Debug)]
pub struct ActionExecutionPolicy {
    pub executor: ExternalExecutor,
    pub reveal: ExternalRevealPolicy,
    pub fingerprint: [u8; 32],
}

#[cfg(feature = "rkyv")]
#[derive(rkyv::bytecheck::CheckBytes)]
#[bytecheck(crate = rkyv::bytecheck)]
#[repr(C)]
pub struct ArchivedActionExecutionPolicy {
    pub executor: <ExternalExecutor as rkyv::Archive>::Archived,
    pub reveal: <ExternalRevealPolicy as rkyv::Archive>::Archived,
    pub fingerprint: <[u8; 32] as rkyv::Archive>::Archived,
}

#[cfg(feature = "rkyv")]
#[allow(dead_code)]
pub struct ActionExecutionPolicyResolver {
    executor: <ExternalExecutor as rkyv::Archive>::Resolver,
    reveal: <ExternalRevealPolicy as rkyv::Archive>::Resolver,
    fingerprint: <[u8; 32] as rkyv::Archive>::Resolver,
}

#[cfg(feature = "rkyv")]
unsafe impl rkyv::Portable for ArchivedActionExecutionPolicy
where
    <ExternalExecutor as rkyv::Archive>::Archived: rkyv::Portable,
    <ExternalRevealPolicy as rkyv::Archive>::Archived: rkyv::Portable,
    <[u8; 32] as rkyv::Archive>::Archived: rkyv::Portable,
{
}

#[cfg(feature = "rkyv")]
impl rkyv::Archive for ActionExecutionPolicy {
    type Archived = ArchivedActionExecutionPolicy;
    type Resolver = ActionExecutionPolicyResolver;

    fn resolve(&self, resolver: Self::Resolver, out: rkyv::Place<Self::Archived>) {
        let field_ptr = unsafe { ::core::ptr::addr_of_mut!((*out.ptr()).executor) };
        let field_out = unsafe { rkyv::Place::from_field_unchecked(out, field_ptr) };
        rkyv::Archive::resolve(&self.executor, resolver.executor, field_out);
        let field_ptr = unsafe { ::core::ptr::addr_of_mut!((*out.ptr()).reveal) };
        let field_out = unsafe { rkyv::Place::from_field_unchecked(out, field_ptr) };
        rkyv::Archive::resolve(&self.reveal, resolver.reveal, field_out);
        let field_ptr = unsafe { ::core::ptr::addr_of_mut!((*out.ptr()).fingerprint) };
        let field_out = unsafe { rkyv::Place::from_field_unchecked(out, field_ptr) };
        rkyv::Archive::resolve(&self.fingerprint, resolver.fingerprint, field_out);
    }
}

#[cfg(feature = "rkyv")]
impl<S: rkyv::rancor::Fallible + ?Sized> rkyv::Serialize<S> for ActionExecutionPolicy
where
    ExternalExecutor: rkyv::Serialize<S>,
    ExternalRevealPolicy: rkyv::Serialize<S>,
    [u8; 32]: rkyv::Serialize<S>,
{
    fn serialize(&self, serializer: &mut S) -> Result<Self::Resolver, S::Error> {
        Ok(ActionExecutionPolicyResolver {
            executor: rkyv::Serialize::serialize(&self.executor, serializer)?,
            reveal: rkyv::Serialize::serialize(&self.reveal, serializer)?,
            fingerprint: rkyv::Serialize::serialize(&self.fingerprint, serializer)?,
        })
    }
}

#[cfg(feature = "rkyv")]
impl<D: rkyv::rancor::Fallible + ?Sized> rkyv::Deserialize<ActionExecutionPolicy, D>
    for ArchivedActionExecutionPolicy
where
    <ExternalExecutor as rkyv::Archive>::Archived: rkyv::Deserialize<ExternalExecutor, D>,
    <ExternalRevealPolicy as rkyv::Archive>::Archived: rkyv::Deserialize<ExternalRevealPolicy, D>,
    <[u8; 32] as rkyv::Archive>::Archived: rkyv::Deserialize<[u8; 32], D>,
{
    fn deserialize(&self, deserializer: &mut D) -> Result<ActionExecutionPolicy, D::Error> {
        Ok(ActionExecutionPolicy {
            executor: rkyv::Deserialize::deserialize(&self.executor, deserializer)?,
            reveal: rkyv::Deserialize::deserialize(&self.reveal, deserializer)?,
            fingerprint: rkyv::Deserialize::deserialize(&self.fingerprint, deserializer)?,
        })
    }
}

/// Public oracle execution, reveal policy, and declaration fingerprint.
#[derive(Clone, Copy, PartialEq, Eq, PartialOrd, Ord, Hash, Debug)]
pub struct OracleExecutionPolicy {
    pub execution: OracleExecutionKind,
    pub executor: ExternalExecutor,
    pub reveal: ExternalRevealPolicy,
    pub fingerprint: [u8; 32],
}

#[cfg(feature = "rkyv")]
#[derive(rkyv::bytecheck::CheckBytes)]
#[bytecheck(crate = rkyv::bytecheck)]
#[repr(C)]
pub struct ArchivedOracleExecutionPolicy {
    pub execution: <OracleExecutionKind as rkyv::Archive>::Archived,
    pub executor: <ExternalExecutor as rkyv::Archive>::Archived,
    pub reveal: <ExternalRevealPolicy as rkyv::Archive>::Archived,
    pub fingerprint: <[u8; 32] as rkyv::Archive>::Archived,
}

#[cfg(feature = "rkyv")]
#[allow(dead_code)]
pub struct OracleExecutionPolicyResolver {
    execution: <OracleExecutionKind as rkyv::Archive>::Resolver,
    executor: <ExternalExecutor as rkyv::Archive>::Resolver,
    reveal: <ExternalRevealPolicy as rkyv::Archive>::Resolver,
    fingerprint: <[u8; 32] as rkyv::Archive>::Resolver,
}

#[cfg(feature = "rkyv")]
unsafe impl rkyv::Portable for ArchivedOracleExecutionPolicy
where
    <OracleExecutionKind as rkyv::Archive>::Archived: rkyv::Portable,
    <ExternalExecutor as rkyv::Archive>::Archived: rkyv::Portable,
    <ExternalRevealPolicy as rkyv::Archive>::Archived: rkyv::Portable,
    <[u8; 32] as rkyv::Archive>::Archived: rkyv::Portable,
{
}

#[cfg(feature = "rkyv")]
impl rkyv::Archive for OracleExecutionPolicy {
    type Archived = ArchivedOracleExecutionPolicy;
    type Resolver = OracleExecutionPolicyResolver;

    fn resolve(&self, resolver: Self::Resolver, out: rkyv::Place<Self::Archived>) {
        let field_ptr = unsafe { ::core::ptr::addr_of_mut!((*out.ptr()).execution) };
        let field_out = unsafe { rkyv::Place::from_field_unchecked(out, field_ptr) };
        rkyv::Archive::resolve(&self.execution, resolver.execution, field_out);
        let field_ptr = unsafe { ::core::ptr::addr_of_mut!((*out.ptr()).executor) };
        let field_out = unsafe { rkyv::Place::from_field_unchecked(out, field_ptr) };
        rkyv::Archive::resolve(&self.executor, resolver.executor, field_out);
        let field_ptr = unsafe { ::core::ptr::addr_of_mut!((*out.ptr()).reveal) };
        let field_out = unsafe { rkyv::Place::from_field_unchecked(out, field_ptr) };
        rkyv::Archive::resolve(&self.reveal, resolver.reveal, field_out);
        let field_ptr = unsafe { ::core::ptr::addr_of_mut!((*out.ptr()).fingerprint) };
        let field_out = unsafe { rkyv::Place::from_field_unchecked(out, field_ptr) };
        rkyv::Archive::resolve(&self.fingerprint, resolver.fingerprint, field_out);
    }
}

#[cfg(feature = "rkyv")]
impl<S: rkyv::rancor::Fallible + ?Sized> rkyv::Serialize<S> for OracleExecutionPolicy
where
    OracleExecutionKind: rkyv::Serialize<S>,
    ExternalExecutor: rkyv::Serialize<S>,
    ExternalRevealPolicy: rkyv::Serialize<S>,
    [u8; 32]: rkyv::Serialize<S>,
{
    fn serialize(&self, serializer: &mut S) -> Result<Self::Resolver, S::Error> {
        Ok(OracleExecutionPolicyResolver {
            execution: rkyv::Serialize::serialize(&self.execution, serializer)?,
            executor: rkyv::Serialize::serialize(&self.executor, serializer)?,
            reveal: rkyv::Serialize::serialize(&self.reveal, serializer)?,
            fingerprint: rkyv::Serialize::serialize(&self.fingerprint, serializer)?,
        })
    }
}

#[cfg(feature = "rkyv")]
impl<D: rkyv::rancor::Fallible + ?Sized> rkyv::Deserialize<OracleExecutionPolicy, D>
    for ArchivedOracleExecutionPolicy
where
    <OracleExecutionKind as rkyv::Archive>::Archived: rkyv::Deserialize<OracleExecutionKind, D>,
    <ExternalExecutor as rkyv::Archive>::Archived: rkyv::Deserialize<ExternalExecutor, D>,
    <ExternalRevealPolicy as rkyv::Archive>::Archived: rkyv::Deserialize<ExternalRevealPolicy, D>,
    <[u8; 32] as rkyv::Archive>::Archived: rkyv::Deserialize<[u8; 32], D>,
{
    fn deserialize(&self, deserializer: &mut D) -> Result<OracleExecutionPolicy, D::Error> {
        Ok(OracleExecutionPolicy {
            execution: rkyv::Deserialize::deserialize(&self.execution, deserializer)?,
            executor: rkyv::Deserialize::deserialize(&self.executor, deserializer)?,
            reveal: rkyv::Deserialize::deserialize(&self.reveal, deserializer)?,
            fingerprint: rkyv::Deserialize::deserialize(&self.fingerprint, deserializer)?,
        })
    }
}

/// Declaration of a named pure oracle.
#[derive(Clone, PartialEq, Eq, PartialOrd, Ord, Hash, Debug)]
pub struct OracleDecl {
    pub name: alloc::string::String,
    pub params: alloc::vec::Vec<TypeId>,
    pub results: alloc::vec::Vec<TypeId>,
    pub execution: OracleExecutionPolicy,
}

#[cfg(feature = "rkyv")]
#[derive(rkyv::bytecheck::CheckBytes)]
#[bytecheck(crate = rkyv::bytecheck)]
#[repr(C)]
pub struct ArchivedOracleDecl {
    pub name: <alloc::string::String as rkyv::Archive>::Archived,
    pub params: <alloc::vec::Vec<TypeId> as rkyv::Archive>::Archived,
    pub results: <alloc::vec::Vec<TypeId> as rkyv::Archive>::Archived,
    pub execution: <OracleExecutionPolicy as rkyv::Archive>::Archived,
}

#[cfg(feature = "rkyv")]
#[allow(dead_code)]
pub struct OracleDeclResolver {
    name: <alloc::string::String as rkyv::Archive>::Resolver,
    params: <alloc::vec::Vec<TypeId> as rkyv::Archive>::Resolver,
    results: <alloc::vec::Vec<TypeId> as rkyv::Archive>::Resolver,
    execution: <OracleExecutionPolicy as rkyv::Archive>::Resolver,
}

#[cfg(feature = "rkyv")]
unsafe impl rkyv::Portable for ArchivedOracleDecl
where
    <alloc::string::String as rkyv::Archive>::Archived: rkyv::Portable,
    <alloc::vec::Vec<TypeId> as rkyv::Archive>::Archived: rkyv::Portable,
    <alloc::vec::Vec<TypeId> as rkyv::Archive>::Archived: rkyv::Portable,
    <OracleExecutionPolicy as rkyv::Archive>::Archived: rkyv::Portable,
{
}

#[cfg(feature = "rkyv")]
impl rkyv::Archive for OracleDecl {
    type Archived = ArchivedOracleDecl;
    type Resolver = OracleDeclResolver;

    fn resolve(&self, resolver: Self::Resolver, out: rkyv::Place<Self::Archived>) {
        let field_ptr = unsafe { ::core::ptr::addr_of_mut!((*out.ptr()).name) };
        let field_out = unsafe { rkyv::Place::from_field_unchecked(out, field_ptr) };
        rkyv::Archive::resolve(&self.name, resolver.name, field_out);
        let field_ptr = unsafe { ::core::ptr::addr_of_mut!((*out.ptr()).params) };
        let field_out = unsafe { rkyv::Place::from_field_unchecked(out, field_ptr) };
        rkyv::Archive::resolve(&self.params, resolver.params, field_out);
        let field_ptr = unsafe { ::core::ptr::addr_of_mut!((*out.ptr()).results) };
        let field_out = unsafe { rkyv::Place::from_field_unchecked(out, field_ptr) };
        rkyv::Archive::resolve(&self.results, resolver.results, field_out);
        let field_ptr = unsafe { ::core::ptr::addr_of_mut!((*out.ptr()).execution) };
        let field_out = unsafe { rkyv::Place::from_field_unchecked(out, field_ptr) };
        rkyv::Archive::resolve(&self.execution, resolver.execution, field_out);
    }
}

#[cfg(feature = "rkyv")]
impl<S: rkyv::rancor::Fallible + ?Sized> rkyv::Serialize<S> for OracleDecl
where
    alloc::string::String: rkyv::Serialize<S>,
    alloc::vec::Vec<TypeId>: rkyv::Serialize<S>,
    alloc::vec::Vec<TypeId>: rkyv::Serialize<S>,
    OracleExecutionPolicy: rkyv::Serialize<S>,
{
    fn serialize(&self, serializer: &mut S) -> Result<Self::Resolver, S::Error> {
        Ok(OracleDeclResolver {
            name: rkyv::Serialize::serialize(&self.name, serializer)?,
            params: rkyv::Serialize::serialize(&self.params, serializer)?,
            results: rkyv::Serialize::serialize(&self.results, serializer)?,
            execution: rkyv::Serialize::serialize(&self.execution, serializer)?,
        })
    }
}

#[cfg(feature = "rkyv")]
impl<D: rkyv::rancor::Fallible + ?Sized> rkyv::Deserialize<OracleDecl, D> for ArchivedOracleDecl
where
    <alloc::string::String as rkyv::Archive>::Archived: rkyv::Deserialize<alloc::string::String, D>,
    <alloc::vec::Vec<TypeId> as rkyv::Archive>::Archived:
        rkyv::Deserialize<alloc::vec::Vec<TypeId>, D>,
    <alloc::vec::Vec<TypeId> as rkyv::Archive>::Archived:
        rkyv::Deserialize<alloc::vec::Vec<TypeId>, D>,
    <OracleExecutionPolicy as rkyv::Archive>::Archived: rkyv::Deserialize<OracleExecutionPolicy, D>,
{
    fn deserialize(&self, deserializer: &mut D) -> Result<OracleDecl, D::Error> {
        Ok(OracleDecl {
            name: rkyv::Deserialize::deserialize(&self.name, deserializer)?,
            params: rkyv::Deserialize::deserialize(&self.params, deserializer)?,
            results: rkyv::Deserialize::deserialize(&self.results, deserializer)?,
            execution: rkyv::Deserialize::deserialize(&self.execution, deserializer)?,
        })
    }
}

/// Declaration of a named conditional action.
#[derive(Clone, PartialEq, Eq, PartialOrd, Ord, Hash, Debug)]
pub struct ActionDecl {
    pub name: alloc::string::String,
    pub params: alloc::vec::Vec<TypeId>,
    pub results: alloc::vec::Vec<TypeId>,
    pub execution: ActionExecutionPolicy,
}

#[cfg(feature = "rkyv")]
#[derive(rkyv::bytecheck::CheckBytes)]
#[bytecheck(crate = rkyv::bytecheck)]
#[repr(C)]
pub struct ArchivedActionDecl {
    pub name: <alloc::string::String as rkyv::Archive>::Archived,
    pub params: <alloc::vec::Vec<TypeId> as rkyv::Archive>::Archived,
    pub results: <alloc::vec::Vec<TypeId> as rkyv::Archive>::Archived,
    pub execution: <ActionExecutionPolicy as rkyv::Archive>::Archived,
}

#[cfg(feature = "rkyv")]
#[allow(dead_code)]
pub struct ActionDeclResolver {
    name: <alloc::string::String as rkyv::Archive>::Resolver,
    params: <alloc::vec::Vec<TypeId> as rkyv::Archive>::Resolver,
    results: <alloc::vec::Vec<TypeId> as rkyv::Archive>::Resolver,
    execution: <ActionExecutionPolicy as rkyv::Archive>::Resolver,
}

#[cfg(feature = "rkyv")]
unsafe impl rkyv::Portable for ArchivedActionDecl
where
    <alloc::string::String as rkyv::Archive>::Archived: rkyv::Portable,
    <alloc::vec::Vec<TypeId> as rkyv::Archive>::Archived: rkyv::Portable,
    <alloc::vec::Vec<TypeId> as rkyv::Archive>::Archived: rkyv::Portable,
    <ActionExecutionPolicy as rkyv::Archive>::Archived: rkyv::Portable,
{
}

#[cfg(feature = "rkyv")]
impl rkyv::Archive for ActionDecl {
    type Archived = ArchivedActionDecl;
    type Resolver = ActionDeclResolver;

    fn resolve(&self, resolver: Self::Resolver, out: rkyv::Place<Self::Archived>) {
        let field_ptr = unsafe { ::core::ptr::addr_of_mut!((*out.ptr()).name) };
        let field_out = unsafe { rkyv::Place::from_field_unchecked(out, field_ptr) };
        rkyv::Archive::resolve(&self.name, resolver.name, field_out);
        let field_ptr = unsafe { ::core::ptr::addr_of_mut!((*out.ptr()).params) };
        let field_out = unsafe { rkyv::Place::from_field_unchecked(out, field_ptr) };
        rkyv::Archive::resolve(&self.params, resolver.params, field_out);
        let field_ptr = unsafe { ::core::ptr::addr_of_mut!((*out.ptr()).results) };
        let field_out = unsafe { rkyv::Place::from_field_unchecked(out, field_ptr) };
        rkyv::Archive::resolve(&self.results, resolver.results, field_out);
        let field_ptr = unsafe { ::core::ptr::addr_of_mut!((*out.ptr()).execution) };
        let field_out = unsafe { rkyv::Place::from_field_unchecked(out, field_ptr) };
        rkyv::Archive::resolve(&self.execution, resolver.execution, field_out);
    }
}

#[cfg(feature = "rkyv")]
impl<S: rkyv::rancor::Fallible + ?Sized> rkyv::Serialize<S> for ActionDecl
where
    alloc::string::String: rkyv::Serialize<S>,
    alloc::vec::Vec<TypeId>: rkyv::Serialize<S>,
    alloc::vec::Vec<TypeId>: rkyv::Serialize<S>,
    ActionExecutionPolicy: rkyv::Serialize<S>,
{
    fn serialize(&self, serializer: &mut S) -> Result<Self::Resolver, S::Error> {
        Ok(ActionDeclResolver {
            name: rkyv::Serialize::serialize(&self.name, serializer)?,
            params: rkyv::Serialize::serialize(&self.params, serializer)?,
            results: rkyv::Serialize::serialize(&self.results, serializer)?,
            execution: rkyv::Serialize::serialize(&self.execution, serializer)?,
        })
    }
}

#[cfg(feature = "rkyv")]
impl<D: rkyv::rancor::Fallible + ?Sized> rkyv::Deserialize<ActionDecl, D> for ArchivedActionDecl
where
    <alloc::string::String as rkyv::Archive>::Archived: rkyv::Deserialize<alloc::string::String, D>,
    <alloc::vec::Vec<TypeId> as rkyv::Archive>::Archived:
        rkyv::Deserialize<alloc::vec::Vec<TypeId>, D>,
    <alloc::vec::Vec<TypeId> as rkyv::Archive>::Archived:
        rkyv::Deserialize<alloc::vec::Vec<TypeId>, D>,
    <ActionExecutionPolicy as rkyv::Archive>::Archived: rkyv::Deserialize<ActionExecutionPolicy, D>,
{
    fn deserialize(&self, deserializer: &mut D) -> Result<ActionDecl, D::Error> {
        Ok(ActionDecl {
            name: rkyv::Deserialize::deserialize(&self.name, deserializer)?,
            params: rkyv::Deserialize::deserialize(&self.params, deserializer)?,
            results: rkyv::Deserialize::deserialize(&self.results, deserializer)?,
            execution: rkyv::Deserialize::deserialize(&self.execution, deserializer)?,
        })
    }
}

/// Declaration of a named source of fresh random values.
#[derive(Clone, PartialEq, Eq, PartialOrd, Ord, Hash, Debug)]
pub struct RngDecl {
    pub name: alloc::string::String,
    pub ty: TypeId,
}

#[cfg(feature = "rkyv")]
#[derive(rkyv::bytecheck::CheckBytes)]
#[bytecheck(crate = rkyv::bytecheck)]
#[repr(C)]
pub struct ArchivedRngDecl {
    pub name: <alloc::string::String as rkyv::Archive>::Archived,
    pub ty: <TypeId as rkyv::Archive>::Archived,
}

#[cfg(feature = "rkyv")]
#[allow(dead_code)]
pub struct RngDeclResolver {
    name: <alloc::string::String as rkyv::Archive>::Resolver,
    ty: <TypeId as rkyv::Archive>::Resolver,
}

#[cfg(feature = "rkyv")]
unsafe impl rkyv::Portable for ArchivedRngDecl
where
    <alloc::string::String as rkyv::Archive>::Archived: rkyv::Portable,
    <TypeId as rkyv::Archive>::Archived: rkyv::Portable,
{
}

#[cfg(feature = "rkyv")]
impl rkyv::Archive for RngDecl {
    type Archived = ArchivedRngDecl;
    type Resolver = RngDeclResolver;

    fn resolve(&self, resolver: Self::Resolver, out: rkyv::Place<Self::Archived>) {
        let field_ptr = unsafe { ::core::ptr::addr_of_mut!((*out.ptr()).name) };
        let field_out = unsafe { rkyv::Place::from_field_unchecked(out, field_ptr) };
        rkyv::Archive::resolve(&self.name, resolver.name, field_out);
        let field_ptr = unsafe { ::core::ptr::addr_of_mut!((*out.ptr()).ty) };
        let field_out = unsafe { rkyv::Place::from_field_unchecked(out, field_ptr) };
        rkyv::Archive::resolve(&self.ty, resolver.ty, field_out);
    }
}

#[cfg(feature = "rkyv")]
impl<S: rkyv::rancor::Fallible + ?Sized> rkyv::Serialize<S> for RngDecl
where
    alloc::string::String: rkyv::Serialize<S>,
    TypeId: rkyv::Serialize<S>,
{
    fn serialize(&self, serializer: &mut S) -> Result<Self::Resolver, S::Error> {
        Ok(RngDeclResolver {
            name: rkyv::Serialize::serialize(&self.name, serializer)?,
            ty: rkyv::Serialize::serialize(&self.ty, serializer)?,
        })
    }
}

#[cfg(feature = "rkyv")]
impl<D: rkyv::rancor::Fallible + ?Sized> rkyv::Deserialize<RngDecl, D> for ArchivedRngDecl
where
    <alloc::string::String as rkyv::Archive>::Archived: rkyv::Deserialize<alloc::string::String, D>,
    <TypeId as rkyv::Archive>::Archived: rkyv::Deserialize<TypeId, D>,
{
    fn deserialize(&self, deserializer: &mut D) -> Result<RngDecl, D::Error> {
        Ok(RngDecl {
            name: rkyv::Deserialize::deserialize(&self.name, deserializer)?,
            ty: rkyv::Deserialize::deserialize(&self.ty, deserializer)?,
        })
    }
}

/// A contiguous run of pre-initialised typed storage elements.
#[derive(Clone, PartialEq, Eq, PartialOrd, Ord, Hash, Debug)]
pub struct PreInitSegment {
    pub storage: StorageId,
    pub ty: TypeId,
    pub offset: usize,
    pub data: alloc::vec::Vec<Constant>,
}

#[cfg(feature = "rkyv")]
#[derive(rkyv::bytecheck::CheckBytes)]
#[bytecheck(crate = rkyv::bytecheck)]
#[repr(C)]
pub struct ArchivedPreInitSegment {
    pub storage: <StorageId as rkyv::Archive>::Archived,
    pub ty: <TypeId as rkyv::Archive>::Archived,
    pub offset: <usize as rkyv::Archive>::Archived,
    pub data: <alloc::vec::Vec<Constant> as rkyv::Archive>::Archived,
}

#[cfg(feature = "rkyv")]
#[allow(dead_code)]
pub struct PreInitSegmentResolver {
    storage: <StorageId as rkyv::Archive>::Resolver,
    ty: <TypeId as rkyv::Archive>::Resolver,
    offset: <usize as rkyv::Archive>::Resolver,
    data: <alloc::vec::Vec<Constant> as rkyv::Archive>::Resolver,
}

#[cfg(feature = "rkyv")]
unsafe impl rkyv::Portable for ArchivedPreInitSegment
where
    <StorageId as rkyv::Archive>::Archived: rkyv::Portable,
    <TypeId as rkyv::Archive>::Archived: rkyv::Portable,
    <usize as rkyv::Archive>::Archived: rkyv::Portable,
    <alloc::vec::Vec<Constant> as rkyv::Archive>::Archived: rkyv::Portable,
{
}

#[cfg(feature = "rkyv")]
impl rkyv::Archive for PreInitSegment {
    type Archived = ArchivedPreInitSegment;
    type Resolver = PreInitSegmentResolver;

    fn resolve(&self, resolver: Self::Resolver, out: rkyv::Place<Self::Archived>) {
        let field_ptr = unsafe { ::core::ptr::addr_of_mut!((*out.ptr()).storage) };
        let field_out = unsafe { rkyv::Place::from_field_unchecked(out, field_ptr) };
        rkyv::Archive::resolve(&self.storage, resolver.storage, field_out);
        let field_ptr = unsafe { ::core::ptr::addr_of_mut!((*out.ptr()).ty) };
        let field_out = unsafe { rkyv::Place::from_field_unchecked(out, field_ptr) };
        rkyv::Archive::resolve(&self.ty, resolver.ty, field_out);
        let field_ptr = unsafe { ::core::ptr::addr_of_mut!((*out.ptr()).offset) };
        let field_out = unsafe { rkyv::Place::from_field_unchecked(out, field_ptr) };
        rkyv::Archive::resolve(&self.offset, resolver.offset, field_out);
        let field_ptr = unsafe { ::core::ptr::addr_of_mut!((*out.ptr()).data) };
        let field_out = unsafe { rkyv::Place::from_field_unchecked(out, field_ptr) };
        rkyv::Archive::resolve(&self.data, resolver.data, field_out);
    }
}

#[cfg(feature = "rkyv")]
impl<S: rkyv::rancor::Fallible + ?Sized> rkyv::Serialize<S> for PreInitSegment
where
    StorageId: rkyv::Serialize<S>,
    TypeId: rkyv::Serialize<S>,
    usize: rkyv::Serialize<S>,
    alloc::vec::Vec<Constant>: rkyv::Serialize<S>,
{
    fn serialize(&self, serializer: &mut S) -> Result<Self::Resolver, S::Error> {
        Ok(PreInitSegmentResolver {
            storage: rkyv::Serialize::serialize(&self.storage, serializer)?,
            ty: rkyv::Serialize::serialize(&self.ty, serializer)?,
            offset: rkyv::Serialize::serialize(&self.offset, serializer)?,
            data: rkyv::Serialize::serialize(&self.data, serializer)?,
        })
    }
}

#[cfg(feature = "rkyv")]
impl<D: rkyv::rancor::Fallible + ?Sized> rkyv::Deserialize<PreInitSegment, D>
    for ArchivedPreInitSegment
where
    <StorageId as rkyv::Archive>::Archived: rkyv::Deserialize<StorageId, D>,
    <TypeId as rkyv::Archive>::Archived: rkyv::Deserialize<TypeId, D>,
    <usize as rkyv::Archive>::Archived: rkyv::Deserialize<usize, D>,
    <alloc::vec::Vec<Constant> as rkyv::Archive>::Archived:
        rkyv::Deserialize<alloc::vec::Vec<Constant>, D>,
{
    fn deserialize(&self, deserializer: &mut D) -> Result<PreInitSegment, D::Error> {
        Ok(PreInitSegment {
            storage: rkyv::Deserialize::deserialize(&self.storage, deserializer)?,
            ty: rkyv::Deserialize::deserialize(&self.ty, deserializer)?,
            offset: rkyv::Deserialize::deserialize(&self.offset, deserializer)?,
            data: rkyv::Deserialize::deserialize(&self.data, deserializer)?,
        })
    }
}

/// Opaque index into the module-local IR type table.
#[derive(Clone, Copy, PartialEq, Eq, PartialOrd, Ord, Hash, Debug)]
pub struct TypeId(pub u32);

#[cfg(feature = "rkyv")]
#[derive(Clone, Copy, PartialEq, Eq, PartialOrd, Ord, Debug, rkyv::bytecheck::CheckBytes)]
#[bytecheck(crate = rkyv::bytecheck)]
#[repr(C)]
pub struct ArchivedTypeId(pub rkyv::primitive::ArchivedU32);

#[cfg(feature = "rkyv")]
unsafe impl rkyv::Portable for ArchivedTypeId {}

#[cfg(feature = "rkyv")]
impl rkyv::Archive for TypeId {
    type Archived = ArchivedTypeId;
    type Resolver = ();

    fn resolve(&self, (): Self::Resolver, out: rkyv::Place<Self::Archived>) {
        // SAFETY: the generated archived newtype is repr(C), contains exactly
        // one initialized portable scalar, and has no padding.
        unsafe {
            out.write_unchecked(ArchivedTypeId(rkyv::primitive::ArchivedU32::from_native(
                self.0,
            )))
        }
    }
}

#[cfg(feature = "rkyv")]
impl<S: rkyv::rancor::Fallible + ?Sized> rkyv::Serialize<S> for TypeId {
    fn serialize(&self, _: &mut S) -> Result<Self::Resolver, S::Error> {
        Ok(())
    }
}

#[cfg(feature = "rkyv")]
impl<D: rkyv::rancor::Fallible + ?Sized> rkyv::Deserialize<TypeId, D> for ArchivedTypeId {
    fn deserialize(&self, _: &mut D) -> Result<TypeId, D::Error> {
        Ok(TypeId(self.0.to_native()))
    }
}

/// Opaque identifier for an independent storage space.
#[derive(Clone, Copy, PartialEq, Eq, PartialOrd, Ord, Hash, Debug)]
pub struct StorageId(pub u32);

#[cfg(feature = "rkyv")]
#[derive(Clone, Copy, PartialEq, Eq, PartialOrd, Ord, Debug, rkyv::bytecheck::CheckBytes)]
#[bytecheck(crate = rkyv::bytecheck)]
#[repr(C)]
pub struct ArchivedStorageId(pub rkyv::primitive::ArchivedU32);

#[cfg(feature = "rkyv")]
unsafe impl rkyv::Portable for ArchivedStorageId {}

#[cfg(feature = "rkyv")]
impl rkyv::Archive for StorageId {
    type Archived = ArchivedStorageId;
    type Resolver = ();

    fn resolve(&self, (): Self::Resolver, out: rkyv::Place<Self::Archived>) {
        // SAFETY: the generated archived newtype is repr(C), contains exactly
        // one initialized portable scalar, and has no padding.
        unsafe {
            out.write_unchecked(ArchivedStorageId(
                rkyv::primitive::ArchivedU32::from_native(self.0),
            ))
        }
    }
}

#[cfg(feature = "rkyv")]
impl<S: rkyv::rancor::Fallible + ?Sized> rkyv::Serialize<S> for StorageId {
    fn serialize(&self, _: &mut S) -> Result<Self::Resolver, S::Error> {
        Ok(())
    }
}

#[cfg(feature = "rkyv")]
impl<D: rkyv::rancor::Fallible + ?Sized> rkyv::Deserialize<StorageId, D> for ArchivedStorageId {
    fn deserialize(&self, _: &mut D) -> Result<StorageId, D::Error> {
        Ok(StorageId(self.0.to_native()))
    }
}

/// An IR value paired with provenance and an optional side annotation.
#[derive(Clone, PartialEq, Eq, PartialOrd, Ord, Hash, Debug)]
pub struct Node<T, P: Clone = ()> {
    pub kind: T,
    pub prov: P,
    pub side: core::option::Option<volar_side::SideId>,
}

#[cfg(feature = "rkyv")]
#[derive(rkyv::bytecheck::CheckBytes)]
#[bytecheck(crate = rkyv::bytecheck)]
#[repr(C)]
pub struct ArchivedNode<T: rkyv::Archive, P: Clone + rkyv::Archive = ()> {
    pub kind: <T as rkyv::Archive>::Archived,
    pub prov: <P as rkyv::Archive>::Archived,
    pub side: <core::option::Option<volar_side::SideId> as rkyv::Archive>::Archived,
}

#[cfg(feature = "rkyv")]
#[allow(dead_code)]
pub struct NodeResolver<T: rkyv::Archive, P: Clone + rkyv::Archive = ()> {
    kind: <T as rkyv::Archive>::Resolver,
    prov: <P as rkyv::Archive>::Resolver,
    side: <core::option::Option<volar_side::SideId> as rkyv::Archive>::Resolver,
}

#[cfg(feature = "rkyv")]
unsafe impl<T: rkyv::Archive, P: Clone + rkyv::Archive> rkyv::Portable for ArchivedNode<T, P>
where
    <T as rkyv::Archive>::Archived: rkyv::Portable,
    <P as rkyv::Archive>::Archived: rkyv::Portable,
    <core::option::Option<volar_side::SideId> as rkyv::Archive>::Archived: rkyv::Portable,
{
}

#[cfg(feature = "rkyv")]
impl<T: rkyv::Archive, P: Clone + rkyv::Archive> rkyv::Archive for Node<T, P> {
    type Archived = ArchivedNode<T, P>;
    type Resolver = NodeResolver<T, P>;

    fn resolve(&self, resolver: Self::Resolver, out: rkyv::Place<Self::Archived>) {
        let field_ptr = unsafe { ::core::ptr::addr_of_mut!((*out.ptr()).kind) };
        let field_out = unsafe { rkyv::Place::from_field_unchecked(out, field_ptr) };
        rkyv::Archive::resolve(&self.kind, resolver.kind, field_out);
        let field_ptr = unsafe { ::core::ptr::addr_of_mut!((*out.ptr()).prov) };
        let field_out = unsafe { rkyv::Place::from_field_unchecked(out, field_ptr) };
        rkyv::Archive::resolve(&self.prov, resolver.prov, field_out);
        let field_ptr = unsafe { ::core::ptr::addr_of_mut!((*out.ptr()).side) };
        let field_out = unsafe { rkyv::Place::from_field_unchecked(out, field_ptr) };
        rkyv::Archive::resolve(&self.side, resolver.side, field_out);
    }
}

#[cfg(feature = "rkyv")]
impl<T: rkyv::Archive, P: Clone + rkyv::Archive, S: rkyv::rancor::Fallible + ?Sized>
    rkyv::Serialize<S> for Node<T, P>
where
    T: rkyv::Serialize<S>,
    P: rkyv::Serialize<S>,
    core::option::Option<volar_side::SideId>: rkyv::Serialize<S>,
{
    fn serialize(&self, serializer: &mut S) -> Result<Self::Resolver, S::Error> {
        Ok(NodeResolver {
            kind: rkyv::Serialize::serialize(&self.kind, serializer)?,
            prov: rkyv::Serialize::serialize(&self.prov, serializer)?,
            side: rkyv::Serialize::serialize(&self.side, serializer)?,
        })
    }
}

#[cfg(feature = "rkyv")]
impl<T: rkyv::Archive, P: Clone + rkyv::Archive, D: rkyv::rancor::Fallible + ?Sized>
    rkyv::Deserialize<Node<T, P>, D> for ArchivedNode<T, P>
where
    <T as rkyv::Archive>::Archived: rkyv::Deserialize<T, D>,
    <P as rkyv::Archive>::Archived: rkyv::Deserialize<P, D>,
    <core::option::Option<volar_side::SideId> as rkyv::Archive>::Archived:
        rkyv::Deserialize<core::option::Option<volar_side::SideId>, D>,
{
    fn deserialize(&self, deserializer: &mut D) -> Result<Node<T, P>, D::Error> {
        Ok(Node {
            kind: rkyv::Deserialize::deserialize(&self.kind, deserializer)?,
            prov: rkyv::Deserialize::deserialize(&self.prov, deserializer)?,
            side: rkyv::Deserialize::deserialize(&self.side, deserializer)?,
        })
    }
}
