// Generated by volar-ir-schema-gen; do not edit.
//
// This code deliberately implements rkyv's three traits directly and
// generates byte validation for archived values. The archived layout matches
// rkyv_derive's `#[repr(C)]` scalar-newtype layout, so pinned-rkyv binary
// artifacts remain byte-compatible.

/// A recorded sequence of low-level IR target calls that can be replayed into any target.
#[derive(Clone, Debug, PartialEq, Default)]
pub struct SavedLirModule {
    pub calls: alloc::vec::Vec<crate::LirCall>,
}

#[cfg(feature = "rkyv")]
#[derive(rkyv::bytecheck::CheckBytes)]
#[bytecheck(crate = rkyv::bytecheck)]
#[repr(C)]
pub struct ArchivedSavedLirModule {
    pub calls: <alloc::vec::Vec<crate::LirCall> as rkyv::Archive>::Archived,
}

#[cfg(feature = "rkyv")]
#[allow(dead_code)]
pub struct SavedLirModuleResolver {
    calls: <alloc::vec::Vec<crate::LirCall> as rkyv::Archive>::Resolver,
}

#[cfg(feature = "rkyv")]
unsafe impl rkyv::Portable for ArchivedSavedLirModule
where
    <alloc::vec::Vec<crate::LirCall> as rkyv::Archive>::Archived: rkyv::Portable,
{}

#[cfg(feature = "rkyv")]
impl rkyv::Archive for SavedLirModule {
    type Archived = ArchivedSavedLirModule;
    type Resolver = SavedLirModuleResolver;

    fn resolve(&self, resolver: Self::Resolver, out: rkyv::Place<Self::Archived>) {
        let field_ptr = unsafe { ::core::ptr::addr_of_mut!((*out.ptr()).calls) };
        let field_out = unsafe { rkyv::Place::from_field_unchecked(out, field_ptr) };
        rkyv::Archive::resolve(&self.calls, resolver.calls, field_out);
    }
}

#[cfg(feature = "rkyv")]
impl<S: rkyv::rancor::Fallible + ?Sized> rkyv::Serialize<S> for SavedLirModule
where
    alloc::vec::Vec<crate::LirCall>: rkyv::Serialize<S>,
{
    fn serialize(&self, serializer: &mut S) -> Result<Self::Resolver, S::Error> {
        Ok(SavedLirModuleResolver {
            calls: rkyv::Serialize::serialize(&self.calls, serializer)?,
        })
    }
}

#[cfg(feature = "rkyv")]
impl<D: rkyv::rancor::Fallible + ?Sized> rkyv::Deserialize<SavedLirModule, D>
    for ArchivedSavedLirModule
where
    <alloc::vec::Vec<crate::LirCall> as rkyv::Archive>::Archived: rkyv::Deserialize<alloc::vec::Vec<crate::LirCall>, D>,
{
    fn deserialize(&self, deserializer: &mut D) -> Result<SavedLirModule, D::Error> {
        Ok(SavedLirModule {
            calls: rkyv::Deserialize::deserialize(&self.calls, deserializer)?,
        })
    }
}

