// Generated by volar-ir-schema-gen; do not edit.
//
// This code deliberately implements rkyv's three traits directly and
// generates byte validation for archived values. The archived layout matches
// rkyv_derive's `#[repr(C)]` scalar-newtype layout, so pinned-rkyv binary
// artifacts remain byte-compatible.

/// Class of a replayable reversible external source.
#[derive(Clone, Copy, PartialEq, Eq, PartialOrd, Ord, Hash, Debug)]
pub enum RExternalKind {
    Oracle,
    Rng,
}

#[cfg(feature = "rkyv")]
#[derive(Clone, Copy, PartialEq, Eq, PartialOrd, Ord, Hash, Debug, rkyv::bytecheck::CheckBytes)]
#[bytecheck(crate = rkyv::bytecheck)]
#[repr(u8)]
pub enum ArchivedRExternalKind {
    Oracle,
    Rng,
}

#[cfg(feature = "rkyv")]
#[derive(Clone, Copy, Debug)]
pub enum RExternalKindResolver {
    Oracle,
    Rng,
}

#[cfg(feature = "rkyv")]
unsafe impl rkyv::Portable for ArchivedRExternalKind {}

#[cfg(feature = "rkyv")]
impl rkyv::Archive for RExternalKind {
    type Archived = ArchivedRExternalKind;
    type Resolver = RExternalKindResolver;

    fn resolve(&self, resolver: Self::Resolver, out: rkyv::Place<Self::Archived>) {
        let archived = match resolver {
            RExternalKindResolver::Oracle => ArchivedRExternalKind::Oracle,
            RExternalKindResolver::Rng => ArchivedRExternalKind::Rng,
        };
        // SAFETY: `archived` is a fully initialized repr(u8) discriminant.
        unsafe { out.write_unchecked(archived) }
    }
}

#[cfg(feature = "rkyv")]
impl<S: rkyv::rancor::Fallible + ?Sized> rkyv::Serialize<S> for RExternalKind {
    fn serialize(&self, _: &mut S) -> Result<Self::Resolver, S::Error> {
        Ok(match self {
            RExternalKind::Oracle => RExternalKindResolver::Oracle,
            RExternalKind::Rng => RExternalKindResolver::Rng,
        })
    }
}

#[cfg(feature = "rkyv")]
impl<D: rkyv::rancor::Fallible + ?Sized> rkyv::Deserialize<RExternalKind, D>
    for ArchivedRExternalKind
{
    fn deserialize(&self, _: &mut D) -> Result<RExternalKind, D::Error> {
        Ok(match self {
            ArchivedRExternalKind::Oracle => RExternalKind::Oracle,
            ArchivedRExternalKind::Rng => RExternalKind::Rng,
        })
    }
}

/// A validated reversible circuit over a fixed number of wires.
#[derive(Clone, PartialEq, Eq, PartialOrd, Ord, Hash, Debug, Default)]
pub struct RCircuit {
    pub num_wires: usize,
    pub gates: alloc::vec::Vec<crate::rcircuit::RGate>,
}

#[cfg(feature = "rkyv")]
#[derive(rkyv::bytecheck::CheckBytes)]
#[bytecheck(crate = rkyv::bytecheck)]
#[repr(C)]
pub struct ArchivedRCircuit {
    pub num_wires: <usize as rkyv::Archive>::Archived,
    pub gates: <alloc::vec::Vec<crate::rcircuit::RGate> as rkyv::Archive>::Archived,
}

#[cfg(feature = "rkyv")]
#[allow(dead_code)]
pub struct RCircuitResolver {
    num_wires: <usize as rkyv::Archive>::Resolver,
    gates: <alloc::vec::Vec<crate::rcircuit::RGate> as rkyv::Archive>::Resolver,
}

#[cfg(feature = "rkyv")]
unsafe impl rkyv::Portable for ArchivedRCircuit
where
    <usize as rkyv::Archive>::Archived: rkyv::Portable,
    <alloc::vec::Vec<crate::rcircuit::RGate> as rkyv::Archive>::Archived: rkyv::Portable,
{}

#[cfg(feature = "rkyv")]
impl rkyv::Archive for RCircuit {
    type Archived = ArchivedRCircuit;
    type Resolver = RCircuitResolver;

    fn resolve(&self, resolver: Self::Resolver, out: rkyv::Place<Self::Archived>) {
        let field_ptr = unsafe { ::core::ptr::addr_of_mut!((*out.ptr()).num_wires) };
        let field_out = unsafe { rkyv::Place::from_field_unchecked(out, field_ptr) };
        rkyv::Archive::resolve(&self.num_wires, resolver.num_wires, field_out);
        let field_ptr = unsafe { ::core::ptr::addr_of_mut!((*out.ptr()).gates) };
        let field_out = unsafe { rkyv::Place::from_field_unchecked(out, field_ptr) };
        rkyv::Archive::resolve(&self.gates, resolver.gates, field_out);
    }
}

#[cfg(feature = "rkyv")]
impl<S: rkyv::rancor::Fallible + ?Sized> rkyv::Serialize<S> for RCircuit
where
    usize: rkyv::Serialize<S>,
    alloc::vec::Vec<crate::rcircuit::RGate>: rkyv::Serialize<S>,
{
    fn serialize(&self, serializer: &mut S) -> Result<Self::Resolver, S::Error> {
        Ok(RCircuitResolver {
            num_wires: rkyv::Serialize::serialize(&self.num_wires, serializer)?,
            gates: rkyv::Serialize::serialize(&self.gates, serializer)?,
        })
    }
}

#[cfg(feature = "rkyv")]
impl<D: rkyv::rancor::Fallible + ?Sized> rkyv::Deserialize<RCircuit, D>
    for ArchivedRCircuit
where
    <usize as rkyv::Archive>::Archived: rkyv::Deserialize<usize, D>,
    <alloc::vec::Vec<crate::rcircuit::RGate> as rkyv::Archive>::Archived: rkyv::Deserialize<alloc::vec::Vec<crate::rcircuit::RGate>, D>,
{
    fn deserialize(&self, deserializer: &mut D) -> Result<RCircuit, D::Error> {
        Ok(RCircuit {
            num_wires: rkyv::Deserialize::deserialize(&self.num_wires, deserializer)?,
            gates: rkyv::Deserialize::deserialize(&self.gates, deserializer)?,
        })
    }
}
