// Generated by volar-ir-schema-gen; do not edit.
//
// This code deliberately implements rkyv's three traits directly and
// generates byte validation for archived values. The archived layout matches
// rkyv_derive's `#[repr(C)]` scalar-newtype layout, so pinned-rkyv binary
// artifacts remain byte-compatible.

/// Portable reference to a compiler struct (module path plus name).
#[derive(Clone, PartialEq, Eq, PartialOrd, Ord, Hash, Debug)]
pub struct StructRef {
    pub module_path: alloc::vec::Vec<alloc::string::String>,
    pub name: alloc::string::String,
}

#[cfg(feature = "rkyv")]
#[derive(rkyv::bytecheck::CheckBytes)]
#[bytecheck(crate = rkyv::bytecheck)]
#[repr(C)]
pub struct ArchivedStructRef {
    pub module_path: <alloc::vec::Vec<alloc::string::String> as rkyv::Archive>::Archived,
    pub name: <alloc::string::String as rkyv::Archive>::Archived,
}

#[cfg(feature = "rkyv")]
#[allow(dead_code)]
pub struct StructRefResolver {
    module_path: <alloc::vec::Vec<alloc::string::String> as rkyv::Archive>::Resolver,
    name: <alloc::string::String as rkyv::Archive>::Resolver,
}

#[cfg(feature = "rkyv")]
unsafe impl rkyv::Portable for ArchivedStructRef
where
    <alloc::vec::Vec<alloc::string::String> as rkyv::Archive>::Archived: rkyv::Portable,
    <alloc::string::String as rkyv::Archive>::Archived: rkyv::Portable,
{}

#[cfg(feature = "rkyv")]
impl rkyv::Archive for StructRef {
    type Archived = ArchivedStructRef;
    type Resolver = StructRefResolver;

    fn resolve(&self, resolver: Self::Resolver, out: rkyv::Place<Self::Archived>) {
        let field_ptr = unsafe { ::core::ptr::addr_of_mut!((*out.ptr()).module_path) };
        let field_out = unsafe { rkyv::Place::from_field_unchecked(out, field_ptr) };
        rkyv::Archive::resolve(&self.module_path, resolver.module_path, field_out);
        let field_ptr = unsafe { ::core::ptr::addr_of_mut!((*out.ptr()).name) };
        let field_out = unsafe { rkyv::Place::from_field_unchecked(out, field_ptr) };
        rkyv::Archive::resolve(&self.name, resolver.name, field_out);
    }
}

#[cfg(feature = "rkyv")]
impl<S: rkyv::rancor::Fallible + ?Sized> rkyv::Serialize<S> for StructRef
where
    alloc::vec::Vec<alloc::string::String>: rkyv::Serialize<S>,
    alloc::string::String: rkyv::Serialize<S>,
{
    fn serialize(&self, serializer: &mut S) -> Result<Self::Resolver, S::Error> {
        Ok(StructRefResolver {
            module_path: rkyv::Serialize::serialize(&self.module_path, serializer)?,
            name: rkyv::Serialize::serialize(&self.name, serializer)?,
        })
    }
}

#[cfg(feature = "rkyv")]
impl<D: rkyv::rancor::Fallible + ?Sized> rkyv::Deserialize<StructRef, D>
    for ArchivedStructRef
where
    <alloc::vec::Vec<alloc::string::String> as rkyv::Archive>::Archived: rkyv::Deserialize<alloc::vec::Vec<alloc::string::String>, D>,
    <alloc::string::String as rkyv::Archive>::Archived: rkyv::Deserialize<alloc::string::String, D>,
{
    fn deserialize(&self, deserializer: &mut D) -> Result<StructRef, D::Error> {
        Ok(StructRef {
            module_path: rkyv::Deserialize::deserialize(&self.module_path, deserializer)?,
            name: rkyv::Deserialize::deserialize(&self.name, deserializer)?,
        })
    }
}

/// Well-founded descent metadata attached to a branch target.
#[derive(Clone, PartialEq, Eq, PartialOrd, Ord, Hash, Debug)]
pub struct ReentryHint {
    pub measures: alloc::vec::Vec<crate::complexity::MeasureSpec>,
}

#[cfg(feature = "rkyv")]
#[derive(rkyv::bytecheck::CheckBytes)]
#[bytecheck(crate = rkyv::bytecheck)]
#[repr(C)]
pub struct ArchivedReentryHint {
    pub measures: <alloc::vec::Vec<crate::complexity::MeasureSpec> as rkyv::Archive>::Archived,
}

#[cfg(feature = "rkyv")]
#[allow(dead_code)]
pub struct ReentryHintResolver {
    measures: <alloc::vec::Vec<crate::complexity::MeasureSpec> as rkyv::Archive>::Resolver,
}

#[cfg(feature = "rkyv")]
unsafe impl rkyv::Portable for ArchivedReentryHint
where
    <alloc::vec::Vec<crate::complexity::MeasureSpec> as rkyv::Archive>::Archived: rkyv::Portable,
{}

#[cfg(feature = "rkyv")]
impl rkyv::Archive for ReentryHint {
    type Archived = ArchivedReentryHint;
    type Resolver = ReentryHintResolver;

    fn resolve(&self, resolver: Self::Resolver, out: rkyv::Place<Self::Archived>) {
        let field_ptr = unsafe { ::core::ptr::addr_of_mut!((*out.ptr()).measures) };
        let field_out = unsafe { rkyv::Place::from_field_unchecked(out, field_ptr) };
        rkyv::Archive::resolve(&self.measures, resolver.measures, field_out);
    }
}

#[cfg(feature = "rkyv")]
impl<S: rkyv::rancor::Fallible + ?Sized> rkyv::Serialize<S> for ReentryHint
where
    alloc::vec::Vec<crate::complexity::MeasureSpec>: rkyv::Serialize<S>,
{
    fn serialize(&self, serializer: &mut S) -> Result<Self::Resolver, S::Error> {
        Ok(ReentryHintResolver {
            measures: rkyv::Serialize::serialize(&self.measures, serializer)?,
        })
    }
}

#[cfg(feature = "rkyv")]
impl<D: rkyv::rancor::Fallible + ?Sized> rkyv::Deserialize<ReentryHint, D>
    for ArchivedReentryHint
where
    <alloc::vec::Vec<crate::complexity::MeasureSpec> as rkyv::Archive>::Archived: rkyv::Deserialize<alloc::vec::Vec<crate::complexity::MeasureSpec>, D>,
{
    fn deserialize(&self, deserializer: &mut D) -> Result<ReentryHint, D::Error> {
        Ok(ReentryHint {
            measures: rkyv::Deserialize::deserialize(&self.measures, deserializer)?,
        })
    }
}

