// Generated by volar-ir-schema-gen; do not edit.
//
// This code deliberately implements rkyv's three traits directly and
// generates byte validation for archived values. The archived layout matches
// rkyv_derive's `#[repr(C)]` scalar-newtype layout, so pinned-rkyv binary
// artifacts remain byte-compatible.

/// Integer comparison predicate used by low-level IR.
#[derive(Clone, Copy, PartialEq, Eq, PartialOrd, Ord, Hash, Debug)]
pub enum IcmpPred {
    Eq,
    Ne,
    Ult,
    Ule,
    Ugt,
    Uge,
    Slt,
    Sle,
    Sgt,
    Sge,
}

#[cfg(feature = "rkyv")]
#[derive(Clone, Copy, PartialEq, Eq, PartialOrd, Ord, Hash, Debug, rkyv::bytecheck::CheckBytes)]
#[bytecheck(crate = rkyv::bytecheck)]
#[repr(u8)]
pub enum ArchivedIcmpPred {
    Eq,
    Ne,
    Ult,
    Ule,
    Ugt,
    Uge,
    Slt,
    Sle,
    Sgt,
    Sge,
}

#[cfg(feature = "rkyv")]
#[derive(Clone, Copy, Debug)]
pub enum IcmpPredResolver {
    Eq,
    Ne,
    Ult,
    Ule,
    Ugt,
    Uge,
    Slt,
    Sle,
    Sgt,
    Sge,
}

#[cfg(feature = "rkyv")]
unsafe impl rkyv::Portable for ArchivedIcmpPred {}

#[cfg(feature = "rkyv")]
impl rkyv::Archive for IcmpPred {
    type Archived = ArchivedIcmpPred;
    type Resolver = IcmpPredResolver;

    fn resolve(&self, resolver: Self::Resolver, out: rkyv::Place<Self::Archived>) {
        let archived = match resolver {
            IcmpPredResolver::Eq => ArchivedIcmpPred::Eq,
            IcmpPredResolver::Ne => ArchivedIcmpPred::Ne,
            IcmpPredResolver::Ult => ArchivedIcmpPred::Ult,
            IcmpPredResolver::Ule => ArchivedIcmpPred::Ule,
            IcmpPredResolver::Ugt => ArchivedIcmpPred::Ugt,
            IcmpPredResolver::Uge => ArchivedIcmpPred::Uge,
            IcmpPredResolver::Slt => ArchivedIcmpPred::Slt,
            IcmpPredResolver::Sle => ArchivedIcmpPred::Sle,
            IcmpPredResolver::Sgt => ArchivedIcmpPred::Sgt,
            IcmpPredResolver::Sge => ArchivedIcmpPred::Sge,
        };
        // SAFETY: `archived` is a fully initialized repr(u8) discriminant.
        unsafe { out.write_unchecked(archived) }
    }
}

#[cfg(feature = "rkyv")]
impl<S: rkyv::rancor::Fallible + ?Sized> rkyv::Serialize<S> for IcmpPred {
    fn serialize(&self, _: &mut S) -> Result<Self::Resolver, S::Error> {
        Ok(match self {
            IcmpPred::Eq => IcmpPredResolver::Eq,
            IcmpPred::Ne => IcmpPredResolver::Ne,
            IcmpPred::Ult => IcmpPredResolver::Ult,
            IcmpPred::Ule => IcmpPredResolver::Ule,
            IcmpPred::Ugt => IcmpPredResolver::Ugt,
            IcmpPred::Uge => IcmpPredResolver::Uge,
            IcmpPred::Slt => IcmpPredResolver::Slt,
            IcmpPred::Sle => IcmpPredResolver::Sle,
            IcmpPred::Sgt => IcmpPredResolver::Sgt,
            IcmpPred::Sge => IcmpPredResolver::Sge,
        })
    }
}

#[cfg(feature = "rkyv")]
impl<D: rkyv::rancor::Fallible + ?Sized> rkyv::Deserialize<IcmpPred, D>
    for ArchivedIcmpPred
{
    fn deserialize(&self, _: &mut D) -> Result<IcmpPred, D::Error> {
        Ok(match self {
            ArchivedIcmpPred::Eq => IcmpPred::Eq,
            ArchivedIcmpPred::Ne => IcmpPred::Ne,
            ArchivedIcmpPred::Ult => IcmpPred::Ult,
            ArchivedIcmpPred::Ule => IcmpPred::Ule,
            ArchivedIcmpPred::Ugt => IcmpPred::Ugt,
            ArchivedIcmpPred::Uge => IcmpPred::Uge,
            ArchivedIcmpPred::Slt => IcmpPred::Slt,
            ArchivedIcmpPred::Sle => IcmpPred::Sle,
            ArchivedIcmpPred::Sgt => IcmpPred::Sgt,
            ArchivedIcmpPred::Sge => IcmpPred::Sge,
        })
    }
}

/// One named field in a saved LIR struct definition.
#[derive(Clone, Debug, PartialEq, Eq)]
pub struct FieldDef {
    pub name: alloc::string::String,
    pub ty: crate::LirType,
}

#[cfg(feature = "rkyv")]
#[derive(rkyv::bytecheck::CheckBytes)]
#[bytecheck(crate = rkyv::bytecheck)]
#[repr(C)]
pub struct ArchivedFieldDef {
    pub name: <alloc::string::String as rkyv::Archive>::Archived,
    pub ty: <crate::LirType as rkyv::Archive>::Archived,
}

#[cfg(feature = "rkyv")]
#[allow(dead_code)]
pub struct FieldDefResolver {
    name: <alloc::string::String as rkyv::Archive>::Resolver,
    ty: <crate::LirType as rkyv::Archive>::Resolver,
}

#[cfg(feature = "rkyv")]
unsafe impl rkyv::Portable for ArchivedFieldDef
where
    <alloc::string::String as rkyv::Archive>::Archived: rkyv::Portable,
    <crate::LirType as rkyv::Archive>::Archived: rkyv::Portable,
{}

#[cfg(feature = "rkyv")]
impl rkyv::Archive for FieldDef {
    type Archived = ArchivedFieldDef;
    type Resolver = FieldDefResolver;

    fn resolve(&self, resolver: Self::Resolver, out: rkyv::Place<Self::Archived>) {
        let field_ptr = unsafe { ::core::ptr::addr_of_mut!((*out.ptr()).name) };
        let field_out = unsafe { rkyv::Place::from_field_unchecked(out, field_ptr) };
        rkyv::Archive::resolve(&self.name, resolver.name, field_out);
        let field_ptr = unsafe { ::core::ptr::addr_of_mut!((*out.ptr()).ty) };
        let field_out = unsafe { rkyv::Place::from_field_unchecked(out, field_ptr) };
        rkyv::Archive::resolve(&self.ty, resolver.ty, field_out);
    }
}

#[cfg(feature = "rkyv")]
impl<S: rkyv::rancor::Fallible + ?Sized> rkyv::Serialize<S> for FieldDef
where
    alloc::string::String: rkyv::Serialize<S>,
    crate::LirType: rkyv::Serialize<S>,
{
    fn serialize(&self, serializer: &mut S) -> Result<Self::Resolver, S::Error> {
        Ok(FieldDefResolver {
            name: rkyv::Serialize::serialize(&self.name, serializer)?,
            ty: rkyv::Serialize::serialize(&self.ty, serializer)?,
        })
    }
}

#[cfg(feature = "rkyv")]
impl<D: rkyv::rancor::Fallible + ?Sized> rkyv::Deserialize<FieldDef, D>
    for ArchivedFieldDef
where
    <alloc::string::String as rkyv::Archive>::Archived: rkyv::Deserialize<alloc::string::String, D>,
    <crate::LirType as rkyv::Archive>::Archived: rkyv::Deserialize<crate::LirType, D>,
{
    fn deserialize(&self, deserializer: &mut D) -> Result<FieldDef, D::Error> {
        Ok(FieldDef {
            name: rkyv::Deserialize::deserialize(&self.name, deserializer)?,
            ty: rkyv::Deserialize::deserialize(&self.ty, deserializer)?,
        })
    }
}

/// Controls how a low-level backend maps logical names to emitted names.
#[derive(Clone, Debug, Default)]
pub struct NameConfig {
    pub prefix: alloc::string::String,
    pub remap: alloc::collections::BTreeMap<alloc::string::String, alloc::string::String>,
}

#[cfg(feature = "rkyv")]
#[derive(rkyv::bytecheck::CheckBytes)]
#[bytecheck(crate = rkyv::bytecheck)]
#[repr(C)]
pub struct ArchivedNameConfig {
    pub prefix: <alloc::string::String as rkyv::Archive>::Archived,
    pub remap: <alloc::collections::BTreeMap<alloc::string::String, alloc::string::String> as rkyv::Archive>::Archived,
}

#[cfg(feature = "rkyv")]
#[allow(dead_code)]
pub struct NameConfigResolver {
    prefix: <alloc::string::String as rkyv::Archive>::Resolver,
    remap: <alloc::collections::BTreeMap<alloc::string::String, alloc::string::String> as rkyv::Archive>::Resolver,
}

#[cfg(feature = "rkyv")]
unsafe impl rkyv::Portable for ArchivedNameConfig
where
    <alloc::string::String as rkyv::Archive>::Archived: rkyv::Portable,
    <alloc::collections::BTreeMap<alloc::string::String, alloc::string::String> as rkyv::Archive>::Archived: rkyv::Portable,
{}

#[cfg(feature = "rkyv")]
impl rkyv::Archive for NameConfig {
    type Archived = ArchivedNameConfig;
    type Resolver = NameConfigResolver;

    fn resolve(&self, resolver: Self::Resolver, out: rkyv::Place<Self::Archived>) {
        let field_ptr = unsafe { ::core::ptr::addr_of_mut!((*out.ptr()).prefix) };
        let field_out = unsafe { rkyv::Place::from_field_unchecked(out, field_ptr) };
        rkyv::Archive::resolve(&self.prefix, resolver.prefix, field_out);
        let field_ptr = unsafe { ::core::ptr::addr_of_mut!((*out.ptr()).remap) };
        let field_out = unsafe { rkyv::Place::from_field_unchecked(out, field_ptr) };
        rkyv::Archive::resolve(&self.remap, resolver.remap, field_out);
    }
}

#[cfg(feature = "rkyv")]
impl<S: rkyv::rancor::Fallible + ?Sized> rkyv::Serialize<S> for NameConfig
where
    alloc::string::String: rkyv::Serialize<S>,
    alloc::collections::BTreeMap<alloc::string::String, alloc::string::String>: rkyv::Serialize<S>,
{
    fn serialize(&self, serializer: &mut S) -> Result<Self::Resolver, S::Error> {
        Ok(NameConfigResolver {
            prefix: rkyv::Serialize::serialize(&self.prefix, serializer)?,
            remap: rkyv::Serialize::serialize(&self.remap, serializer)?,
        })
    }
}

#[cfg(feature = "rkyv")]
impl<D: rkyv::rancor::Fallible + ?Sized> rkyv::Deserialize<NameConfig, D>
    for ArchivedNameConfig
where
    <alloc::string::String as rkyv::Archive>::Archived: rkyv::Deserialize<alloc::string::String, D>,
    <alloc::collections::BTreeMap<alloc::string::String, alloc::string::String> as rkyv::Archive>::Archived: rkyv::Deserialize<alloc::collections::BTreeMap<alloc::string::String, alloc::string::String>, D>,
{
    fn deserialize(&self, deserializer: &mut D) -> Result<NameConfig, D::Error> {
        Ok(NameConfig {
            prefix: rkyv::Deserialize::deserialize(&self.prefix, deserializer)?,
            remap: rkyv::Deserialize::deserialize(&self.remap, deserializer)?,
        })
    }
}

/// Destination for one low-level action-store result.
#[derive(Clone, PartialEq, Eq, Hash, Debug)]
pub struct ActionStoreTarget<Value> {
    pub storage: u64,
    pub lane: u32,
    pub address: Value,
    pub address_ty: crate::LirType,
}

#[cfg(feature = "rkyv")]
#[derive(rkyv::bytecheck::CheckBytes)]
#[bytecheck(crate = rkyv::bytecheck)]
#[repr(C)]
pub struct ArchivedActionStoreTarget<Value: rkyv::Archive> {
    pub storage: <u64 as rkyv::Archive>::Archived,
    pub lane: <u32 as rkyv::Archive>::Archived,
    pub address: <Value as rkyv::Archive>::Archived,
    pub address_ty: <crate::LirType as rkyv::Archive>::Archived,
}

#[cfg(feature = "rkyv")]
#[allow(dead_code)]
pub struct ActionStoreTargetResolver<Value: rkyv::Archive> {
    storage: <u64 as rkyv::Archive>::Resolver,
    lane: <u32 as rkyv::Archive>::Resolver,
    address: <Value as rkyv::Archive>::Resolver,
    address_ty: <crate::LirType as rkyv::Archive>::Resolver,
}

#[cfg(feature = "rkyv")]
unsafe impl<Value: rkyv::Archive> rkyv::Portable for ArchivedActionStoreTarget<Value>
where
    <u64 as rkyv::Archive>::Archived: rkyv::Portable,
    <u32 as rkyv::Archive>::Archived: rkyv::Portable,
    <Value as rkyv::Archive>::Archived: rkyv::Portable,
    <crate::LirType as rkyv::Archive>::Archived: rkyv::Portable,
{}

#[cfg(feature = "rkyv")]
impl<Value: rkyv::Archive> rkyv::Archive for ActionStoreTarget<Value> {
    type Archived = ArchivedActionStoreTarget<Value>;
    type Resolver = ActionStoreTargetResolver<Value>;

    fn resolve(&self, resolver: Self::Resolver, out: rkyv::Place<Self::Archived>) {
        let field_ptr = unsafe { ::core::ptr::addr_of_mut!((*out.ptr()).storage) };
        let field_out = unsafe { rkyv::Place::from_field_unchecked(out, field_ptr) };
        rkyv::Archive::resolve(&self.storage, resolver.storage, field_out);
        let field_ptr = unsafe { ::core::ptr::addr_of_mut!((*out.ptr()).lane) };
        let field_out = unsafe { rkyv::Place::from_field_unchecked(out, field_ptr) };
        rkyv::Archive::resolve(&self.lane, resolver.lane, field_out);
        let field_ptr = unsafe { ::core::ptr::addr_of_mut!((*out.ptr()).address) };
        let field_out = unsafe { rkyv::Place::from_field_unchecked(out, field_ptr) };
        rkyv::Archive::resolve(&self.address, resolver.address, field_out);
        let field_ptr = unsafe { ::core::ptr::addr_of_mut!((*out.ptr()).address_ty) };
        let field_out = unsafe { rkyv::Place::from_field_unchecked(out, field_ptr) };
        rkyv::Archive::resolve(&self.address_ty, resolver.address_ty, field_out);
    }
}

#[cfg(feature = "rkyv")]
impl<Value: rkyv::Archive, S: rkyv::rancor::Fallible + ?Sized> rkyv::Serialize<S> for ActionStoreTarget<Value>
where
    u64: rkyv::Serialize<S>,
    u32: rkyv::Serialize<S>,
    Value: rkyv::Serialize<S>,
    crate::LirType: rkyv::Serialize<S>,
{
    fn serialize(&self, serializer: &mut S) -> Result<Self::Resolver, S::Error> {
        Ok(ActionStoreTargetResolver {
            storage: rkyv::Serialize::serialize(&self.storage, serializer)?,
            lane: rkyv::Serialize::serialize(&self.lane, serializer)?,
            address: rkyv::Serialize::serialize(&self.address, serializer)?,
            address_ty: rkyv::Serialize::serialize(&self.address_ty, serializer)?,
        })
    }
}

#[cfg(feature = "rkyv")]
impl<Value: rkyv::Archive, D: rkyv::rancor::Fallible + ?Sized> rkyv::Deserialize<ActionStoreTarget<Value>, D>
    for ArchivedActionStoreTarget<Value>
where
    <u64 as rkyv::Archive>::Archived: rkyv::Deserialize<u64, D>,
    <u32 as rkyv::Archive>::Archived: rkyv::Deserialize<u32, D>,
    <Value as rkyv::Archive>::Archived: rkyv::Deserialize<Value, D>,
    <crate::LirType as rkyv::Archive>::Archived: rkyv::Deserialize<crate::LirType, D>,
{
    fn deserialize(&self, deserializer: &mut D) -> Result<ActionStoreTarget<Value>, D::Error> {
        Ok(ActionStoreTarget {
            storage: rkyv::Deserialize::deserialize(&self.storage, deserializer)?,
            lane: rkyv::Deserialize::deserialize(&self.lane, deserializer)?,
            address: rkyv::Deserialize::deserialize(&self.address, deserializer)?,
            address_ty: rkyv::Deserialize::deserialize(&self.address_ty, deserializer)?,
        })
    }
}

/// A named saved LIR struct definition.
#[derive(Clone, Debug, PartialEq, Eq)]
pub struct StructDef {
    pub name: alloc::string::String,
    pub fields: alloc::vec::Vec<crate::FieldDef>,
}

#[cfg(feature = "rkyv")]
#[derive(rkyv::bytecheck::CheckBytes)]
#[bytecheck(crate = rkyv::bytecheck)]
#[repr(C)]
pub struct ArchivedStructDef {
    pub name: <alloc::string::String as rkyv::Archive>::Archived,
    pub fields: <alloc::vec::Vec<crate::FieldDef> as rkyv::Archive>::Archived,
}

#[cfg(feature = "rkyv")]
#[allow(dead_code)]
pub struct StructDefResolver {
    name: <alloc::string::String as rkyv::Archive>::Resolver,
    fields: <alloc::vec::Vec<crate::FieldDef> as rkyv::Archive>::Resolver,
}

#[cfg(feature = "rkyv")]
unsafe impl rkyv::Portable for ArchivedStructDef
where
    <alloc::string::String as rkyv::Archive>::Archived: rkyv::Portable,
    <alloc::vec::Vec<crate::FieldDef> as rkyv::Archive>::Archived: rkyv::Portable,
{}

#[cfg(feature = "rkyv")]
impl rkyv::Archive for StructDef {
    type Archived = ArchivedStructDef;
    type Resolver = StructDefResolver;

    fn resolve(&self, resolver: Self::Resolver, out: rkyv::Place<Self::Archived>) {
        let field_ptr = unsafe { ::core::ptr::addr_of_mut!((*out.ptr()).name) };
        let field_out = unsafe { rkyv::Place::from_field_unchecked(out, field_ptr) };
        rkyv::Archive::resolve(&self.name, resolver.name, field_out);
        let field_ptr = unsafe { ::core::ptr::addr_of_mut!((*out.ptr()).fields) };
        let field_out = unsafe { rkyv::Place::from_field_unchecked(out, field_ptr) };
        rkyv::Archive::resolve(&self.fields, resolver.fields, field_out);
    }
}

#[cfg(feature = "rkyv")]
impl<S: rkyv::rancor::Fallible + ?Sized> rkyv::Serialize<S> for StructDef
where
    alloc::string::String: rkyv::Serialize<S>,
    alloc::vec::Vec<crate::FieldDef>: rkyv::Serialize<S>,
{
    fn serialize(&self, serializer: &mut S) -> Result<Self::Resolver, S::Error> {
        Ok(StructDefResolver {
            name: rkyv::Serialize::serialize(&self.name, serializer)?,
            fields: rkyv::Serialize::serialize(&self.fields, serializer)?,
        })
    }
}

#[cfg(feature = "rkyv")]
impl<D: rkyv::rancor::Fallible + ?Sized> rkyv::Deserialize<StructDef, D>
    for ArchivedStructDef
where
    <alloc::string::String as rkyv::Archive>::Archived: rkyv::Deserialize<alloc::string::String, D>,
    <alloc::vec::Vec<crate::FieldDef> as rkyv::Archive>::Archived: rkyv::Deserialize<alloc::vec::Vec<crate::FieldDef>, D>,
{
    fn deserialize(&self, deserializer: &mut D) -> Result<StructDef, D::Error> {
        Ok(StructDef {
            name: rkyv::Deserialize::deserialize(&self.name, deserializer)?,
            fields: rkyv::Deserialize::deserialize(&self.fields, deserializer)?,
        })
    }
}

